zero:
  replicaCount: 1
  persistence:
    size: 8Gi
alpha:
  replicaCount: 1
  persistence:
    size: 10Gi
  extraFlags: "--graphql extensions=false"
ratel:
  enabled: false
backups:
  full:
    enabled: false
  volume:
    enabled: true
    mountPath: /dgraph/export
    claim: orbital-scratch-exports
