zero:
  replicaCount: 1
  persistence:
    size: 8Gi
alpha:
  replicaCount: 1
  persistence:
    size: 25Gi
  extraFlags: "--graphql extensions=false"
ratel:
  enabled: true
  image:
    # repository: dgraph/ratel
    tag: latest
backups:
  full:
    enabled: true
    schedule: "0 0 31 2 *"  # Feb 31 = never fires; only here to enable the volume mount on alpha
  volume:
    enabled: true
    mountPath: /dgraph/export
    claim: orbital-dgraph-exports
