zero:
  replicaCount: 1
  persistence:
    size: 8Gi
alpha:
  replicaCount: 1
  persistence:
    size: 25Gi
  extraFlags: "--graphql extensions=false"
ratel:
  enabled: true
  image:
    # repository: dgraph/ratel
    tag: latest
backups:
  full:
    enabled: false
  volume:
    enabled: true
    mountPath: /dgraph/export
    claim: orbital-dgraph-exports
