// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/armada/orbital/internal/orb/store/importrecord"
	"github.com/armada/orbital/internal/orb/store/pendingoverride"
	"github.com/armada/orbital/internal/orb/store/predicate"
	"github.com/armada/orbital/internal/orb/store/publishedreport"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeImportRecord    = "ImportRecord"
	TypePendingOverride = "PendingOverride"
	TypePublishedReport = "PublishedReport"
)

// ImportRecordMutation represents an operation that mutates the ImportRecord nodes in the graph.
type ImportRecordMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	tag           *string
	digest        *string
	dc_orb_id     *string
	export_job_id *string
	imported_at   *time.Time
	status        *importrecord.Status
	verification  *importrecord.Verification
	layers_json   *string
	error         *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ImportRecord, error)
	predicates    []predicate.ImportRecord
}

var _ ent.Mutation = (*ImportRecordMutation)(nil)

// importrecordOption allows management of the mutation configuration using functional options.
type importrecordOption func(*ImportRecordMutation)

// newImportRecordMutation creates new mutation for the ImportRecord entity.
func newImportRecordMutation(c config, op Op, opts ...importrecordOption) *ImportRecordMutation {
	m := &ImportRecordMutation{
		config:        c,
		op:            op,
		typ:           TypeImportRecord,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withImportRecordID sets the ID field of the mutation.
func withImportRecordID(id uuid.UUID) importrecordOption {
	return func(m *ImportRecordMutation) {
		var (
			err   error
			once  sync.Once
			value *ImportRecord
		)
		m.oldValue = func(ctx context.Context) (*ImportRecord, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ImportRecord.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withImportRecord sets the old ImportRecord of the mutation.
func withImportRecord(node *ImportRecord) importrecordOption {
	return func(m *ImportRecordMutation) {
		m.oldValue = func(context.Context) (*ImportRecord, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ImportRecordMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ImportRecordMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("store: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ImportRecord entities.
func (m *ImportRecordMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ImportRecordMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ImportRecordMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ImportRecord.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTag sets the "tag" field.
func (m *ImportRecordMutation) SetTag(s string) {
	m.tag = &s
}

// Tag returns the value of the "tag" field in the mutation.
func (m *ImportRecordMutation) Tag() (r string, exists bool) {
	v := m.tag
	if v == nil {
		return
	}
	return *v, true
}

// OldTag returns the old "tag" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldTag(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTag is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTag requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTag: %w", err)
	}
	return oldValue.Tag, nil
}

// ResetTag resets all changes to the "tag" field.
func (m *ImportRecordMutation) ResetTag() {
	m.tag = nil
}

// SetDigest sets the "digest" field.
func (m *ImportRecordMutation) SetDigest(s string) {
	m.digest = &s
}

// Digest returns the value of the "digest" field in the mutation.
func (m *ImportRecordMutation) Digest() (r string, exists bool) {
	v := m.digest
	if v == nil {
		return
	}
	return *v, true
}

// OldDigest returns the old "digest" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldDigest(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDigest is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDigest requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDigest: %w", err)
	}
	return oldValue.Digest, nil
}

// ResetDigest resets all changes to the "digest" field.
func (m *ImportRecordMutation) ResetDigest() {
	m.digest = nil
}

// SetDcOrbID sets the "dc_orb_id" field.
func (m *ImportRecordMutation) SetDcOrbID(s string) {
	m.dc_orb_id = &s
}

// DcOrbID returns the value of the "dc_orb_id" field in the mutation.
func (m *ImportRecordMutation) DcOrbID() (r string, exists bool) {
	v := m.dc_orb_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDcOrbID returns the old "dc_orb_id" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldDcOrbID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDcOrbID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDcOrbID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDcOrbID: %w", err)
	}
	return oldValue.DcOrbID, nil
}

// ClearDcOrbID clears the value of the "dc_orb_id" field.
func (m *ImportRecordMutation) ClearDcOrbID() {
	m.dc_orb_id = nil
	m.clearedFields[importrecord.FieldDcOrbID] = struct{}{}
}

// DcOrbIDCleared returns if the "dc_orb_id" field was cleared in this mutation.
func (m *ImportRecordMutation) DcOrbIDCleared() bool {
	_, ok := m.clearedFields[importrecord.FieldDcOrbID]
	return ok
}

// ResetDcOrbID resets all changes to the "dc_orb_id" field.
func (m *ImportRecordMutation) ResetDcOrbID() {
	m.dc_orb_id = nil
	delete(m.clearedFields, importrecord.FieldDcOrbID)
}

// SetExportJobID sets the "export_job_id" field.
func (m *ImportRecordMutation) SetExportJobID(s string) {
	m.export_job_id = &s
}

// ExportJobID returns the value of the "export_job_id" field in the mutation.
func (m *ImportRecordMutation) ExportJobID() (r string, exists bool) {
	v := m.export_job_id
	if v == nil {
		return
	}
	return *v, true
}

// OldExportJobID returns the old "export_job_id" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldExportJobID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExportJobID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExportJobID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExportJobID: %w", err)
	}
	return oldValue.ExportJobID, nil
}

// ClearExportJobID clears the value of the "export_job_id" field.
func (m *ImportRecordMutation) ClearExportJobID() {
	m.export_job_id = nil
	m.clearedFields[importrecord.FieldExportJobID] = struct{}{}
}

// ExportJobIDCleared returns if the "export_job_id" field was cleared in this mutation.
func (m *ImportRecordMutation) ExportJobIDCleared() bool {
	_, ok := m.clearedFields[importrecord.FieldExportJobID]
	return ok
}

// ResetExportJobID resets all changes to the "export_job_id" field.
func (m *ImportRecordMutation) ResetExportJobID() {
	m.export_job_id = nil
	delete(m.clearedFields, importrecord.FieldExportJobID)
}

// SetImportedAt sets the "imported_at" field.
func (m *ImportRecordMutation) SetImportedAt(t time.Time) {
	m.imported_at = &t
}

// ImportedAt returns the value of the "imported_at" field in the mutation.
func (m *ImportRecordMutation) ImportedAt() (r time.Time, exists bool) {
	v := m.imported_at
	if v == nil {
		return
	}
	return *v, true
}

// OldImportedAt returns the old "imported_at" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldImportedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImportedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImportedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImportedAt: %w", err)
	}
	return oldValue.ImportedAt, nil
}

// ResetImportedAt resets all changes to the "imported_at" field.
func (m *ImportRecordMutation) ResetImportedAt() {
	m.imported_at = nil
}

// SetStatus sets the "status" field.
func (m *ImportRecordMutation) SetStatus(i importrecord.Status) {
	m.status = &i
}

// Status returns the value of the "status" field in the mutation.
func (m *ImportRecordMutation) Status() (r importrecord.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldStatus(ctx context.Context) (v importrecord.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *ImportRecordMutation) ResetStatus() {
	m.status = nil
}

// SetVerification sets the "verification" field.
func (m *ImportRecordMutation) SetVerification(i importrecord.Verification) {
	m.verification = &i
}

// Verification returns the value of the "verification" field in the mutation.
func (m *ImportRecordMutation) Verification() (r importrecord.Verification, exists bool) {
	v := m.verification
	if v == nil {
		return
	}
	return *v, true
}

// OldVerification returns the old "verification" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldVerification(ctx context.Context) (v importrecord.Verification, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVerification is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVerification requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVerification: %w", err)
	}
	return oldValue.Verification, nil
}

// ClearVerification clears the value of the "verification" field.
func (m *ImportRecordMutation) ClearVerification() {
	m.verification = nil
	m.clearedFields[importrecord.FieldVerification] = struct{}{}
}

// VerificationCleared returns if the "verification" field was cleared in this mutation.
func (m *ImportRecordMutation) VerificationCleared() bool {
	_, ok := m.clearedFields[importrecord.FieldVerification]
	return ok
}

// ResetVerification resets all changes to the "verification" field.
func (m *ImportRecordMutation) ResetVerification() {
	m.verification = nil
	delete(m.clearedFields, importrecord.FieldVerification)
}

// SetLayersJSON sets the "layers_json" field.
func (m *ImportRecordMutation) SetLayersJSON(s string) {
	m.layers_json = &s
}

// LayersJSON returns the value of the "layers_json" field in the mutation.
func (m *ImportRecordMutation) LayersJSON() (r string, exists bool) {
	v := m.layers_json
	if v == nil {
		return
	}
	return *v, true
}

// OldLayersJSON returns the old "layers_json" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldLayersJSON(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLayersJSON is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLayersJSON requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLayersJSON: %w", err)
	}
	return oldValue.LayersJSON, nil
}

// ClearLayersJSON clears the value of the "layers_json" field.
func (m *ImportRecordMutation) ClearLayersJSON() {
	m.layers_json = nil
	m.clearedFields[importrecord.FieldLayersJSON] = struct{}{}
}

// LayersJSONCleared returns if the "layers_json" field was cleared in this mutation.
func (m *ImportRecordMutation) LayersJSONCleared() bool {
	_, ok := m.clearedFields[importrecord.FieldLayersJSON]
	return ok
}

// ResetLayersJSON resets all changes to the "layers_json" field.
func (m *ImportRecordMutation) ResetLayersJSON() {
	m.layers_json = nil
	delete(m.clearedFields, importrecord.FieldLayersJSON)
}

// SetError sets the "error" field.
func (m *ImportRecordMutation) SetError(s string) {
	m.error = &s
}

// Error returns the value of the "error" field in the mutation.
func (m *ImportRecordMutation) Error() (r string, exists bool) {
	v := m.error
	if v == nil {
		return
	}
	return *v, true
}

// OldError returns the old "error" field's value of the ImportRecord entity.
// If the ImportRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ImportRecordMutation) OldError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldError: %w", err)
	}
	return oldValue.Error, nil
}

// ClearError clears the value of the "error" field.
func (m *ImportRecordMutation) ClearError() {
	m.error = nil
	m.clearedFields[importrecord.FieldError] = struct{}{}
}

// ErrorCleared returns if the "error" field was cleared in this mutation.
func (m *ImportRecordMutation) ErrorCleared() bool {
	_, ok := m.clearedFields[importrecord.FieldError]
	return ok
}

// ResetError resets all changes to the "error" field.
func (m *ImportRecordMutation) ResetError() {
	m.error = nil
	delete(m.clearedFields, importrecord.FieldError)
}

// Where appends a list predicates to the ImportRecordMutation builder.
func (m *ImportRecordMutation) Where(ps ...predicate.ImportRecord) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ImportRecordMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ImportRecordMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ImportRecord, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ImportRecordMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ImportRecordMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ImportRecord).
func (m *ImportRecordMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ImportRecordMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.tag != nil {
		fields = append(fields, importrecord.FieldTag)
	}
	if m.digest != nil {
		fields = append(fields, importrecord.FieldDigest)
	}
	if m.dc_orb_id != nil {
		fields = append(fields, importrecord.FieldDcOrbID)
	}
	if m.export_job_id != nil {
		fields = append(fields, importrecord.FieldExportJobID)
	}
	if m.imported_at != nil {
		fields = append(fields, importrecord.FieldImportedAt)
	}
	if m.status != nil {
		fields = append(fields, importrecord.FieldStatus)
	}
	if m.verification != nil {
		fields = append(fields, importrecord.FieldVerification)
	}
	if m.layers_json != nil {
		fields = append(fields, importrecord.FieldLayersJSON)
	}
	if m.error != nil {
		fields = append(fields, importrecord.FieldError)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ImportRecordMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case importrecord.FieldTag:
		return m.Tag()
	case importrecord.FieldDigest:
		return m.Digest()
	case importrecord.FieldDcOrbID:
		return m.DcOrbID()
	case importrecord.FieldExportJobID:
		return m.ExportJobID()
	case importrecord.FieldImportedAt:
		return m.ImportedAt()
	case importrecord.FieldStatus:
		return m.Status()
	case importrecord.FieldVerification:
		return m.Verification()
	case importrecord.FieldLayersJSON:
		return m.LayersJSON()
	case importrecord.FieldError:
		return m.Error()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ImportRecordMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case importrecord.FieldTag:
		return m.OldTag(ctx)
	case importrecord.FieldDigest:
		return m.OldDigest(ctx)
	case importrecord.FieldDcOrbID:
		return m.OldDcOrbID(ctx)
	case importrecord.FieldExportJobID:
		return m.OldExportJobID(ctx)
	case importrecord.FieldImportedAt:
		return m.OldImportedAt(ctx)
	case importrecord.FieldStatus:
		return m.OldStatus(ctx)
	case importrecord.FieldVerification:
		return m.OldVerification(ctx)
	case importrecord.FieldLayersJSON:
		return m.OldLayersJSON(ctx)
	case importrecord.FieldError:
		return m.OldError(ctx)
	}
	return nil, fmt.Errorf("unknown ImportRecord field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ImportRecordMutation) SetField(name string, value ent.Value) error {
	switch name {
	case importrecord.FieldTag:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTag(v)
		return nil
	case importrecord.FieldDigest:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDigest(v)
		return nil
	case importrecord.FieldDcOrbID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDcOrbID(v)
		return nil
	case importrecord.FieldExportJobID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExportJobID(v)
		return nil
	case importrecord.FieldImportedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImportedAt(v)
		return nil
	case importrecord.FieldStatus:
		v, ok := value.(importrecord.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case importrecord.FieldVerification:
		v, ok := value.(importrecord.Verification)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVerification(v)
		return nil
	case importrecord.FieldLayersJSON:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLayersJSON(v)
		return nil
	case importrecord.FieldError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetError(v)
		return nil
	}
	return fmt.Errorf("unknown ImportRecord field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ImportRecordMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ImportRecordMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ImportRecordMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ImportRecord numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ImportRecordMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(importrecord.FieldDcOrbID) {
		fields = append(fields, importrecord.FieldDcOrbID)
	}
	if m.FieldCleared(importrecord.FieldExportJobID) {
		fields = append(fields, importrecord.FieldExportJobID)
	}
	if m.FieldCleared(importrecord.FieldVerification) {
		fields = append(fields, importrecord.FieldVerification)
	}
	if m.FieldCleared(importrecord.FieldLayersJSON) {
		fields = append(fields, importrecord.FieldLayersJSON)
	}
	if m.FieldCleared(importrecord.FieldError) {
		fields = append(fields, importrecord.FieldError)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ImportRecordMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ImportRecordMutation) ClearField(name string) error {
	switch name {
	case importrecord.FieldDcOrbID:
		m.ClearDcOrbID()
		return nil
	case importrecord.FieldExportJobID:
		m.ClearExportJobID()
		return nil
	case importrecord.FieldVerification:
		m.ClearVerification()
		return nil
	case importrecord.FieldLayersJSON:
		m.ClearLayersJSON()
		return nil
	case importrecord.FieldError:
		m.ClearError()
		return nil
	}
	return fmt.Errorf("unknown ImportRecord nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ImportRecordMutation) ResetField(name string) error {
	switch name {
	case importrecord.FieldTag:
		m.ResetTag()
		return nil
	case importrecord.FieldDigest:
		m.ResetDigest()
		return nil
	case importrecord.FieldDcOrbID:
		m.ResetDcOrbID()
		return nil
	case importrecord.FieldExportJobID:
		m.ResetExportJobID()
		return nil
	case importrecord.FieldImportedAt:
		m.ResetImportedAt()
		return nil
	case importrecord.FieldStatus:
		m.ResetStatus()
		return nil
	case importrecord.FieldVerification:
		m.ResetVerification()
		return nil
	case importrecord.FieldLayersJSON:
		m.ResetLayersJSON()
		return nil
	case importrecord.FieldError:
		m.ResetError()
		return nil
	}
	return fmt.Errorf("unknown ImportRecord field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ImportRecordMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ImportRecordMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ImportRecordMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ImportRecordMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ImportRecordMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ImportRecordMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ImportRecordMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ImportRecord unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ImportRecordMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ImportRecord edge %s", name)
}

// PendingOverrideMutation represents an operation that mutates the PendingOverride nodes in the graph.
type PendingOverrideMutation struct {
	config
	op                     Op
	typ                    string
	id                     *uuid.UUID
	type_name              *string
	entry_orb_id           *string
	field                  *string
	intended_value         *string
	override_value         *string
	who                    *string
	when_str               *string
	first_seen_at          *time.Time
	intended_at_version    *int
	addintended_at_version *int
	clearedFields          map[string]struct{}
	done                   bool
	oldValue               func(context.Context) (*PendingOverride, error)
	predicates             []predicate.PendingOverride
}

var _ ent.Mutation = (*PendingOverrideMutation)(nil)

// pendingoverrideOption allows management of the mutation configuration using functional options.
type pendingoverrideOption func(*PendingOverrideMutation)

// newPendingOverrideMutation creates new mutation for the PendingOverride entity.
func newPendingOverrideMutation(c config, op Op, opts ...pendingoverrideOption) *PendingOverrideMutation {
	m := &PendingOverrideMutation{
		config:        c,
		op:            op,
		typ:           TypePendingOverride,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPendingOverrideID sets the ID field of the mutation.
func withPendingOverrideID(id uuid.UUID) pendingoverrideOption {
	return func(m *PendingOverrideMutation) {
		var (
			err   error
			once  sync.Once
			value *PendingOverride
		)
		m.oldValue = func(ctx context.Context) (*PendingOverride, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PendingOverride.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPendingOverride sets the old PendingOverride of the mutation.
func withPendingOverride(node *PendingOverride) pendingoverrideOption {
	return func(m *PendingOverrideMutation) {
		m.oldValue = func(context.Context) (*PendingOverride, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PendingOverrideMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PendingOverrideMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("store: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PendingOverride entities.
func (m *PendingOverrideMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PendingOverrideMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PendingOverrideMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PendingOverride.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTypeName sets the "type_name" field.
func (m *PendingOverrideMutation) SetTypeName(s string) {
	m.type_name = &s
}

// TypeName returns the value of the "type_name" field in the mutation.
func (m *PendingOverrideMutation) TypeName() (r string, exists bool) {
	v := m.type_name
	if v == nil {
		return
	}
	return *v, true
}

// OldTypeName returns the old "type_name" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldTypeName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTypeName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTypeName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTypeName: %w", err)
	}
	return oldValue.TypeName, nil
}

// ClearTypeName clears the value of the "type_name" field.
func (m *PendingOverrideMutation) ClearTypeName() {
	m.type_name = nil
	m.clearedFields[pendingoverride.FieldTypeName] = struct{}{}
}

// TypeNameCleared returns if the "type_name" field was cleared in this mutation.
func (m *PendingOverrideMutation) TypeNameCleared() bool {
	_, ok := m.clearedFields[pendingoverride.FieldTypeName]
	return ok
}

// ResetTypeName resets all changes to the "type_name" field.
func (m *PendingOverrideMutation) ResetTypeName() {
	m.type_name = nil
	delete(m.clearedFields, pendingoverride.FieldTypeName)
}

// SetEntryOrbID sets the "entry_orb_id" field.
func (m *PendingOverrideMutation) SetEntryOrbID(s string) {
	m.entry_orb_id = &s
}

// EntryOrbID returns the value of the "entry_orb_id" field in the mutation.
func (m *PendingOverrideMutation) EntryOrbID() (r string, exists bool) {
	v := m.entry_orb_id
	if v == nil {
		return
	}
	return *v, true
}

// OldEntryOrbID returns the old "entry_orb_id" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldEntryOrbID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEntryOrbID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEntryOrbID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEntryOrbID: %w", err)
	}
	return oldValue.EntryOrbID, nil
}

// ResetEntryOrbID resets all changes to the "entry_orb_id" field.
func (m *PendingOverrideMutation) ResetEntryOrbID() {
	m.entry_orb_id = nil
}

// SetFieldField sets the "field" field.
func (m *PendingOverrideMutation) SetFieldField(s string) {
	m.field = &s
}

// GetField returns the value of the "field" field in the mutation.
func (m *PendingOverrideMutation) GetField() (r string, exists bool) {
	v := m.field
	if v == nil {
		return
	}
	return *v, true
}

// GetOldField returns the old "field" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) GetOldField(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("GetOldField is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("GetOldField requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for GetOldField: %w", err)
	}
	return oldValue.Field, nil
}

// ResetFieldField resets all changes to the "field" field.
func (m *PendingOverrideMutation) ResetFieldField() {
	m.field = nil
}

// SetIntendedValue sets the "intended_value" field.
func (m *PendingOverrideMutation) SetIntendedValue(s string) {
	m.intended_value = &s
}

// IntendedValue returns the value of the "intended_value" field in the mutation.
func (m *PendingOverrideMutation) IntendedValue() (r string, exists bool) {
	v := m.intended_value
	if v == nil {
		return
	}
	return *v, true
}

// OldIntendedValue returns the old "intended_value" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldIntendedValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIntendedValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIntendedValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIntendedValue: %w", err)
	}
	return oldValue.IntendedValue, nil
}

// ClearIntendedValue clears the value of the "intended_value" field.
func (m *PendingOverrideMutation) ClearIntendedValue() {
	m.intended_value = nil
	m.clearedFields[pendingoverride.FieldIntendedValue] = struct{}{}
}

// IntendedValueCleared returns if the "intended_value" field was cleared in this mutation.
func (m *PendingOverrideMutation) IntendedValueCleared() bool {
	_, ok := m.clearedFields[pendingoverride.FieldIntendedValue]
	return ok
}

// ResetIntendedValue resets all changes to the "intended_value" field.
func (m *PendingOverrideMutation) ResetIntendedValue() {
	m.intended_value = nil
	delete(m.clearedFields, pendingoverride.FieldIntendedValue)
}

// SetOverrideValue sets the "override_value" field.
func (m *PendingOverrideMutation) SetOverrideValue(s string) {
	m.override_value = &s
}

// OverrideValue returns the value of the "override_value" field in the mutation.
func (m *PendingOverrideMutation) OverrideValue() (r string, exists bool) {
	v := m.override_value
	if v == nil {
		return
	}
	return *v, true
}

// OldOverrideValue returns the old "override_value" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldOverrideValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOverrideValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOverrideValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOverrideValue: %w", err)
	}
	return oldValue.OverrideValue, nil
}

// ClearOverrideValue clears the value of the "override_value" field.
func (m *PendingOverrideMutation) ClearOverrideValue() {
	m.override_value = nil
	m.clearedFields[pendingoverride.FieldOverrideValue] = struct{}{}
}

// OverrideValueCleared returns if the "override_value" field was cleared in this mutation.
func (m *PendingOverrideMutation) OverrideValueCleared() bool {
	_, ok := m.clearedFields[pendingoverride.FieldOverrideValue]
	return ok
}

// ResetOverrideValue resets all changes to the "override_value" field.
func (m *PendingOverrideMutation) ResetOverrideValue() {
	m.override_value = nil
	delete(m.clearedFields, pendingoverride.FieldOverrideValue)
}

// SetWho sets the "who" field.
func (m *PendingOverrideMutation) SetWho(s string) {
	m.who = &s
}

// Who returns the value of the "who" field in the mutation.
func (m *PendingOverrideMutation) Who() (r string, exists bool) {
	v := m.who
	if v == nil {
		return
	}
	return *v, true
}

// OldWho returns the old "who" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldWho(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWho is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWho requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWho: %w", err)
	}
	return oldValue.Who, nil
}

// ClearWho clears the value of the "who" field.
func (m *PendingOverrideMutation) ClearWho() {
	m.who = nil
	m.clearedFields[pendingoverride.FieldWho] = struct{}{}
}

// WhoCleared returns if the "who" field was cleared in this mutation.
func (m *PendingOverrideMutation) WhoCleared() bool {
	_, ok := m.clearedFields[pendingoverride.FieldWho]
	return ok
}

// ResetWho resets all changes to the "who" field.
func (m *PendingOverrideMutation) ResetWho() {
	m.who = nil
	delete(m.clearedFields, pendingoverride.FieldWho)
}

// SetWhenStr sets the "when_str" field.
func (m *PendingOverrideMutation) SetWhenStr(s string) {
	m.when_str = &s
}

// WhenStr returns the value of the "when_str" field in the mutation.
func (m *PendingOverrideMutation) WhenStr() (r string, exists bool) {
	v := m.when_str
	if v == nil {
		return
	}
	return *v, true
}

// OldWhenStr returns the old "when_str" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldWhenStr(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWhenStr is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWhenStr requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWhenStr: %w", err)
	}
	return oldValue.WhenStr, nil
}

// ClearWhenStr clears the value of the "when_str" field.
func (m *PendingOverrideMutation) ClearWhenStr() {
	m.when_str = nil
	m.clearedFields[pendingoverride.FieldWhenStr] = struct{}{}
}

// WhenStrCleared returns if the "when_str" field was cleared in this mutation.
func (m *PendingOverrideMutation) WhenStrCleared() bool {
	_, ok := m.clearedFields[pendingoverride.FieldWhenStr]
	return ok
}

// ResetWhenStr resets all changes to the "when_str" field.
func (m *PendingOverrideMutation) ResetWhenStr() {
	m.when_str = nil
	delete(m.clearedFields, pendingoverride.FieldWhenStr)
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (m *PendingOverrideMutation) SetFirstSeenAt(t time.Time) {
	m.first_seen_at = &t
}

// FirstSeenAt returns the value of the "first_seen_at" field in the mutation.
func (m *PendingOverrideMutation) FirstSeenAt() (r time.Time, exists bool) {
	v := m.first_seen_at
	if v == nil {
		return
	}
	return *v, true
}

// OldFirstSeenAt returns the old "first_seen_at" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldFirstSeenAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFirstSeenAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFirstSeenAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFirstSeenAt: %w", err)
	}
	return oldValue.FirstSeenAt, nil
}

// ResetFirstSeenAt resets all changes to the "first_seen_at" field.
func (m *PendingOverrideMutation) ResetFirstSeenAt() {
	m.first_seen_at = nil
}

// SetIntendedAtVersion sets the "intended_at_version" field.
func (m *PendingOverrideMutation) SetIntendedAtVersion(i int) {
	m.intended_at_version = &i
	m.addintended_at_version = nil
}

// IntendedAtVersion returns the value of the "intended_at_version" field in the mutation.
func (m *PendingOverrideMutation) IntendedAtVersion() (r int, exists bool) {
	v := m.intended_at_version
	if v == nil {
		return
	}
	return *v, true
}

// OldIntendedAtVersion returns the old "intended_at_version" field's value of the PendingOverride entity.
// If the PendingOverride object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PendingOverrideMutation) OldIntendedAtVersion(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIntendedAtVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIntendedAtVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIntendedAtVersion: %w", err)
	}
	return oldValue.IntendedAtVersion, nil
}

// AddIntendedAtVersion adds i to the "intended_at_version" field.
func (m *PendingOverrideMutation) AddIntendedAtVersion(i int) {
	if m.addintended_at_version != nil {
		*m.addintended_at_version += i
	} else {
		m.addintended_at_version = &i
	}
}

// AddedIntendedAtVersion returns the value that was added to the "intended_at_version" field in this mutation.
func (m *PendingOverrideMutation) AddedIntendedAtVersion() (r int, exists bool) {
	v := m.addintended_at_version
	if v == nil {
		return
	}
	return *v, true
}

// ClearIntendedAtVersion clears the value of the "intended_at_version" field.
func (m *PendingOverrideMutation) ClearIntendedAtVersion() {
	m.intended_at_version = nil
	m.addintended_at_version = nil
	m.clearedFields[pendingoverride.FieldIntendedAtVersion] = struct{}{}
}

// IntendedAtVersionCleared returns if the "intended_at_version" field was cleared in this mutation.
func (m *PendingOverrideMutation) IntendedAtVersionCleared() bool {
	_, ok := m.clearedFields[pendingoverride.FieldIntendedAtVersion]
	return ok
}

// ResetIntendedAtVersion resets all changes to the "intended_at_version" field.
func (m *PendingOverrideMutation) ResetIntendedAtVersion() {
	m.intended_at_version = nil
	m.addintended_at_version = nil
	delete(m.clearedFields, pendingoverride.FieldIntendedAtVersion)
}

// Where appends a list predicates to the PendingOverrideMutation builder.
func (m *PendingOverrideMutation) Where(ps ...predicate.PendingOverride) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PendingOverrideMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PendingOverrideMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PendingOverride, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PendingOverrideMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PendingOverrideMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PendingOverride).
func (m *PendingOverrideMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PendingOverrideMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.type_name != nil {
		fields = append(fields, pendingoverride.FieldTypeName)
	}
	if m.entry_orb_id != nil {
		fields = append(fields, pendingoverride.FieldEntryOrbID)
	}
	if m.field != nil {
		fields = append(fields, pendingoverride.FieldField)
	}
	if m.intended_value != nil {
		fields = append(fields, pendingoverride.FieldIntendedValue)
	}
	if m.override_value != nil {
		fields = append(fields, pendingoverride.FieldOverrideValue)
	}
	if m.who != nil {
		fields = append(fields, pendingoverride.FieldWho)
	}
	if m.when_str != nil {
		fields = append(fields, pendingoverride.FieldWhenStr)
	}
	if m.first_seen_at != nil {
		fields = append(fields, pendingoverride.FieldFirstSeenAt)
	}
	if m.intended_at_version != nil {
		fields = append(fields, pendingoverride.FieldIntendedAtVersion)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PendingOverrideMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pendingoverride.FieldTypeName:
		return m.TypeName()
	case pendingoverride.FieldEntryOrbID:
		return m.EntryOrbID()
	case pendingoverride.FieldField:
		return m.GetField()
	case pendingoverride.FieldIntendedValue:
		return m.IntendedValue()
	case pendingoverride.FieldOverrideValue:
		return m.OverrideValue()
	case pendingoverride.FieldWho:
		return m.Who()
	case pendingoverride.FieldWhenStr:
		return m.WhenStr()
	case pendingoverride.FieldFirstSeenAt:
		return m.FirstSeenAt()
	case pendingoverride.FieldIntendedAtVersion:
		return m.IntendedAtVersion()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PendingOverrideMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pendingoverride.FieldTypeName:
		return m.OldTypeName(ctx)
	case pendingoverride.FieldEntryOrbID:
		return m.OldEntryOrbID(ctx)
	case pendingoverride.FieldField:
		return m.GetOldField(ctx)
	case pendingoverride.FieldIntendedValue:
		return m.OldIntendedValue(ctx)
	case pendingoverride.FieldOverrideValue:
		return m.OldOverrideValue(ctx)
	case pendingoverride.FieldWho:
		return m.OldWho(ctx)
	case pendingoverride.FieldWhenStr:
		return m.OldWhenStr(ctx)
	case pendingoverride.FieldFirstSeenAt:
		return m.OldFirstSeenAt(ctx)
	case pendingoverride.FieldIntendedAtVersion:
		return m.OldIntendedAtVersion(ctx)
	}
	return nil, fmt.Errorf("unknown PendingOverride field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PendingOverrideMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pendingoverride.FieldTypeName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTypeName(v)
		return nil
	case pendingoverride.FieldEntryOrbID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEntryOrbID(v)
		return nil
	case pendingoverride.FieldField:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFieldField(v)
		return nil
	case pendingoverride.FieldIntendedValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIntendedValue(v)
		return nil
	case pendingoverride.FieldOverrideValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOverrideValue(v)
		return nil
	case pendingoverride.FieldWho:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWho(v)
		return nil
	case pendingoverride.FieldWhenStr:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWhenStr(v)
		return nil
	case pendingoverride.FieldFirstSeenAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFirstSeenAt(v)
		return nil
	case pendingoverride.FieldIntendedAtVersion:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIntendedAtVersion(v)
		return nil
	}
	return fmt.Errorf("unknown PendingOverride field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PendingOverrideMutation) AddedFields() []string {
	var fields []string
	if m.addintended_at_version != nil {
		fields = append(fields, pendingoverride.FieldIntendedAtVersion)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PendingOverrideMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pendingoverride.FieldIntendedAtVersion:
		return m.AddedIntendedAtVersion()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PendingOverrideMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pendingoverride.FieldIntendedAtVersion:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddIntendedAtVersion(v)
		return nil
	}
	return fmt.Errorf("unknown PendingOverride numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PendingOverrideMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(pendingoverride.FieldTypeName) {
		fields = append(fields, pendingoverride.FieldTypeName)
	}
	if m.FieldCleared(pendingoverride.FieldIntendedValue) {
		fields = append(fields, pendingoverride.FieldIntendedValue)
	}
	if m.FieldCleared(pendingoverride.FieldOverrideValue) {
		fields = append(fields, pendingoverride.FieldOverrideValue)
	}
	if m.FieldCleared(pendingoverride.FieldWho) {
		fields = append(fields, pendingoverride.FieldWho)
	}
	if m.FieldCleared(pendingoverride.FieldWhenStr) {
		fields = append(fields, pendingoverride.FieldWhenStr)
	}
	if m.FieldCleared(pendingoverride.FieldIntendedAtVersion) {
		fields = append(fields, pendingoverride.FieldIntendedAtVersion)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PendingOverrideMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PendingOverrideMutation) ClearField(name string) error {
	switch name {
	case pendingoverride.FieldTypeName:
		m.ClearTypeName()
		return nil
	case pendingoverride.FieldIntendedValue:
		m.ClearIntendedValue()
		return nil
	case pendingoverride.FieldOverrideValue:
		m.ClearOverrideValue()
		return nil
	case pendingoverride.FieldWho:
		m.ClearWho()
		return nil
	case pendingoverride.FieldWhenStr:
		m.ClearWhenStr()
		return nil
	case pendingoverride.FieldIntendedAtVersion:
		m.ClearIntendedAtVersion()
		return nil
	}
	return fmt.Errorf("unknown PendingOverride nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PendingOverrideMutation) ResetField(name string) error {
	switch name {
	case pendingoverride.FieldTypeName:
		m.ResetTypeName()
		return nil
	case pendingoverride.FieldEntryOrbID:
		m.ResetEntryOrbID()
		return nil
	case pendingoverride.FieldField:
		m.ResetFieldField()
		return nil
	case pendingoverride.FieldIntendedValue:
		m.ResetIntendedValue()
		return nil
	case pendingoverride.FieldOverrideValue:
		m.ResetOverrideValue()
		return nil
	case pendingoverride.FieldWho:
		m.ResetWho()
		return nil
	case pendingoverride.FieldWhenStr:
		m.ResetWhenStr()
		return nil
	case pendingoverride.FieldFirstSeenAt:
		m.ResetFirstSeenAt()
		return nil
	case pendingoverride.FieldIntendedAtVersion:
		m.ResetIntendedAtVersion()
		return nil
	}
	return fmt.Errorf("unknown PendingOverride field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PendingOverrideMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PendingOverrideMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PendingOverrideMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PendingOverrideMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PendingOverrideMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PendingOverrideMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PendingOverrideMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PendingOverride unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PendingOverrideMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PendingOverride edge %s", name)
}

// PublishedReportMutation represents an operation that mutates the PublishedReport nodes in the graph.
type PublishedReportMutation struct {
	config
	op             Op
	typ            string
	id             *uuid.UUID
	dc_orb_id      *string
	published_at   *time.Time
	s3_key         *string
	s3_endpoint    *string
	entry_count    *int
	addentry_count *int
	status         *publishedreport.Status
	summary_json   *string
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*PublishedReport, error)
	predicates     []predicate.PublishedReport
}

var _ ent.Mutation = (*PublishedReportMutation)(nil)

// publishedreportOption allows management of the mutation configuration using functional options.
type publishedreportOption func(*PublishedReportMutation)

// newPublishedReportMutation creates new mutation for the PublishedReport entity.
func newPublishedReportMutation(c config, op Op, opts ...publishedreportOption) *PublishedReportMutation {
	m := &PublishedReportMutation{
		config:        c,
		op:            op,
		typ:           TypePublishedReport,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPublishedReportID sets the ID field of the mutation.
func withPublishedReportID(id uuid.UUID) publishedreportOption {
	return func(m *PublishedReportMutation) {
		var (
			err   error
			once  sync.Once
			value *PublishedReport
		)
		m.oldValue = func(ctx context.Context) (*PublishedReport, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PublishedReport.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPublishedReport sets the old PublishedReport of the mutation.
func withPublishedReport(node *PublishedReport) publishedreportOption {
	return func(m *PublishedReportMutation) {
		m.oldValue = func(context.Context) (*PublishedReport, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PublishedReportMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PublishedReportMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("store: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PublishedReport entities.
func (m *PublishedReportMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PublishedReportMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PublishedReportMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PublishedReport.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDcOrbID sets the "dc_orb_id" field.
func (m *PublishedReportMutation) SetDcOrbID(s string) {
	m.dc_orb_id = &s
}

// DcOrbID returns the value of the "dc_orb_id" field in the mutation.
func (m *PublishedReportMutation) DcOrbID() (r string, exists bool) {
	v := m.dc_orb_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDcOrbID returns the old "dc_orb_id" field's value of the PublishedReport entity.
// If the PublishedReport object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PublishedReportMutation) OldDcOrbID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDcOrbID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDcOrbID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDcOrbID: %w", err)
	}
	return oldValue.DcOrbID, nil
}

// ResetDcOrbID resets all changes to the "dc_orb_id" field.
func (m *PublishedReportMutation) ResetDcOrbID() {
	m.dc_orb_id = nil
}

// SetPublishedAt sets the "published_at" field.
func (m *PublishedReportMutation) SetPublishedAt(t time.Time) {
	m.published_at = &t
}

// PublishedAt returns the value of the "published_at" field in the mutation.
func (m *PublishedReportMutation) PublishedAt() (r time.Time, exists bool) {
	v := m.published_at
	if v == nil {
		return
	}
	return *v, true
}

// OldPublishedAt returns the old "published_at" field's value of the PublishedReport entity.
// If the PublishedReport object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PublishedReportMutation) OldPublishedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublishedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublishedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublishedAt: %w", err)
	}
	return oldValue.PublishedAt, nil
}

// ResetPublishedAt resets all changes to the "published_at" field.
func (m *PublishedReportMutation) ResetPublishedAt() {
	m.published_at = nil
}

// SetS3Key sets the "s3_key" field.
func (m *PublishedReportMutation) SetS3Key(s string) {
	m.s3_key = &s
}

// S3Key returns the value of the "s3_key" field in the mutation.
func (m *PublishedReportMutation) S3Key() (r string, exists bool) {
	v := m.s3_key
	if v == nil {
		return
	}
	return *v, true
}

// OldS3Key returns the old "s3_key" field's value of the PublishedReport entity.
// If the PublishedReport object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PublishedReportMutation) OldS3Key(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldS3Key is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldS3Key requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldS3Key: %w", err)
	}
	return oldValue.S3Key, nil
}

// ResetS3Key resets all changes to the "s3_key" field.
func (m *PublishedReportMutation) ResetS3Key() {
	m.s3_key = nil
}

// SetS3Endpoint sets the "s3_endpoint" field.
func (m *PublishedReportMutation) SetS3Endpoint(s string) {
	m.s3_endpoint = &s
}

// S3Endpoint returns the value of the "s3_endpoint" field in the mutation.
func (m *PublishedReportMutation) S3Endpoint() (r string, exists bool) {
	v := m.s3_endpoint
	if v == nil {
		return
	}
	return *v, true
}

// OldS3Endpoint returns the old "s3_endpoint" field's value of the PublishedReport entity.
// If the PublishedReport object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PublishedReportMutation) OldS3Endpoint(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldS3Endpoint is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldS3Endpoint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldS3Endpoint: %w", err)
	}
	return oldValue.S3Endpoint, nil
}

// ClearS3Endpoint clears the value of the "s3_endpoint" field.
func (m *PublishedReportMutation) ClearS3Endpoint() {
	m.s3_endpoint = nil
	m.clearedFields[publishedreport.FieldS3Endpoint] = struct{}{}
}

// S3EndpointCleared returns if the "s3_endpoint" field was cleared in this mutation.
func (m *PublishedReportMutation) S3EndpointCleared() bool {
	_, ok := m.clearedFields[publishedreport.FieldS3Endpoint]
	return ok
}

// ResetS3Endpoint resets all changes to the "s3_endpoint" field.
func (m *PublishedReportMutation) ResetS3Endpoint() {
	m.s3_endpoint = nil
	delete(m.clearedFields, publishedreport.FieldS3Endpoint)
}

// SetEntryCount sets the "entry_count" field.
func (m *PublishedReportMutation) SetEntryCount(i int) {
	m.entry_count = &i
	m.addentry_count = nil
}

// EntryCount returns the value of the "entry_count" field in the mutation.
func (m *PublishedReportMutation) EntryCount() (r int, exists bool) {
	v := m.entry_count
	if v == nil {
		return
	}
	return *v, true
}

// OldEntryCount returns the old "entry_count" field's value of the PublishedReport entity.
// If the PublishedReport object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PublishedReportMutation) OldEntryCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEntryCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEntryCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEntryCount: %w", err)
	}
	return oldValue.EntryCount, nil
}

// AddEntryCount adds i to the "entry_count" field.
func (m *PublishedReportMutation) AddEntryCount(i int) {
	if m.addentry_count != nil {
		*m.addentry_count += i
	} else {
		m.addentry_count = &i
	}
}

// AddedEntryCount returns the value that was added to the "entry_count" field in this mutation.
func (m *PublishedReportMutation) AddedEntryCount() (r int, exists bool) {
	v := m.addentry_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetEntryCount resets all changes to the "entry_count" field.
func (m *PublishedReportMutation) ResetEntryCount() {
	m.entry_count = nil
	m.addentry_count = nil
}

// SetStatus sets the "status" field.
func (m *PublishedReportMutation) SetStatus(pu publishedreport.Status) {
	m.status = &pu
}

// Status returns the value of the "status" field in the mutation.
func (m *PublishedReportMutation) Status() (r publishedreport.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the PublishedReport entity.
// If the PublishedReport object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PublishedReportMutation) OldStatus(ctx context.Context) (v publishedreport.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *PublishedReportMutation) ResetStatus() {
	m.status = nil
}

// SetSummaryJSON sets the "summary_json" field.
func (m *PublishedReportMutation) SetSummaryJSON(s string) {
	m.summary_json = &s
}

// SummaryJSON returns the value of the "summary_json" field in the mutation.
func (m *PublishedReportMutation) SummaryJSON() (r string, exists bool) {
	v := m.summary_json
	if v == nil {
		return
	}
	return *v, true
}

// OldSummaryJSON returns the old "summary_json" field's value of the PublishedReport entity.
// If the PublishedReport object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PublishedReportMutation) OldSummaryJSON(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSummaryJSON is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSummaryJSON requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSummaryJSON: %w", err)
	}
	return oldValue.SummaryJSON, nil
}

// ClearSummaryJSON clears the value of the "summary_json" field.
func (m *PublishedReportMutation) ClearSummaryJSON() {
	m.summary_json = nil
	m.clearedFields[publishedreport.FieldSummaryJSON] = struct{}{}
}

// SummaryJSONCleared returns if the "summary_json" field was cleared in this mutation.
func (m *PublishedReportMutation) SummaryJSONCleared() bool {
	_, ok := m.clearedFields[publishedreport.FieldSummaryJSON]
	return ok
}

// ResetSummaryJSON resets all changes to the "summary_json" field.
func (m *PublishedReportMutation) ResetSummaryJSON() {
	m.summary_json = nil
	delete(m.clearedFields, publishedreport.FieldSummaryJSON)
}

// Where appends a list predicates to the PublishedReportMutation builder.
func (m *PublishedReportMutation) Where(ps ...predicate.PublishedReport) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PublishedReportMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PublishedReportMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PublishedReport, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PublishedReportMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PublishedReportMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PublishedReport).
func (m *PublishedReportMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PublishedReportMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.dc_orb_id != nil {
		fields = append(fields, publishedreport.FieldDcOrbID)
	}
	if m.published_at != nil {
		fields = append(fields, publishedreport.FieldPublishedAt)
	}
	if m.s3_key != nil {
		fields = append(fields, publishedreport.FieldS3Key)
	}
	if m.s3_endpoint != nil {
		fields = append(fields, publishedreport.FieldS3Endpoint)
	}
	if m.entry_count != nil {
		fields = append(fields, publishedreport.FieldEntryCount)
	}
	if m.status != nil {
		fields = append(fields, publishedreport.FieldStatus)
	}
	if m.summary_json != nil {
		fields = append(fields, publishedreport.FieldSummaryJSON)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PublishedReportMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case publishedreport.FieldDcOrbID:
		return m.DcOrbID()
	case publishedreport.FieldPublishedAt:
		return m.PublishedAt()
	case publishedreport.FieldS3Key:
		return m.S3Key()
	case publishedreport.FieldS3Endpoint:
		return m.S3Endpoint()
	case publishedreport.FieldEntryCount:
		return m.EntryCount()
	case publishedreport.FieldStatus:
		return m.Status()
	case publishedreport.FieldSummaryJSON:
		return m.SummaryJSON()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PublishedReportMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case publishedreport.FieldDcOrbID:
		return m.OldDcOrbID(ctx)
	case publishedreport.FieldPublishedAt:
		return m.OldPublishedAt(ctx)
	case publishedreport.FieldS3Key:
		return m.OldS3Key(ctx)
	case publishedreport.FieldS3Endpoint:
		return m.OldS3Endpoint(ctx)
	case publishedreport.FieldEntryCount:
		return m.OldEntryCount(ctx)
	case publishedreport.FieldStatus:
		return m.OldStatus(ctx)
	case publishedreport.FieldSummaryJSON:
		return m.OldSummaryJSON(ctx)
	}
	return nil, fmt.Errorf("unknown PublishedReport field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PublishedReportMutation) SetField(name string, value ent.Value) error {
	switch name {
	case publishedreport.FieldDcOrbID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDcOrbID(v)
		return nil
	case publishedreport.FieldPublishedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublishedAt(v)
		return nil
	case publishedreport.FieldS3Key:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetS3Key(v)
		return nil
	case publishedreport.FieldS3Endpoint:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetS3Endpoint(v)
		return nil
	case publishedreport.FieldEntryCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEntryCount(v)
		return nil
	case publishedreport.FieldStatus:
		v, ok := value.(publishedreport.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case publishedreport.FieldSummaryJSON:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSummaryJSON(v)
		return nil
	}
	return fmt.Errorf("unknown PublishedReport field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PublishedReportMutation) AddedFields() []string {
	var fields []string
	if m.addentry_count != nil {
		fields = append(fields, publishedreport.FieldEntryCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PublishedReportMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case publishedreport.FieldEntryCount:
		return m.AddedEntryCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PublishedReportMutation) AddField(name string, value ent.Value) error {
	switch name {
	case publishedreport.FieldEntryCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddEntryCount(v)
		return nil
	}
	return fmt.Errorf("unknown PublishedReport numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PublishedReportMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(publishedreport.FieldS3Endpoint) {
		fields = append(fields, publishedreport.FieldS3Endpoint)
	}
	if m.FieldCleared(publishedreport.FieldSummaryJSON) {
		fields = append(fields, publishedreport.FieldSummaryJSON)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PublishedReportMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PublishedReportMutation) ClearField(name string) error {
	switch name {
	case publishedreport.FieldS3Endpoint:
		m.ClearS3Endpoint()
		return nil
	case publishedreport.FieldSummaryJSON:
		m.ClearSummaryJSON()
		return nil
	}
	return fmt.Errorf("unknown PublishedReport nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PublishedReportMutation) ResetField(name string) error {
	switch name {
	case publishedreport.FieldDcOrbID:
		m.ResetDcOrbID()
		return nil
	case publishedreport.FieldPublishedAt:
		m.ResetPublishedAt()
		return nil
	case publishedreport.FieldS3Key:
		m.ResetS3Key()
		return nil
	case publishedreport.FieldS3Endpoint:
		m.ResetS3Endpoint()
		return nil
	case publishedreport.FieldEntryCount:
		m.ResetEntryCount()
		return nil
	case publishedreport.FieldStatus:
		m.ResetStatus()
		return nil
	case publishedreport.FieldSummaryJSON:
		m.ResetSummaryJSON()
		return nil
	}
	return fmt.Errorf("unknown PublishedReport field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PublishedReportMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PublishedReportMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PublishedReportMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PublishedReportMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PublishedReportMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PublishedReportMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PublishedReportMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PublishedReport unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PublishedReportMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PublishedReport edge %s", name)
}
