apiVersion: v1
kind: Secret
metadata:
  name: orbital-secrets
  namespace: netbox
type: Opaque
stringData:
  DATABASE_URL: "postgres://orbital:orbital@orbital-postgres:5432/orbital?sslmode=disable"
  ORBITAL_SESSION_HMAC_KEY: "c4499bc5229f999b136912663c4550a36f93d45983c529069d9471cfb027bdf2"
  ORBITAL_SESSION_ENCRYPTION_KEY: "0mkyFiskKtwkhAMpx68OFvLgdCni54q9"
  ORBITAL_OIDC_CLIENT_SECRET: "5D.8Q~nu3ssTejLcvAmOz1rR6PQ6hVMurQB1Act_"
  ORBITAL_OIDC_REDIRECT_URL: "http://localhost:8001/auth/callback"
  ORBITAL_S3_SECRET_KEY: "IsPAJSeS7BzD5xnnbAF+KUoIHQ2iLf/NLXr768N99I9w+O2NLtassnFZZdXbeYsw9rRQRag2Eehn+AStm/dC/g=="
  ORBITAL_OCI_PASSWORD: "rBKjnsBK0I1E+U+SZ2ROxgEKilR4ZjmGzT4sxd/1HD+ACRCxP3ni"
  cosign.key: |
    -----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----
    eyJrZGYiOnsibmFtZSI6InNjcnlwdCIsInBhcmFtcyI6eyJOIjo2NTUzNiwiciI6
    OCwicCI6MX0sInNhbHQiOiIzVnZqQXdoWEFtakNNS25TS3N6ck5aa2ZlN3FUMmNu
    anVMOEpnT0hDUmNVPSJ9LCJjaXBoZXIiOnsibmFtZSI6Im5hY2wvc2VjcmV0Ym94
    Iiwibm9uY2UiOiJEalB5RXZmQ0xwa0NzY1psbVBibmdNV2dYdkJKaW1jSSJ9LCJj
    aXBoZXJ0ZXh0IjoiZTJYamo3UHFwY3hVQXVWVjk2U2FkZ0FwSFI1WWtwa3ZVVWd0
    c2h2OE5UREFtRTBJTXpseWdGUzV5L1o4bTdvZ1E1OER4UGQrbklYNUtEOHpCa3Q1
    SmhXb0lwazlJUFhidC9xS2RldVZmYms3VTA5aXQ5R2lPbDgyRjg2SUlBUTdYRUZJ
    V1J2dTFQbEZJeWFOYjJYRHhCeDJpQ1N1eTZWY1E2SzBpanBDT0hWMEpsaXZlYzVn
    eDVsbTVtVnhINTFtM0dNblFBY2dTTk5iV1E9PSJ9
    -----END ENCRYPTED SIGSTORE PRIVATE KEY-----
