// Code generated by ent, DO NOT EDIT.

package approvalpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the approvalpolicy type in the database.
	Label = "approval_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldActionType holds the string denoting the action_type field in the database.
	FieldActionType = "action_type"
	// FieldAllNamespaces holds the string denoting the all_namespaces field in the database.
	FieldAllNamespaces = "all_namespaces"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldAllTypes holds the string denoting the all_types field in the database.
	FieldAllTypes = "all_types"
	// FieldTypes holds the string denoting the types field in the database.
	FieldTypes = "types"
	// FieldRequiredApprovals holds the string denoting the required_approvals field in the database.
	FieldRequiredApprovals = "required_approvals"
	// FieldBypassRoles holds the string denoting the bypass_roles field in the database.
	FieldBypassRoles = "bypass_roles"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// Table holds the table name of the approvalpolicy in the database.
	Table = "approval_policies"
)

// Columns holds all SQL columns for approvalpolicy fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCreatedBy,
	FieldUpdatedAt,
	FieldUpdatedBy,
	FieldActionType,
	FieldAllNamespaces,
	FieldNamespace,
	FieldAllTypes,
	FieldTypes,
	FieldRequiredApprovals,
	FieldBypassRoles,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// ActionTypeValidator is a validator for the "action_type" field. It is called by the builders before save.
	ActionTypeValidator func(string) error
	// DefaultAllNamespaces holds the default value on creation for the "all_namespaces" field.
	DefaultAllNamespaces bool
	// DefaultAllTypes holds the default value on creation for the "all_types" field.
	DefaultAllTypes bool
	// DefaultRequiredApprovals holds the default value on creation for the "required_approvals" field.
	DefaultRequiredApprovals int
	// RequiredApprovalsValidator is a validator for the "required_approvals" field. It is called by the builders before save.
	RequiredApprovalsValidator func(int) error
	// DefaultBypassRoles holds the default value on creation for the "bypass_roles" field.
	DefaultBypassRoles []string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ApprovalPolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByActionType orders the results by the action_type field.
func ByActionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionType, opts...).ToFunc()
}

// ByAllNamespaces orders the results by the all_namespaces field.
func ByAllNamespaces(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllNamespaces, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByAllTypes orders the results by the all_types field.
func ByAllTypes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllTypes, opts...).ToFunc()
}

// ByRequiredApprovals orders the results by the required_approvals field.
func ByRequiredApprovals(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiredApprovals, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
