services:
  dgraph-zero:
    image: dgraph/dgraph:v25.3.1
    command: dgraph zero --my=dgraph-zero:5080
    ports:
      - "5080:5080"
      - "6080:6080"

  dgraph-alpha:
    image: dgraph/dgraph:v25.3.1
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080 --graphql extensions=false
    ports:
      - "7080:7080"
      - "8080:8080"
      - "9080:9080"
    depends_on:
      - dgraph-zero

  dgraph-ratel:
    image: dgraph/ratel:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      - dgraph-alpha

  postgres:
    image: postgres:18.3-alpine3.23 
    environment:
      POSTGRES_USER: orbital
      POSTGRES_PASSWORD: orbital
      POSTGRES_DB: orbital
    ports:
      - "5432:5432"
