// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApprovalsColumns holds the columns for the "approvals" table.
	ApprovalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "approver", Type: field.TypeString},
		{Name: "decision", Type: field.TypeEnum, Enums: []string{"approved", "rejected"}},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "approved_at_hash", Type: field.TypeString},
		{Name: "approval_request_id", Type: field.TypeInt64},
	}
	// ApprovalsTable holds the schema information for the "approvals" table.
	ApprovalsTable = &schema.Table{
		Name:       "approvals",
		Columns:    ApprovalsColumns,
		PrimaryKey: []*schema.Column{ApprovalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "approvals_approval_requests_approvals",
				Columns:    []*schema.Column{ApprovalsColumns[9]},
				RefColumns: []*schema.Column{ApprovalRequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "approval_approval_request_id_approver",
				Unique:  true,
				Columns: []*schema.Column{ApprovalsColumns[9], ApprovalsColumns[5]},
			},
		},
	}
	// ApprovalPoliciesColumns holds the columns for the "approval_policies" table.
	ApprovalPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "action_type", Type: field.TypeString},
		{Name: "all_namespaces", Type: field.TypeBool, Default: false},
		{Name: "namespace", Type: field.TypeString, Nullable: true},
		{Name: "all_types", Type: field.TypeBool, Default: true},
		{Name: "types", Type: field.TypeJSON, Nullable: true},
		{Name: "required_approvals", Type: field.TypeInt, Default: 1},
		{Name: "bypass_roles", Type: field.TypeJSON},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// ApprovalPoliciesTable holds the schema information for the "approval_policies" table.
	ApprovalPoliciesTable = &schema.Table{
		Name:       "approval_policies",
		Columns:    ApprovalPoliciesColumns,
		PrimaryKey: []*schema.Column{ApprovalPoliciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "approvalpolicy_action_type_namespace",
				Unique:  true,
				Columns: []*schema.Column{ApprovalPoliciesColumns[5], ApprovalPoliciesColumns[7]},
			},
			{
				Name:    "approvalpolicy_action_type",
				Unique:  true,
				Columns: []*schema.Column{ApprovalPoliciesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Where: "all_namespaces",
				},
			},
		},
	}
	// ApprovalRequestsColumns holds the columns for the "approval_requests" table.
	ApprovalRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "namespace", Type: field.TypeString},
		{Name: "number", Type: field.TypeInt},
		{Name: "action_type", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"open", "rejected", "merged", "closed"}, Default: "open"},
		{Name: "author", Type: field.TypeString},
		{Name: "base_hash", Type: field.TypeString},
		{Name: "base_present", Type: field.TypeJSON, Nullable: true},
		{Name: "base_effect", Type: field.TypeJSON, Nullable: true},
		{Name: "base_values", Type: field.TypeJSON, Nullable: true},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "executed_at", Type: field.TypeTime, Nullable: true},
		{Name: "executed_by", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// ApprovalRequestsTable holds the schema information for the "approval_requests" table.
	ApprovalRequestsTable = &schema.Table{
		Name:       "approval_requests",
		Columns:    ApprovalRequestsColumns,
		PrimaryKey: []*schema.Column{ApprovalRequestsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "approvalrequest_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{ApprovalRequestsColumns[10], ApprovalRequestsColumns[1]},
			},
			{
				Name:    "approvalrequest_author",
				Unique:  false,
				Columns: []*schema.Column{ApprovalRequestsColumns[11]},
			},
			{
				Name:    "approvalrequest_action_type",
				Unique:  false,
				Columns: []*schema.Column{ApprovalRequestsColumns[7]},
			},
			{
				Name:    "approvalrequest_namespace_number",
				Unique:  true,
				Columns: []*schema.Column{ApprovalRequestsColumns[5], ApprovalRequestsColumns[6]},
			},
			{
				Name:    "approvalrequest_payload",
				Unique:  false,
				Columns: []*schema.Column{ApprovalRequestsColumns[16]},
				Annotation: &entsql.IndexAnnotation{
					Types: map[string]string{
						"postgres": "GIN",
					},
				},
			},
		},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "operations", Type: field.TypeJSON, Nullable: true},
		{Name: "actor", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "details", Type: field.TypeJSON, Nullable: true},
		{Name: "event_category", Type: field.TypeString, Default: "data"},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[3]},
			},
		},
	}
	// AuditEventResourcesColumns holds the columns for the "audit_event_resources" table.
	AuditEventResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "orb_id", Type: field.TypeString},
		{Name: "audit_event_id", Type: field.TypeUUID},
	}
	// AuditEventResourcesTable holds the schema information for the "audit_event_resources" table.
	AuditEventResourcesTable = &schema.Table{
		Name:       "audit_event_resources",
		Columns:    AuditEventResourcesColumns,
		PrimaryKey: []*schema.Column{AuditEventResourcesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_event_resources_audit_events_resources",
				Columns:    []*schema.Column{AuditEventResourcesColumns[2]},
				RefColumns: []*schema.Column{AuditEventsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "auditeventresource_orb_id",
				Unique:  false,
				Columns: []*schema.Column{AuditEventResourcesColumns[1]},
			},
			{
				Name:    "auditeventresource_audit_event_id_orb_id",
				Unique:  true,
				Columns: []*schema.Column{AuditEventResourcesColumns[2], AuditEventResourcesColumns[1]},
			},
		},
	}
	// AuditEventResourceTypesColumns holds the columns for the "audit_event_resource_types" table.
	AuditEventResourceTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "audit_event_id", Type: field.TypeUUID},
	}
	// AuditEventResourceTypesTable holds the schema information for the "audit_event_resource_types" table.
	AuditEventResourceTypesTable = &schema.Table{
		Name:       "audit_event_resource_types",
		Columns:    AuditEventResourceTypesColumns,
		PrimaryKey: []*schema.Column{AuditEventResourceTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_event_resource_types_audit_events_resource_types",
				Columns:    []*schema.Column{AuditEventResourceTypesColumns[2]},
				RefColumns: []*schema.Column{AuditEventsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "auditeventresourcetype_resource_type",
				Unique:  false,
				Columns: []*schema.Column{AuditEventResourceTypesColumns[1]},
			},
			{
				Name:    "auditeventresourcetype_audit_event_id_resource_type",
				Unique:  true,
				Columns: []*schema.Column{AuditEventResourceTypesColumns[2], AuditEventResourceTypesColumns[1]},
			},
		},
	}
	// BackupsColumns holds the columns for the "backups" table.
	BackupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "skipped", "failed"}},
		{Name: "trigger", Type: field.TypeEnum, Enums: []string{"manual", "scheduled"}, Default: "manual"},
		{Name: "s3_bucket", Type: field.TypeString, Nullable: true},
		{Name: "s3_key", Type: field.TypeString, Nullable: true},
		{Name: "s3_endpoint", Type: field.TypeString, Nullable: true},
		{Name: "checksum", Type: field.TypeString, Nullable: true},
		{Name: "schema_version", Type: field.TypeString, Nullable: true},
		{Name: "binary_version", Type: field.TypeString, Nullable: true},
		{Name: "size_bytes", Type: field.TypeInt64, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// BackupsTable holds the schema information for the "backups" table.
	BackupsTable = &schema.Table{
		Name:       "backups",
		Columns:    BackupsColumns,
		PrimaryKey: []*schema.Column{BackupsColumns[0]},
	}
	// DivergenceEntriesColumns holds the columns for the "divergence_entries" table.
	DivergenceEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "dc_orb_id", Type: field.TypeString},
		{Name: "entry_orb_id", Type: field.TypeString},
		{Name: "field", Type: field.TypeString},
		{Name: "type_name", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "intended_value", Type: field.TypeJSON, Nullable: true},
		{Name: "override_value", Type: field.TypeJSON, Nullable: true},
		{Name: "who", Type: field.TypeString},
		{Name: "first_seen_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "last_report_published_at", Type: field.TypeTime},
	}
	// DivergenceEntriesTable holds the schema information for the "divergence_entries" table.
	DivergenceEntriesTable = &schema.Table{
		Name:       "divergence_entries",
		Columns:    DivergenceEntriesColumns,
		PrimaryKey: []*schema.Column{DivergenceEntriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "divergenceentry_dc_orb_id_entry_orb_id_field",
				Unique:  true,
				Columns: []*schema.Column{DivergenceEntriesColumns[5], DivergenceEntriesColumns[6], DivergenceEntriesColumns[7]},
			},
			{
				Name:    "divergenceentry_dc_orb_id_last_seen_at",
				Unique:  false,
				Columns: []*schema.Column{DivergenceEntriesColumns[5], DivergenceEntriesColumns[13]},
			},
		},
	}
	// DivergenceIngestCursorsColumns holds the columns for the "divergence_ingest_cursors" table.
	DivergenceIngestCursorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "dc_orb_id", Type: field.TypeString, Unique: true},
		{Name: "last_published_at", Type: field.TypeTime},
	}
	// DivergenceIngestCursorsTable holds the schema information for the "divergence_ingest_cursors" table.
	DivergenceIngestCursorsTable = &schema.Table{
		Name:       "divergence_ingest_cursors",
		Columns:    DivergenceIngestCursorsColumns,
		PrimaryKey: []*schema.Column{DivergenceIngestCursorsColumns[0]},
	}
	// DivergenceResolutionsColumns holds the columns for the "divergence_resolutions" table.
	DivergenceResolutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "entry_orb_id", Type: field.TypeString},
		{Name: "field", Type: field.TypeString},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"accept", "reject", "ignore"}},
		{Name: "actor", Type: field.TypeString},
		{Name: "decided_at", Type: field.TypeTime},
	}
	// DivergenceResolutionsTable holds the schema information for the "divergence_resolutions" table.
	DivergenceResolutionsTable = &schema.Table{
		Name:       "divergence_resolutions",
		Columns:    DivergenceResolutionsColumns,
		PrimaryKey: []*schema.Column{DivergenceResolutionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "divergenceresolution_entry_orb_id_field",
				Unique:  true,
				Columns: []*schema.Column{DivergenceResolutionsColumns[5], DivergenceResolutionsColumns[6]},
			},
		},
	}
	// ExportJobsColumns holds the columns for the "export_jobs" table.
	ExportJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "datacenter_id", Type: field.TypeString},
		{Name: "datacenter_name", Type: field.TypeString},
		{Name: "datacenter_orb_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed", "stale"}},
		{Name: "artifact_path", Type: field.TypeString, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// ExportJobsTable holds the schema information for the "export_jobs" table.
	ExportJobsTable = &schema.Table{
		Name:       "export_jobs",
		Columns:    ExportJobsColumns,
		PrimaryKey: []*schema.Column{ExportJobsColumns[0]},
	}
	// MergeAttemptsColumns holds the columns for the "merge_attempts" table.
	MergeAttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "attempted_by", Type: field.TypeString},
		{Name: "attempted_at", Type: field.TypeTime},
		{Name: "results", Type: field.TypeJSON, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "approval_request_id", Type: field.TypeInt64},
	}
	// MergeAttemptsTable holds the schema information for the "merge_attempts" table.
	MergeAttemptsTable = &schema.Table{
		Name:       "merge_attempts",
		Columns:    MergeAttemptsColumns,
		PrimaryKey: []*schema.Column{MergeAttemptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "merge_attempts_approval_requests_merge_attempts",
				Columns:    []*schema.Column{MergeAttemptsColumns[9]},
				RefColumns: []*schema.Column{ApprovalRequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mergeattempt_approval_request_id_attempted_at",
				Unique:  false,
				Columns: []*schema.Column{MergeAttemptsColumns[9], MergeAttemptsColumns[6]},
			},
		},
	}
	// OrbsColumns holds the columns for the "orbs" table.
	OrbsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "datacenter_id", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "revoked"}, Default: "active"},
	}
	// OrbsTable holds the schema information for the "orbs" table.
	OrbsTable = &schema.Table{
		Name:       "orbs",
		Columns:    OrbsColumns,
		PrimaryKey: []*schema.Column{OrbsColumns[0]},
	}
	// RegistryArtifactsColumns holds the columns for the "registry_artifacts" table.
	RegistryArtifactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "datacenter_id", Type: field.TypeString},
		{Name: "datacenter_name", Type: field.TypeString, Default: ""},
		{Name: "registry", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "tag", Type: field.TypeString},
		{Name: "digest", Type: field.TypeString, Nullable: true},
		{Name: "size_bytes", Type: field.TypeInt64, Nullable: true},
		{Name: "signed", Type: field.TypeBool, Default: false},
		{Name: "signing_key_fingerprint", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "bundling", "pushing", "signing", "completed", "failed"}},
		{Name: "initiated_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "enriched", Type: field.TypeBool, Default: false},
		{Name: "bundler_error", Type: field.TypeString, Nullable: true},
		{Name: "layers", Type: field.TypeJSON, Nullable: true},
		{Name: "export_job_id", Type: field.TypeUUID},
	}
	// RegistryArtifactsTable holds the schema information for the "registry_artifacts" table.
	RegistryArtifactsTable = &schema.Table{
		Name:       "registry_artifacts",
		Columns:    RegistryArtifactsColumns,
		PrimaryKey: []*schema.Column{RegistryArtifactsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "registry_artifacts_export_jobs_registry_artifacts",
				Columns:    []*schema.Column{RegistryArtifactsColumns[17]},
				RefColumns: []*schema.Column{ExportJobsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RestoreJobsColumns holds the columns for the "restore_jobs" table.
	RestoreJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed"}},
		{Name: "backup_id", Type: field.TypeUUID, Nullable: true},
		{Name: "backup_key", Type: field.TypeString, Nullable: true},
		{Name: "log", Type: field.TypeString, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// RestoreJobsTable holds the schema information for the "restore_jobs" table.
	RestoreJobsTable = &schema.Table{
		Name:       "restore_jobs",
		Columns:    RestoreJobsColumns,
		PrimaryKey: []*schema.Column{RestoreJobsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "preferred_username", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"readonly", "dev", "admin"}, Default: "readonly"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApprovalsTable,
		ApprovalPoliciesTable,
		ApprovalRequestsTable,
		AuditEventsTable,
		AuditEventResourcesTable,
		AuditEventResourceTypesTable,
		BackupsTable,
		DivergenceEntriesTable,
		DivergenceIngestCursorsTable,
		DivergenceResolutionsTable,
		ExportJobsTable,
		MergeAttemptsTable,
		OrbsTable,
		RegistryArtifactsTable,
		RestoreJobsTable,
		UsersTable,
	}
)

func init() {
	ApprovalsTable.ForeignKeys[0].RefTable = ApprovalRequestsTable
	ApprovalPoliciesTable.Annotation = &entsql.Annotation{}
	ApprovalPoliciesTable.Annotation.Checks = map[string]string{
		"approval_policy_namespace_exclusive": "(all_namespaces AND (namespace IS NULL OR namespace = '')) OR ((NOT all_namespaces) AND namespace IS NOT NULL AND namespace <> '')",
		"approval_policy_scope_exclusive":     "(all_types AND (jsonb_typeof(types) <> 'array' OR jsonb_array_length(types) = 0)) OR ((NOT all_types) AND jsonb_typeof(types) = 'array' AND jsonb_array_length(types) > 0)",
	}
	AuditEventResourcesTable.ForeignKeys[0].RefTable = AuditEventsTable
	AuditEventResourceTypesTable.ForeignKeys[0].RefTable = AuditEventsTable
	MergeAttemptsTable.ForeignKeys[0].RefTable = ApprovalRequestsTable
	RegistryArtifactsTable.ForeignKeys[0].RefTable = ExportJobsTable
}
