// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BackupsColumns holds the columns for the "backups" table.
	BackupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "bucket", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "in_progress", "completed", "failed"}},
		{Name: "dgraph_instance", Type: field.TypeString, Nullable: true},
		{Name: "checksum", Type: field.TypeString, Nullable: true},
		{Name: "schema_version", Type: field.TypeString, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "size_bytes", Type: field.TypeInt64, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// BackupsTable holds the schema information for the "backups" table.
	BackupsTable = &schema.Table{
		Name:       "backups",
		Columns:    BackupsColumns,
		PrimaryKey: []*schema.Column{BackupsColumns[0]},
	}
	// ExportJobsColumns holds the columns for the "export_jobs" table.
	ExportJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "datacenter_id", Type: field.TypeString},
		{Name: "datacenter_name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed"}},
		{Name: "artifact_path", Type: field.TypeString, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// ExportJobsTable holds the schema information for the "export_jobs" table.
	ExportJobsTable = &schema.Table{
		Name:       "export_jobs",
		Columns:    ExportJobsColumns,
		PrimaryKey: []*schema.Column{ExportJobsColumns[0]},
	}
	// NamespacesColumns holds the columns for the "namespaces" table.
	NamespacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "dgraph_id", Type: field.TypeString, Nullable: true},
	}
	// NamespacesTable holds the schema information for the "namespaces" table.
	NamespacesTable = &schema.Table{
		Name:       "namespaces",
		Columns:    NamespacesColumns,
		PrimaryKey: []*schema.Column{NamespacesColumns[0]},
	}
	// OrbsColumns holds the columns for the "orbs" table.
	OrbsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "datacenter_id", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "revoked"}, Default: "active"},
	}
	// OrbsTable holds the schema information for the "orbs" table.
	OrbsTable = &schema.Table{
		Name:       "orbs",
		Columns:    OrbsColumns,
		PrimaryKey: []*schema.Column{OrbsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "preferred_username", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BackupsTable,
		ExportJobsTable,
		NamespacesTable,
		OrbsTable,
		UsersTable,
	}
)

func init() {
}
