apiVersion: v1
kind: Pod
metadata:
  name: dgraph-live
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: orbital
          topologyKey: kubernetes.io/hostname
          namespaces:
            - orbital
