mutation UpsertIdracSettings {
  addIdracSettings(input: [
    {
      orbId: "2f-uae:5HSC3D4-idrac"
      version: 1
      name: "idrac"
      namespace: "2f-uae"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "2f-uae:5HSC3D4" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "2f-uae:6MLN3D4-idrac"
      version: 1
      name: "idrac"
      namespace: "2f-uae"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "2f-uae:6MLN3D4" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "2f-uae:9MLN3D4-idrac"
      version: 1
      name: "idrac"
      namespace: "2f-uae"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "2f-uae:9MLN3D4" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "2f-uae:7MLN3D4-idrac"
      version: 1
      name: "idrac"
      namespace: "2f-uae"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "2f-uae:7MLN3D4" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "2f-uae:3MLN3D4-idrac"
      version: 1
      name: "idrac"
      namespace: "2f-uae"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "2f-uae:3MLN3D4" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "2f-uae:2MLN3D4-idrac"
      version: 1
      name: "idrac"
      namespace: "2f-uae"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "2f-uae:2MLN3D4" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
  ], upsert: true) {
    numUids
  }
}
