mutation UpsertIdracSettings {
  addIdracSettings(input: [
    {
      orbId: "grayling:505CK74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-505CK74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:B5WVM34-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-B5WVM34" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:JY69K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-JY69K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:BLP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-BLP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:CLP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-CLP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:8LP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-8LP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:3LP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-3LP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:9LP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-9LP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:6LP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-6LP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:7LP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-7LP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:5LP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-5LP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:4LP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-4LP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "grayling:D5MP6K74-idrac"
      version: 1
      name: "idrac"
      namespace: "grayling"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "grayling:server-D5MP6K74" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
  ], upsert: true) {
    numUids
  }
}
