mutation UpsertIdracSettings {
  addIdracSettings(input: [
    {
      orbId: "houston:6PJ1FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-6PJ1FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:9B52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-9B52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:BB52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-BB52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:DB52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-DB52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:6B52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-6B52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:8B52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-8B52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:J922FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-J922FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:J452FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-J452FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:1B22FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-1B22FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:2B22FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-2B22FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:4B22FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-4B22FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:53RKHZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-53RKHZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:7PJ1FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-7PJ1FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:4PJ1FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-4PJ1FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:3B52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-3B52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:CB52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-CB52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:7B52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-7B52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:FB52FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-FB52FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:1552FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-1552FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:6B22FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-6B22FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:3B22FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-3B22FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:7B22FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-7B22FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:5B22FZ3-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-5B22FZ3" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:F9J1X54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-F9J1X54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:D9J1X54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-D9J1X54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:H9J1X54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-H9J1X54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:G9J1X54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-G9J1X54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:C9J1X54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-C9J1X54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:8N4VW54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-8N4VW54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:9N4VW54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-9N4VW54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:CN4VW54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-CN4VW54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:BN4VW54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-BN4VW54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
    {
      orbId: "houston:J9J1X54-idrac"
      version: 1
      name: "idrac"
      namespace: "houston"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-15T00:00:00Z"
      server: { orbId: "houston:server-J9J1X54" version: 1 }
      firmwareVersion: "7.20.10.05"
      sshEnabled: false
      ipmiEnabled: false
      lockdownModeEnabled: false
      osToIdracPassThroughEnabled: false
      usbManagementPortEnabled: true
      dhcpEnabled: false
      racadmEnabled: true
    }
  ], upsert: true) {
    numUids
  }
}
