mutation {
  addNamespace(input: { name: "seattle" }, upsert: true) {
    numUids
  }

  addDataCenter(input: [
    {
      name: "seattle-galleon"
      orbId: "seattle:seattle-galleon"
      version: 1
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      assetDataV2: "{\"072a5bf6-459d-405f-93b4-667509ead0c2\":{\"kvmURL\":\"https://kubevirt.colo.armada.ai/vmlist\",\"cfTunnelID\":\"\"},\"44a8c40e-6a4a-48bf-acaa-45706b1e1e77\":{\"kvmURL\":\"https://kubevirt.colo.armada.ai/vmlist\",\"cfTunnelID\":\"\"},\"bdf378a1-0e73-4088-9889-0000e1531948\":{\"kvmURL\":\"https://kubevirt-dg.armada.ai/vmlist\",\"cfTunnelID\":\"5571f458-6d95-4e66-81c3-ba8baf50dbe7\",\"metricsAPIURL\":\"https://metrics-api-dg-seattle.armadaapps.io\"}}"
    }
  ], upsert: true) {
    numUids
  }

  addRack(input: [
    {
      name: "Rack-1"
      orbId: "seattle:Rack-1"
      version: 1
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
    }
    {
      name: "Rack-2"
      orbId: "seattle:Rack-2"
      version: 1
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
    }
    {
      name: "Rack-3"
      orbId: "seattle:Rack-3"
      version: 1
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
    }
    {
      name: "Rack-4"
      orbId: "seattle:Rack-4"
      version: 1
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
    }
    {
      name: "Rack-5"
      orbId: "seattle:Rack-5"
      version: 1
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
    }
  ], upsert: true) {
    numUids
  }

  addIPAddress(input: [
    {
      orbId: "seattle:10.20.43.7"
      version: 1
      address: "10.20.43.7"
      name: "10.20.43.7"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.43.4"
      version: 1
      address: "10.20.43.4"
      name: "10.20.43.4"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.49"
      version: 1
      address: "10.20.33.49"
      name: "10.20.33.49"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.51"
      version: 1
      address: "10.20.33.51"
      name: "10.20.33.51"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.52"
      version: 1
      address: "10.20.33.52"
      name: "10.20.33.52"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.80"
      version: 1
      address: "10.20.33.80"
      name: "10.20.33.80"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-06-18T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.81"
      version: 1
      address: "10.20.33.81"
      name: "10.20.33.81"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-06-18T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.53"
      version: 1
      address: "10.20.33.53"
      name: "10.20.33.53"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.54"
      version: 1
      address: "10.20.33.54"
      name: "10.20.33.54"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.43.2"
      version: 1
      address: "10.20.43.2"
      name: "10.20.43.2"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.43.3"
      version: 1
      address: "10.20.43.3"
      name: "10.20.43.3"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.61"
      version: 1
      address: "10.20.33.61"
      name: "10.20.33.61"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.62"
      version: 1
      address: "10.20.33.62"
      name: "10.20.33.62"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.63"
      version: 1
      address: "10.20.33.63"
      name: "10.20.33.63"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.64"
      version: 1
      address: "10.20.33.64"
      name: "10.20.33.64"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.65"
      version: 1
      address: "10.20.33.65"
      name: "10.20.33.65"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.66"
      version: 1
      address: "10.20.33.66"
      name: "10.20.33.66"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.67"
      version: 1
      address: "10.20.33.67"
      name: "10.20.33.67"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.68"
      version: 1
      address: "10.20.33.68"
      name: "10.20.33.68"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.33.69"
      version: 1
      address: "10.20.33.69"
      name: "10.20.33.69"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.43.5"
      version: 1
      address: "10.20.43.5"
      name: "10.20.43.5"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.96.87.15"
      version: 1
      address: "10.96.87.15"
      name: "10.96.87.15"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.43.6"
      version: 1
      address: "10.20.43.6"
      name: "10.20.43.6"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.96.87.17"
      version: 1
      address: "10.96.87.17"
      name: "10.96.87.17"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.96.87.16"
      version: 1
      address: "10.96.87.16"
      name: "10.96.87.16"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    },
    {
      orbId: "seattle:10.20.43.8"
      version: 1
      address: "10.20.43.8"
      name: "10.20.43.8"
      role: "oob"
      namespace: "seattle"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
    }
  ], upsert: true) {
    numUids
  }

  addServer(input: [
    {
      serviceTag: "65WVM34"
      manufacturer: "Dell"
      orbId: "seattle:server-65WVM34"
      version: 1
      name: "r05-u03.seattle-galleon"
      hostname: "r05-u03.seattle-galleon"
      model: "PowerEdge XE8640"
      rackPosition: 3
      oobIP: { orbId: "seattle:10.20.43.7" version: 1 }
      oobMAC: "c4:cb:e1:ba:37:84"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "95WVM34"
      manufacturer: "Dell"
      orbId: "seattle:server-95WVM34"
      version: 1
      name: "r05-u07.seattle-galleon"
      hostname: "r05-u07.seattle-galleon"
      model: "PowerEdge XE8640"
      rackPosition: 7
      oobIP: { orbId: "seattle:10.20.43.4" version: 1 }
      oobMAC: "c4:cb:e1:ba:37:5a"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "JD268Y3"
      manufacturer: "Dell"
      orbId: "seattle:server-JD268Y3"
      version: 1
      model: "PowerEdge R350"
      oobIP: { orbId: "seattle:10.20.33.49" version: 1 }
      oobMAC: "c4:5a:b1:ac:62:36"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "FZ7P7Y3"
      manufacturer: "Dell"
      orbId: "seattle:server-FZ7P7Y3"
      version: 1
      model: "PowerEdge R750"
      oobIP: { orbId: "seattle:10.20.33.51" version: 1 }
      oobMAC: "c8:4b:d6:a0:66:60"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "5L4P7Y3"
      manufacturer: "Dell"
      orbId: "seattle:server-5L4P7Y3"
      version: 1
      model: "PowerEdge R650"
      oobIP: { orbId: "seattle:10.20.33.52" version: 1 }
      oobMAC: "c8:4b:d6:9f:8e:2a"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "6L4P7Y3"
      manufacturer: "Dell"
      orbId: "seattle:server-6L4P7Y3"
      version: 1
      model: "PowerEdge R650"
      oobIP: { orbId: "seattle:10.20.33.53" version: 1 }
      oobMAC: "c8:4b:d6:9f:81:be"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "7L4P7Y3"
      manufacturer: "Dell"
      orbId: "seattle:server-7L4P7Y3"
      version: 1
      model: "PowerEdge R650"
      oobIP: { orbId: "seattle:10.20.33.54" version: 1 }
      oobMAC: "c8:4b:d6:9f:81:ac"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "GMP6K74"
      manufacturer: "Dell"
      orbId: "seattle:server-GMP6K74"
      version: 1
      model: "PowerEdge R450"
      oobIP: { orbId: "seattle:10.20.43.2" version: 1 }
      oobMAC: "d0:c1:b5:0c:b1:d8"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "JMP6K74"
      manufacturer: "Dell"
      orbId: "seattle:server-JMP6K74"
      version: 1
      model: "PowerEdge R450"
      oobIP: { orbId: "seattle:10.20.43.3" version: 1 }
      oobMAC: "d0:c1:b5:0c:b1:c0"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "HVZ8Z44"
      manufacturer: "Dell"
      orbId: "seattle:server-HVZ8Z44"
      version: 1
      name: "r04-u13.seattle-galleon"
      hostname: "r04-u13.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 13
      oobIP: { orbId: "seattle:10.20.33.61" version: 1 }
      oobMAC: "a8:3c:a5:42:42:f2"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "3WZ8Z44"
      manufacturer: "Dell"
      orbId: "seattle:server-3WZ8Z44"
      version: 1
      name: "r04-u14.seattle-galleon"
      hostname: "r04-u14.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 14
      oobIP: { orbId: "seattle:10.20.33.62" version: 1 }
      oobMAC: "a8:3c:a5:43:f5:98"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "2WZ8Z44"
      manufacturer: "Dell"
      orbId: "seattle:server-2WZ8Z44"
      version: 1
      name: "r04-u15.seattle-galleon"
      hostname: "r04-u15.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 15
      oobIP: { orbId: "seattle:10.20.33.63" version: 1 }
      oobMAC: "a8:3c:a5:43:e9:56"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "1WZ8Z44"
      manufacturer: "Dell"
      orbId: "seattle:server-1WZ8Z44"
      version: 1
      name: "r04-u16.seattle-galleon"
      hostname: "r04-u16.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 16
      oobIP: { orbId: "seattle:10.20.33.64" version: 1 }
      oobMAC: "a8:3c:a5:43:e9:6e"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "4WZ8Z44"
      manufacturer: "Dell"
      orbId: "seattle:server-4WZ8Z44"
      version: 1
      name: "r04-u17.seattle-galleon"
      hostname: "r04-u17.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 17
      oobIP: { orbId: "seattle:10.20.33.65" version: 1 }
      oobMAC: "a8:3c:a5:40:dd:07"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "JVZ8Z44"
      manufacturer: "Dell"
      orbId: "seattle:server-JVZ8Z44"
      version: 1
      name: "r04-u18.seattle-galleon"
      hostname: "r04-u18.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 18
      oobIP: { orbId: "seattle:10.20.33.66" version: 1 }
      oobMAC: "a8:3c:a5:40:c5:07"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "7FS1L44"
      manufacturer: "Dell"
      orbId: "seattle:server-7FS1L44"
      version: 1
      name: "r04-u21.seattle-galleon"
      hostname: "r04-u21.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 21
      oobIP: { orbId: "seattle:10.20.33.67" version: 1 }
      oobMAC: "a8:3c:a5:43:f2:50"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "BDP1L44"
      manufacturer: "Dell"
      orbId: "seattle:server-BDP1L44"
      version: 1
      name: "r04-u22.seattle-galleon"
      hostname: "r04-u22.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 22
      oobIP: { orbId: "seattle:10.20.33.68" version: 1 }
      oobMAC: "a8:3c:a5:43:f4:54"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "9DP1L44"
      manufacturer: "Dell"
      orbId: "seattle:server-9DP1L44"
      version: 1
      name: "r04-u23.seattle-galleon"
      hostname: "r04-u23.seattle-galleon"
      model: "PowerEdge AX650"
      rackPosition: 23
      oobIP: { orbId: "seattle:10.20.33.69" version: 1 }
      oobMAC: "a8:3c:a5:43:f4:fc"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
    {
      serviceTag: "97WVM34"
      manufacturer: "Dell"
      orbId: "seattle:server-97WVM34"
      version: 1
      name: "r03-u01.seattle-galleon"
      hostname: "r03-u01.seattle-galleon"
      model: "PowerEdge XE8640"
      rackPosition: 1
      oobIP: { orbId: "seattle:10.20.43.5" version: 1 }
      oobMAC: "c4:cb:e1:b6:45:48"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-3" version: 1 }
    }
    {
      serviceTag: "DLP6K74"
      manufacturer: "Dell"
      orbId: "seattle:server-DLP6K74"
      version: 1
      name: "r02-u21.seattle-galleon"
      hostname: "r02-u21.seattle-galleon"
      model: "PowerEdge R450"
      rackPosition: 21
      oobIP: { orbId: "seattle:10.96.87.15" version: 1 }
      oobMAC: "e8:cf:83:27:a5:73"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-2" version: 1 }
    }
    {
      serviceTag: "75WVM34"
      manufacturer: "Dell"
      orbId: "seattle:server-75WVM34"
      version: 1
      name: "r03-u05.seattle-galleon"
      hostname: "r03-u05.seattle-galleon"
      model: "PowerEdge XE8640"
      rackPosition: 5
      oobIP: { orbId: "seattle:10.20.43.6" version: 1 }
      oobMAC: "c4:cb:e1:ba:3a:90"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-3" version: 1 }
    }
    {
      serviceTag: "GLP6K74"
      manufacturer: "Dell"
      orbId: "seattle:server-GLP6K74"
      version: 1
      name: "r01-u15.seattle-galleon"
      hostname: "r01-u15.seattle-galleon"
      model: "PowerEdge R450"
      rackPosition: 15
      oobIP: { orbId: "seattle:10.96.87.17" version: 1 }
      oobMAC: "e8:cf:83:27:b2:9b"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-1" version: 1 }
    }
    {
      serviceTag: "HLP6K74"
      manufacturer: "Dell"
      orbId: "seattle:server-HLP6K74"
      version: 1
      model: "PowerEdge R450"
      oobIP: { orbId: "seattle:10.20.33.80" version: 1 }
      oobMAC: "e8:cf:83:27:aa:2b"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "D4MP6K74"
      manufacturer: "Dell"
      orbId: "seattle:server-D4MP6K74"
      version: 1
      model: "PowerEdge R450"
      oobIP: { orbId: "seattle:10.20.33.81" version: 1 }
      oobMAC: "d0:c1:b5:0c:bb:70"
      createdBy: "admin@armada.ai"
      createdAt: "2026-06-18T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-5" version: 1 }
    }
    {
      serviceTag: "42TD3H4"
      manufacturer: "Dell"
      orbId: "seattle:server-42TD3H4"
      version: 1
      name: "r04-u03.seattle-galleon"
      hostname: "r04-u03.seattle-galleon"
      model: "PowerEdge XE7745"
      rackPosition: 3
      oobIP: { orbId: "seattle:10.20.43.8" version: 1 }
      oobMAC: "6c:3c:8c:93:bd:72"
      createdBy: "admin@armada.ai"
      createdAt: "2026-05-11T00:00:00Z"
      namespace: "seattle"
      dataCenter: { orbId: "seattle:seattle-galleon" version: 1 }
      rack: { orbId: "seattle:Rack-4" version: 1 }
    }
  ], upsert: true) {
    numUids
  }
}
