// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/approval"
	"github.com/armada/orbital/ent/approvalrequest"
	"github.com/armada/orbital/ent/mergeattempt"
	"github.com/armada/orbital/ent/predicate"
	"github.com/google/uuid"
)

// ApprovalRequestUpdate is the builder for updating ApprovalRequest entities.
type ApprovalRequestUpdate struct {
	config
	hooks    []Hook
	mutation *ApprovalRequestMutation
}

// Where appends a list predicates to the ApprovalRequestUpdate builder.
func (_u *ApprovalRequestUpdate) Where(ps ...predicate.ApprovalRequest) *ApprovalRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApprovalRequestUpdate) SetCreatedBy(v string) *ApprovalRequestUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableCreatedBy(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApprovalRequestUpdate) ClearCreatedBy() *ApprovalRequestUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApprovalRequestUpdate) SetUpdatedAt(v time.Time) *ApprovalRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableUpdatedAt(v *time.Time) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ApprovalRequestUpdate) ClearUpdatedAt() *ApprovalRequestUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ApprovalRequestUpdate) SetUpdatedBy(v string) *ApprovalRequestUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableUpdatedBy(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ApprovalRequestUpdate) ClearUpdatedBy() *ApprovalRequestUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *ApprovalRequestUpdate) SetActionType(v string) *ApprovalRequestUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableActionType(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ApprovalRequestUpdate) SetTitle(v string) *ApprovalRequestUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableTitle(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApprovalRequestUpdate) SetDescription(v string) *ApprovalRequestUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableDescription(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApprovalRequestUpdate) ClearDescription() *ApprovalRequestUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApprovalRequestUpdate) SetStatus(v approvalrequest.Status) *ApprovalRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableStatus(v *approvalrequest.Status) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ApprovalRequestUpdate) SetAuthor(v string) *ApprovalRequestUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableAuthor(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetBaseHash sets the "base_hash" field.
func (_u *ApprovalRequestUpdate) SetBaseHash(v string) *ApprovalRequestUpdate {
	_u.mutation.SetBaseHash(v)
	return _u
}

// SetNillableBaseHash sets the "base_hash" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableBaseHash(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetBaseHash(*v)
	}
	return _u
}

// SetBasePresent sets the "base_present" field.
func (_u *ApprovalRequestUpdate) SetBasePresent(v []string) *ApprovalRequestUpdate {
	_u.mutation.SetBasePresent(v)
	return _u
}

// AppendBasePresent appends value to the "base_present" field.
func (_u *ApprovalRequestUpdate) AppendBasePresent(v []string) *ApprovalRequestUpdate {
	_u.mutation.AppendBasePresent(v)
	return _u
}

// ClearBasePresent clears the value of the "base_present" field.
func (_u *ApprovalRequestUpdate) ClearBasePresent() *ApprovalRequestUpdate {
	_u.mutation.ClearBasePresent()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ApprovalRequestUpdate) SetPayload(v json.RawMessage) *ApprovalRequestUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *ApprovalRequestUpdate) AppendPayload(v json.RawMessage) *ApprovalRequestUpdate {
	_u.mutation.AppendPayload(v)
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *ApprovalRequestUpdate) SetExecutedAt(v time.Time) *ApprovalRequestUpdate {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableExecutedAt(v *time.Time) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *ApprovalRequestUpdate) ClearExecutedAt() *ApprovalRequestUpdate {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetExecutedBy sets the "executed_by" field.
func (_u *ApprovalRequestUpdate) SetExecutedBy(v string) *ApprovalRequestUpdate {
	_u.mutation.SetExecutedBy(v)
	return _u
}

// SetNillableExecutedBy sets the "executed_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdate) SetNillableExecutedBy(v *string) *ApprovalRequestUpdate {
	if v != nil {
		_u.SetExecutedBy(*v)
	}
	return _u
}

// ClearExecutedBy clears the value of the "executed_by" field.
func (_u *ApprovalRequestUpdate) ClearExecutedBy() *ApprovalRequestUpdate {
	_u.mutation.ClearExecutedBy()
	return _u
}

// AddApprovalIDs adds the "approvals" edge to the Approval entity by IDs.
func (_u *ApprovalRequestUpdate) AddApprovalIDs(ids ...uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.AddApprovalIDs(ids...)
	return _u
}

// AddApprovals adds the "approvals" edges to the Approval entity.
func (_u *ApprovalRequestUpdate) AddApprovals(v ...*Approval) *ApprovalRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApprovalIDs(ids...)
}

// AddMergeAttemptIDs adds the "merge_attempts" edge to the MergeAttempt entity by IDs.
func (_u *ApprovalRequestUpdate) AddMergeAttemptIDs(ids ...uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.AddMergeAttemptIDs(ids...)
	return _u
}

// AddMergeAttempts adds the "merge_attempts" edges to the MergeAttempt entity.
func (_u *ApprovalRequestUpdate) AddMergeAttempts(v ...*MergeAttempt) *ApprovalRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMergeAttemptIDs(ids...)
}

// Mutation returns the ApprovalRequestMutation object of the builder.
func (_u *ApprovalRequestUpdate) Mutation() *ApprovalRequestMutation {
	return _u.mutation
}

// ClearApprovals clears all "approvals" edges to the Approval entity.
func (_u *ApprovalRequestUpdate) ClearApprovals() *ApprovalRequestUpdate {
	_u.mutation.ClearApprovals()
	return _u
}

// RemoveApprovalIDs removes the "approvals" edge to Approval entities by IDs.
func (_u *ApprovalRequestUpdate) RemoveApprovalIDs(ids ...uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.RemoveApprovalIDs(ids...)
	return _u
}

// RemoveApprovals removes "approvals" edges to Approval entities.
func (_u *ApprovalRequestUpdate) RemoveApprovals(v ...*Approval) *ApprovalRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApprovalIDs(ids...)
}

// ClearMergeAttempts clears all "merge_attempts" edges to the MergeAttempt entity.
func (_u *ApprovalRequestUpdate) ClearMergeAttempts() *ApprovalRequestUpdate {
	_u.mutation.ClearMergeAttempts()
	return _u
}

// RemoveMergeAttemptIDs removes the "merge_attempts" edge to MergeAttempt entities by IDs.
func (_u *ApprovalRequestUpdate) RemoveMergeAttemptIDs(ids ...uuid.UUID) *ApprovalRequestUpdate {
	_u.mutation.RemoveMergeAttemptIDs(ids...)
	return _u
}

// RemoveMergeAttempts removes "merge_attempts" edges to MergeAttempt entities.
func (_u *ApprovalRequestUpdate) RemoveMergeAttempts(v ...*MergeAttempt) *ApprovalRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMergeAttemptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApprovalRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApprovalRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApprovalRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApprovalRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApprovalRequestUpdate) check() error {
	if v, ok := _u.mutation.ActionType(); ok {
		if err := approvalrequest.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := approvalrequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := approvalrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := approvalrequest.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseHash(); ok {
		if err := approvalrequest.BaseHashValidator(v); err != nil {
			return &ValidationError{Name: "base_hash", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.base_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ApprovalRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(approvalrequest.Table, approvalrequest.Columns, sqlgraph.NewFieldSpec(approvalrequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(approvalrequest.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(approvalrequest.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(approvalrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(approvalrequest.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(approvalrequest.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(approvalrequest.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(approvalrequest.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(approvalrequest.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(approvalrequest.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(approvalrequest.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(approvalrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(approvalrequest.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseHash(); ok {
		_spec.SetField(approvalrequest.FieldBaseHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.BasePresent(); ok {
		_spec.SetField(approvalrequest.FieldBasePresent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBasePresent(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalrequest.FieldBasePresent, value)
		})
	}
	if _u.mutation.BasePresentCleared() {
		_spec.ClearField(approvalrequest.FieldBasePresent, field.TypeJSON)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(approvalrequest.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalrequest.FieldPayload, value)
		})
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(approvalrequest.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(approvalrequest.FieldExecutedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExecutedBy(); ok {
		_spec.SetField(approvalrequest.FieldExecutedBy, field.TypeString, value)
	}
	if _u.mutation.ExecutedByCleared() {
		_spec.ClearField(approvalrequest.FieldExecutedBy, field.TypeString)
	}
	if _u.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.ApprovalsTable,
			Columns: []string{approvalrequest.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApprovalsIDs(); len(nodes) > 0 && !_u.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.ApprovalsTable,
			Columns: []string{approvalrequest.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApprovalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.ApprovalsTable,
			Columns: []string{approvalrequest.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MergeAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.MergeAttemptsTable,
			Columns: []string{approvalrequest.MergeAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mergeattempt.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMergeAttemptsIDs(); len(nodes) > 0 && !_u.mutation.MergeAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.MergeAttemptsTable,
			Columns: []string{approvalrequest.MergeAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mergeattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MergeAttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.MergeAttemptsTable,
			Columns: []string{approvalrequest.MergeAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mergeattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{approvalrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApprovalRequestUpdateOne is the builder for updating a single ApprovalRequest entity.
type ApprovalRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApprovalRequestMutation
}

// SetCreatedBy sets the "created_by" field.
func (_u *ApprovalRequestUpdateOne) SetCreatedBy(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableCreatedBy(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ApprovalRequestUpdateOne) ClearCreatedBy() *ApprovalRequestUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApprovalRequestUpdateOne) SetUpdatedAt(v time.Time) *ApprovalRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableUpdatedAt(v *time.Time) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ApprovalRequestUpdateOne) ClearUpdatedAt() *ApprovalRequestUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ApprovalRequestUpdateOne) SetUpdatedBy(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableUpdatedBy(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ApprovalRequestUpdateOne) ClearUpdatedBy() *ApprovalRequestUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *ApprovalRequestUpdateOne) SetActionType(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableActionType(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ApprovalRequestUpdateOne) SetTitle(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableTitle(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApprovalRequestUpdateOne) SetDescription(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableDescription(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ApprovalRequestUpdateOne) ClearDescription() *ApprovalRequestUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApprovalRequestUpdateOne) SetStatus(v approvalrequest.Status) *ApprovalRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableStatus(v *approvalrequest.Status) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ApprovalRequestUpdateOne) SetAuthor(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableAuthor(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetBaseHash sets the "base_hash" field.
func (_u *ApprovalRequestUpdateOne) SetBaseHash(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetBaseHash(v)
	return _u
}

// SetNillableBaseHash sets the "base_hash" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableBaseHash(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetBaseHash(*v)
	}
	return _u
}

// SetBasePresent sets the "base_present" field.
func (_u *ApprovalRequestUpdateOne) SetBasePresent(v []string) *ApprovalRequestUpdateOne {
	_u.mutation.SetBasePresent(v)
	return _u
}

// AppendBasePresent appends value to the "base_present" field.
func (_u *ApprovalRequestUpdateOne) AppendBasePresent(v []string) *ApprovalRequestUpdateOne {
	_u.mutation.AppendBasePresent(v)
	return _u
}

// ClearBasePresent clears the value of the "base_present" field.
func (_u *ApprovalRequestUpdateOne) ClearBasePresent() *ApprovalRequestUpdateOne {
	_u.mutation.ClearBasePresent()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ApprovalRequestUpdateOne) SetPayload(v json.RawMessage) *ApprovalRequestUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// AppendPayload appends value to the "payload" field.
func (_u *ApprovalRequestUpdateOne) AppendPayload(v json.RawMessage) *ApprovalRequestUpdateOne {
	_u.mutation.AppendPayload(v)
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *ApprovalRequestUpdateOne) SetExecutedAt(v time.Time) *ApprovalRequestUpdateOne {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableExecutedAt(v *time.Time) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *ApprovalRequestUpdateOne) ClearExecutedAt() *ApprovalRequestUpdateOne {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetExecutedBy sets the "executed_by" field.
func (_u *ApprovalRequestUpdateOne) SetExecutedBy(v string) *ApprovalRequestUpdateOne {
	_u.mutation.SetExecutedBy(v)
	return _u
}

// SetNillableExecutedBy sets the "executed_by" field if the given value is not nil.
func (_u *ApprovalRequestUpdateOne) SetNillableExecutedBy(v *string) *ApprovalRequestUpdateOne {
	if v != nil {
		_u.SetExecutedBy(*v)
	}
	return _u
}

// ClearExecutedBy clears the value of the "executed_by" field.
func (_u *ApprovalRequestUpdateOne) ClearExecutedBy() *ApprovalRequestUpdateOne {
	_u.mutation.ClearExecutedBy()
	return _u
}

// AddApprovalIDs adds the "approvals" edge to the Approval entity by IDs.
func (_u *ApprovalRequestUpdateOne) AddApprovalIDs(ids ...uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.AddApprovalIDs(ids...)
	return _u
}

// AddApprovals adds the "approvals" edges to the Approval entity.
func (_u *ApprovalRequestUpdateOne) AddApprovals(v ...*Approval) *ApprovalRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApprovalIDs(ids...)
}

// AddMergeAttemptIDs adds the "merge_attempts" edge to the MergeAttempt entity by IDs.
func (_u *ApprovalRequestUpdateOne) AddMergeAttemptIDs(ids ...uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.AddMergeAttemptIDs(ids...)
	return _u
}

// AddMergeAttempts adds the "merge_attempts" edges to the MergeAttempt entity.
func (_u *ApprovalRequestUpdateOne) AddMergeAttempts(v ...*MergeAttempt) *ApprovalRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMergeAttemptIDs(ids...)
}

// Mutation returns the ApprovalRequestMutation object of the builder.
func (_u *ApprovalRequestUpdateOne) Mutation() *ApprovalRequestMutation {
	return _u.mutation
}

// ClearApprovals clears all "approvals" edges to the Approval entity.
func (_u *ApprovalRequestUpdateOne) ClearApprovals() *ApprovalRequestUpdateOne {
	_u.mutation.ClearApprovals()
	return _u
}

// RemoveApprovalIDs removes the "approvals" edge to Approval entities by IDs.
func (_u *ApprovalRequestUpdateOne) RemoveApprovalIDs(ids ...uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.RemoveApprovalIDs(ids...)
	return _u
}

// RemoveApprovals removes "approvals" edges to Approval entities.
func (_u *ApprovalRequestUpdateOne) RemoveApprovals(v ...*Approval) *ApprovalRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApprovalIDs(ids...)
}

// ClearMergeAttempts clears all "merge_attempts" edges to the MergeAttempt entity.
func (_u *ApprovalRequestUpdateOne) ClearMergeAttempts() *ApprovalRequestUpdateOne {
	_u.mutation.ClearMergeAttempts()
	return _u
}

// RemoveMergeAttemptIDs removes the "merge_attempts" edge to MergeAttempt entities by IDs.
func (_u *ApprovalRequestUpdateOne) RemoveMergeAttemptIDs(ids ...uuid.UUID) *ApprovalRequestUpdateOne {
	_u.mutation.RemoveMergeAttemptIDs(ids...)
	return _u
}

// RemoveMergeAttempts removes "merge_attempts" edges to MergeAttempt entities.
func (_u *ApprovalRequestUpdateOne) RemoveMergeAttempts(v ...*MergeAttempt) *ApprovalRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMergeAttemptIDs(ids...)
}

// Where appends a list predicates to the ApprovalRequestUpdate builder.
func (_u *ApprovalRequestUpdateOne) Where(ps ...predicate.ApprovalRequest) *ApprovalRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApprovalRequestUpdateOne) Select(field string, fields ...string) *ApprovalRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApprovalRequest entity.
func (_u *ApprovalRequestUpdateOne) Save(ctx context.Context) (*ApprovalRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApprovalRequestUpdateOne) SaveX(ctx context.Context) *ApprovalRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApprovalRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApprovalRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApprovalRequestUpdateOne) check() error {
	if v, ok := _u.mutation.ActionType(); ok {
		if err := approvalrequest.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := approvalrequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := approvalrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := approvalrequest.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseHash(); ok {
		if err := approvalrequest.BaseHashValidator(v); err != nil {
			return &ValidationError{Name: "base_hash", err: fmt.Errorf(`ent: validator failed for field "ApprovalRequest.base_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ApprovalRequestUpdateOne) sqlSave(ctx context.Context) (_node *ApprovalRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(approvalrequest.Table, approvalrequest.Columns, sqlgraph.NewFieldSpec(approvalrequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApprovalRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, approvalrequest.FieldID)
		for _, f := range fields {
			if !approvalrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != approvalrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(approvalrequest.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(approvalrequest.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(approvalrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(approvalrequest.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(approvalrequest.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(approvalrequest.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(approvalrequest.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(approvalrequest.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(approvalrequest.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(approvalrequest.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(approvalrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(approvalrequest.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseHash(); ok {
		_spec.SetField(approvalrequest.FieldBaseHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.BasePresent(); ok {
		_spec.SetField(approvalrequest.FieldBasePresent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBasePresent(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalrequest.FieldBasePresent, value)
		})
	}
	if _u.mutation.BasePresentCleared() {
		_spec.ClearField(approvalrequest.FieldBasePresent, field.TypeJSON)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(approvalrequest.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, approvalrequest.FieldPayload, value)
		})
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(approvalrequest.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(approvalrequest.FieldExecutedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExecutedBy(); ok {
		_spec.SetField(approvalrequest.FieldExecutedBy, field.TypeString, value)
	}
	if _u.mutation.ExecutedByCleared() {
		_spec.ClearField(approvalrequest.FieldExecutedBy, field.TypeString)
	}
	if _u.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.ApprovalsTable,
			Columns: []string{approvalrequest.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApprovalsIDs(); len(nodes) > 0 && !_u.mutation.ApprovalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.ApprovalsTable,
			Columns: []string{approvalrequest.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApprovalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.ApprovalsTable,
			Columns: []string{approvalrequest.ApprovalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approval.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MergeAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.MergeAttemptsTable,
			Columns: []string{approvalrequest.MergeAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mergeattempt.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMergeAttemptsIDs(); len(nodes) > 0 && !_u.mutation.MergeAttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.MergeAttemptsTable,
			Columns: []string{approvalrequest.MergeAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mergeattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MergeAttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   approvalrequest.MergeAttemptsTable,
			Columns: []string{approvalrequest.MergeAttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mergeattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApprovalRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{approvalrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
