// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/approvalpolicy"
	"github.com/google/uuid"
)

// ApprovalPolicyCreate is the builder for creating a ApprovalPolicy entity.
type ApprovalPolicyCreate struct {
	config
	mutation *ApprovalPolicyMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApprovalPolicyCreate) SetCreatedAt(v time.Time) *ApprovalPolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableCreatedAt(v *time.Time) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ApprovalPolicyCreate) SetCreatedBy(v string) *ApprovalPolicyCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableCreatedBy(v *string) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApprovalPolicyCreate) SetUpdatedAt(v time.Time) *ApprovalPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableUpdatedAt(v *time.Time) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ApprovalPolicyCreate) SetUpdatedBy(v string) *ApprovalPolicyCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableUpdatedBy(v *string) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetActionType sets the "action_type" field.
func (_c *ApprovalPolicyCreate) SetActionType(v string) *ApprovalPolicyCreate {
	_c.mutation.SetActionType(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *ApprovalPolicyCreate) SetNamespace(v string) *ApprovalPolicyCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetTypeName sets the "type_name" field.
func (_c *ApprovalPolicyCreate) SetTypeName(v string) *ApprovalPolicyCreate {
	_c.mutation.SetTypeName(v)
	return _c
}

// SetNillableTypeName sets the "type_name" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableTypeName(v *string) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetTypeName(*v)
	}
	return _c
}

// SetRequiredApprovals sets the "required_approvals" field.
func (_c *ApprovalPolicyCreate) SetRequiredApprovals(v int) *ApprovalPolicyCreate {
	_c.mutation.SetRequiredApprovals(v)
	return _c
}

// SetNillableRequiredApprovals sets the "required_approvals" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableRequiredApprovals(v *int) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetRequiredApprovals(*v)
	}
	return _c
}

// SetBypassRoles sets the "bypass_roles" field.
func (_c *ApprovalPolicyCreate) SetBypassRoles(v []string) *ApprovalPolicyCreate {
	_c.mutation.SetBypassRoles(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ApprovalPolicyCreate) SetEnabled(v bool) *ApprovalPolicyCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableEnabled(v *bool) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ApprovalPolicyCreate) SetID(v uuid.UUID) *ApprovalPolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ApprovalPolicyCreate) SetNillableID(v *uuid.UUID) *ApprovalPolicyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ApprovalPolicyMutation object of the builder.
func (_c *ApprovalPolicyCreate) Mutation() *ApprovalPolicyMutation {
	return _c.mutation
}

// Save creates the ApprovalPolicy in the database.
func (_c *ApprovalPolicyCreate) Save(ctx context.Context) (*ApprovalPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApprovalPolicyCreate) SaveX(ctx context.Context) *ApprovalPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApprovalPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApprovalPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApprovalPolicyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := approvalpolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.TypeName(); !ok {
		v := approvalpolicy.DefaultTypeName
		_c.mutation.SetTypeName(v)
	}
	if _, ok := _c.mutation.RequiredApprovals(); !ok {
		v := approvalpolicy.DefaultRequiredApprovals
		_c.mutation.SetRequiredApprovals(v)
	}
	if _, ok := _c.mutation.BypassRoles(); !ok {
		v := approvalpolicy.DefaultBypassRoles
		_c.mutation.SetBypassRoles(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := approvalpolicy.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := approvalpolicy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApprovalPolicyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ApprovalPolicy.created_at"`)}
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		return &ValidationError{Name: "action_type", err: errors.New(`ent: missing required field "ApprovalPolicy.action_type"`)}
	}
	if v, ok := _c.mutation.ActionType(); ok {
		if err := approvalpolicy.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ApprovalPolicy.action_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "ApprovalPolicy.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := approvalpolicy.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "ApprovalPolicy.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequiredApprovals(); !ok {
		return &ValidationError{Name: "required_approvals", err: errors.New(`ent: missing required field "ApprovalPolicy.required_approvals"`)}
	}
	if v, ok := _c.mutation.RequiredApprovals(); ok {
		if err := approvalpolicy.RequiredApprovalsValidator(v); err != nil {
			return &ValidationError{Name: "required_approvals", err: fmt.Errorf(`ent: validator failed for field "ApprovalPolicy.required_approvals": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BypassRoles(); !ok {
		return &ValidationError{Name: "bypass_roles", err: errors.New(`ent: missing required field "ApprovalPolicy.bypass_roles"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ApprovalPolicy.enabled"`)}
	}
	return nil
}

func (_c *ApprovalPolicyCreate) sqlSave(ctx context.Context) (*ApprovalPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApprovalPolicyCreate) createSpec() (*ApprovalPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &ApprovalPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(approvalpolicy.Table, sqlgraph.NewFieldSpec(approvalpolicy.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(approvalpolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(approvalpolicy.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(approvalpolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(approvalpolicy.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.ActionType(); ok {
		_spec.SetField(approvalpolicy.FieldActionType, field.TypeString, value)
		_node.ActionType = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(approvalpolicy.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.TypeName(); ok {
		_spec.SetField(approvalpolicy.FieldTypeName, field.TypeString, value)
		_node.TypeName = value
	}
	if value, ok := _c.mutation.RequiredApprovals(); ok {
		_spec.SetField(approvalpolicy.FieldRequiredApprovals, field.TypeInt, value)
		_node.RequiredApprovals = value
	}
	if value, ok := _c.mutation.BypassRoles(); ok {
		_spec.SetField(approvalpolicy.FieldBypassRoles, field.TypeJSON, value)
		_node.BypassRoles = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(approvalpolicy.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// ApprovalPolicyCreateBulk is the builder for creating many ApprovalPolicy entities in bulk.
type ApprovalPolicyCreateBulk struct {
	config
	err      error
	builders []*ApprovalPolicyCreate
}

// Save creates the ApprovalPolicy entities in the database.
func (_c *ApprovalPolicyCreateBulk) Save(ctx context.Context) ([]*ApprovalPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ApprovalPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApprovalPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApprovalPolicyCreateBulk) SaveX(ctx context.Context) []*ApprovalPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApprovalPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApprovalPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
