// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/auditevent"
	"github.com/armada/orbital/ent/auditeventresourcetype"
	"github.com/armada/orbital/ent/predicate"
	"github.com/google/uuid"
)

// AuditEventResourceTypeUpdate is the builder for updating AuditEventResourceType entities.
type AuditEventResourceTypeUpdate struct {
	config
	hooks    []Hook
	mutation *AuditEventResourceTypeMutation
}

// Where appends a list predicates to the AuditEventResourceTypeUpdate builder.
func (_u *AuditEventResourceTypeUpdate) Where(ps ...predicate.AuditEventResourceType) *AuditEventResourceTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAuditEventID sets the "audit_event_id" field.
func (_u *AuditEventResourceTypeUpdate) SetAuditEventID(v uuid.UUID) *AuditEventResourceTypeUpdate {
	_u.mutation.SetAuditEventID(v)
	return _u
}

// SetNillableAuditEventID sets the "audit_event_id" field if the given value is not nil.
func (_u *AuditEventResourceTypeUpdate) SetNillableAuditEventID(v *uuid.UUID) *AuditEventResourceTypeUpdate {
	if v != nil {
		_u.SetAuditEventID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditEventResourceTypeUpdate) SetResourceType(v string) *AuditEventResourceTypeUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditEventResourceTypeUpdate) SetNillableResourceType(v *string) *AuditEventResourceTypeUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetAuditEvent sets the "audit_event" edge to the AuditEvent entity.
func (_u *AuditEventResourceTypeUpdate) SetAuditEvent(v *AuditEvent) *AuditEventResourceTypeUpdate {
	return _u.SetAuditEventID(v.ID)
}

// Mutation returns the AuditEventResourceTypeMutation object of the builder.
func (_u *AuditEventResourceTypeUpdate) Mutation() *AuditEventResourceTypeMutation {
	return _u.mutation
}

// ClearAuditEvent clears the "audit_event" edge to the AuditEvent entity.
func (_u *AuditEventResourceTypeUpdate) ClearAuditEvent() *AuditEventResourceTypeUpdate {
	_u.mutation.ClearAuditEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditEventResourceTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventResourceTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditEventResourceTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventResourceTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditEventResourceTypeUpdate) check() error {
	if _u.mutation.AuditEventCleared() && len(_u.mutation.AuditEventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditEventResourceType.audit_event"`)
	}
	return nil
}

func (_u *AuditEventResourceTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditeventresourcetype.Table, auditeventresourcetype.Columns, sqlgraph.NewFieldSpec(auditeventresourcetype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditeventresourcetype.FieldResourceType, field.TypeString, value)
	}
	if _u.mutation.AuditEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditeventresourcetype.AuditEventTable,
			Columns: []string{auditeventresourcetype.AuditEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditeventresourcetype.AuditEventTable,
			Columns: []string{auditeventresourcetype.AuditEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditeventresourcetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditEventResourceTypeUpdateOne is the builder for updating a single AuditEventResourceType entity.
type AuditEventResourceTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditEventResourceTypeMutation
}

// SetAuditEventID sets the "audit_event_id" field.
func (_u *AuditEventResourceTypeUpdateOne) SetAuditEventID(v uuid.UUID) *AuditEventResourceTypeUpdateOne {
	_u.mutation.SetAuditEventID(v)
	return _u
}

// SetNillableAuditEventID sets the "audit_event_id" field if the given value is not nil.
func (_u *AuditEventResourceTypeUpdateOne) SetNillableAuditEventID(v *uuid.UUID) *AuditEventResourceTypeUpdateOne {
	if v != nil {
		_u.SetAuditEventID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditEventResourceTypeUpdateOne) SetResourceType(v string) *AuditEventResourceTypeUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditEventResourceTypeUpdateOne) SetNillableResourceType(v *string) *AuditEventResourceTypeUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetAuditEvent sets the "audit_event" edge to the AuditEvent entity.
func (_u *AuditEventResourceTypeUpdateOne) SetAuditEvent(v *AuditEvent) *AuditEventResourceTypeUpdateOne {
	return _u.SetAuditEventID(v.ID)
}

// Mutation returns the AuditEventResourceTypeMutation object of the builder.
func (_u *AuditEventResourceTypeUpdateOne) Mutation() *AuditEventResourceTypeMutation {
	return _u.mutation
}

// ClearAuditEvent clears the "audit_event" edge to the AuditEvent entity.
func (_u *AuditEventResourceTypeUpdateOne) ClearAuditEvent() *AuditEventResourceTypeUpdateOne {
	_u.mutation.ClearAuditEvent()
	return _u
}

// Where appends a list predicates to the AuditEventResourceTypeUpdate builder.
func (_u *AuditEventResourceTypeUpdateOne) Where(ps ...predicate.AuditEventResourceType) *AuditEventResourceTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditEventResourceTypeUpdateOne) Select(field string, fields ...string) *AuditEventResourceTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditEventResourceType entity.
func (_u *AuditEventResourceTypeUpdateOne) Save(ctx context.Context) (*AuditEventResourceType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventResourceTypeUpdateOne) SaveX(ctx context.Context) *AuditEventResourceType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditEventResourceTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventResourceTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditEventResourceTypeUpdateOne) check() error {
	if _u.mutation.AuditEventCleared() && len(_u.mutation.AuditEventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuditEventResourceType.audit_event"`)
	}
	return nil
}

func (_u *AuditEventResourceTypeUpdateOne) sqlSave(ctx context.Context) (_node *AuditEventResourceType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditeventresourcetype.Table, auditeventresourcetype.Columns, sqlgraph.NewFieldSpec(auditeventresourcetype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditEventResourceType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditeventresourcetype.FieldID)
		for _, f := range fields {
			if !auditeventresourcetype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditeventresourcetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditeventresourcetype.FieldResourceType, field.TypeString, value)
	}
	if _u.mutation.AuditEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditeventresourcetype.AuditEventTable,
			Columns: []string{auditeventresourcetype.AuditEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuditEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditeventresourcetype.AuditEventTable,
			Columns: []string{auditeventresourcetype.AuditEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuditEventResourceType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditeventresourcetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
