// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/auditevent"
	"github.com/armada/orbital/ent/auditeventresource"
	"github.com/armada/orbital/ent/auditeventresourcetype"
	"github.com/google/uuid"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
}

// SetOperations sets the "operations" field.
func (_c *AuditEventCreate) SetOperations(v []string) *AuditEventCreate {
	_c.mutation.SetOperations(v)
	return _c
}

// SetActor sets the "actor" field.
func (_c *AuditEventCreate) SetActor(v string) *AuditEventCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *AuditEventCreate) SetTimestamp(v time.Time) *AuditEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableTimestamp(v *time.Time) *AuditEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *AuditEventCreate) SetDetails(v json.RawMessage) *AuditEventCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetEventCategory sets the "event_category" field.
func (_c *AuditEventCreate) SetEventCategory(v string) *AuditEventCreate {
	_c.mutation.SetEventCategory(v)
	return _c
}

// SetNillableEventCategory sets the "event_category" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableEventCategory(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetEventCategory(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditEventCreate) SetID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableID(v *uuid.UUID) *AuditEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddResourceIDs adds the "resources" edge to the AuditEventResource entity by IDs.
func (_c *AuditEventCreate) AddResourceIDs(ids ...int) *AuditEventCreate {
	_c.mutation.AddResourceIDs(ids...)
	return _c
}

// AddResources adds the "resources" edges to the AuditEventResource entity.
func (_c *AuditEventCreate) AddResources(v ...*AuditEventResource) *AuditEventCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResourceIDs(ids...)
}

// AddResourceTypeIDs adds the "resource_types" edge to the AuditEventResourceType entity by IDs.
func (_c *AuditEventCreate) AddResourceTypeIDs(ids ...int) *AuditEventCreate {
	_c.mutation.AddResourceTypeIDs(ids...)
	return _c
}

// AddResourceTypes adds the "resource_types" edges to the AuditEventResourceType entity.
func (_c *AuditEventCreate) AddResourceTypes(v ...*AuditEventResourceType) *AuditEventCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResourceTypeIDs(ids...)
}

// Mutation returns the AuditEventMutation object of the builder.
func (_c *AuditEventCreate) Mutation() *AuditEventMutation {
	return _c.mutation
}

// Save creates the AuditEvent in the database.
func (_c *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditEventCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := auditevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.EventCategory(); !ok {
		v := auditevent.DefaultEventCategory
		_c.mutation.SetEventCategory(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := auditevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventCreate) check() error {
	if _, ok := _c.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "AuditEvent.actor"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AuditEvent.timestamp"`)}
	}
	if _, ok := _c.mutation.EventCategory(); !ok {
		return &ValidationError{Name: "event_category", err: errors.New(`ent: missing required field "AuditEvent.event_category"`)}
	}
	return nil
}

func (_c *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Operations(); ok {
		_spec.SetField(auditevent.FieldOperations, field.TypeJSON, value)
		_node.Operations = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(auditevent.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(auditevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(auditevent.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.EventCategory(); ok {
		_spec.SetField(auditevent.FieldEventCategory, field.TypeString, value)
		_node.EventCategory = value
	}
	if nodes := _c.mutation.ResourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   auditevent.ResourcesTable,
			Columns: []string{auditevent.ResourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditeventresource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResourceTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   auditevent.ResourceTypesTable,
			Columns: []string{auditevent.ResourceTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditeventresourcetype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
}

// Save creates the AuditEvent entities in the database.
func (_c *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
