// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/auditevent"
	"github.com/armada/orbital/ent/auditeventresource"
	"github.com/google/uuid"
)

// AuditEventResourceCreate is the builder for creating a AuditEventResource entity.
type AuditEventResourceCreate struct {
	config
	mutation *AuditEventResourceMutation
	hooks    []Hook
}

// SetAuditEventID sets the "audit_event_id" field.
func (_c *AuditEventResourceCreate) SetAuditEventID(v uuid.UUID) *AuditEventResourceCreate {
	_c.mutation.SetAuditEventID(v)
	return _c
}

// SetOrbID sets the "orb_id" field.
func (_c *AuditEventResourceCreate) SetOrbID(v string) *AuditEventResourceCreate {
	_c.mutation.SetOrbID(v)
	return _c
}

// SetAuditEvent sets the "audit_event" edge to the AuditEvent entity.
func (_c *AuditEventResourceCreate) SetAuditEvent(v *AuditEvent) *AuditEventResourceCreate {
	return _c.SetAuditEventID(v.ID)
}

// Mutation returns the AuditEventResourceMutation object of the builder.
func (_c *AuditEventResourceCreate) Mutation() *AuditEventResourceMutation {
	return _c.mutation
}

// Save creates the AuditEventResource in the database.
func (_c *AuditEventResourceCreate) Save(ctx context.Context) (*AuditEventResource, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventResourceCreate) SaveX(ctx context.Context) *AuditEventResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventResourceCreate) check() error {
	if _, ok := _c.mutation.AuditEventID(); !ok {
		return &ValidationError{Name: "audit_event_id", err: errors.New(`ent: missing required field "AuditEventResource.audit_event_id"`)}
	}
	if _, ok := _c.mutation.OrbID(); !ok {
		return &ValidationError{Name: "orb_id", err: errors.New(`ent: missing required field "AuditEventResource.orb_id"`)}
	}
	if len(_c.mutation.AuditEventIDs()) == 0 {
		return &ValidationError{Name: "audit_event", err: errors.New(`ent: missing required edge "AuditEventResource.audit_event"`)}
	}
	return nil
}

func (_c *AuditEventResourceCreate) sqlSave(ctx context.Context) (*AuditEventResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventResourceCreate) createSpec() (*AuditEventResource, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEventResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditeventresource.Table, sqlgraph.NewFieldSpec(auditeventresource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OrbID(); ok {
		_spec.SetField(auditeventresource.FieldOrbID, field.TypeString, value)
		_node.OrbID = value
	}
	if nodes := _c.mutation.AuditEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditeventresource.AuditEventTable,
			Columns: []string{auditeventresource.AuditEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuditEventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuditEventResourceCreateBulk is the builder for creating many AuditEventResource entities in bulk.
type AuditEventResourceCreateBulk struct {
	config
	err      error
	builders []*AuditEventResourceCreate
}

// Save creates the AuditEventResource entities in the database.
func (_c *AuditEventResourceCreateBulk) Save(ctx context.Context) ([]*AuditEventResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEventResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventResourceCreateBulk) SaveX(ctx context.Context) []*AuditEventResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
