// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/armada/orbital/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/armada/orbital/ent/backup"
	"github.com/armada/orbital/ent/event"
	"github.com/armada/orbital/ent/exportjob"
	"github.com/armada/orbital/ent/namespace"
	"github.com/armada/orbital/ent/orb"
	"github.com/armada/orbital/ent/registryartifact"
	"github.com/armada/orbital/ent/restorejob"
	"github.com/armada/orbital/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Backup is the client for interacting with the Backup builders.
	Backup *BackupClient
	// Event is the client for interacting with the Event builders.
	Event *EventClient
	// ExportJob is the client for interacting with the ExportJob builders.
	ExportJob *ExportJobClient
	// Namespace is the client for interacting with the Namespace builders.
	Namespace *NamespaceClient
	// Orb is the client for interacting with the Orb builders.
	Orb *OrbClient
	// RegistryArtifact is the client for interacting with the RegistryArtifact builders.
	RegistryArtifact *RegistryArtifactClient
	// RestoreJob is the client for interacting with the RestoreJob builders.
	RestoreJob *RestoreJobClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Backup = NewBackupClient(c.config)
	c.Event = NewEventClient(c.config)
	c.ExportJob = NewExportJobClient(c.config)
	c.Namespace = NewNamespaceClient(c.config)
	c.Orb = NewOrbClient(c.config)
	c.RegistryArtifact = NewRegistryArtifactClient(c.config)
	c.RestoreJob = NewRestoreJobClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Backup:           NewBackupClient(cfg),
		Event:            NewEventClient(cfg),
		ExportJob:        NewExportJobClient(cfg),
		Namespace:        NewNamespaceClient(cfg),
		Orb:              NewOrbClient(cfg),
		RegistryArtifact: NewRegistryArtifactClient(cfg),
		RestoreJob:       NewRestoreJobClient(cfg),
		User:             NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Backup:           NewBackupClient(cfg),
		Event:            NewEventClient(cfg),
		ExportJob:        NewExportJobClient(cfg),
		Namespace:        NewNamespaceClient(cfg),
		Orb:              NewOrbClient(cfg),
		RegistryArtifact: NewRegistryArtifactClient(cfg),
		RestoreJob:       NewRestoreJobClient(cfg),
		User:             NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Backup.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Backup, c.Event, c.ExportJob, c.Namespace, c.Orb, c.RegistryArtifact,
		c.RestoreJob, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Backup, c.Event, c.ExportJob, c.Namespace, c.Orb, c.RegistryArtifact,
		c.RestoreJob, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BackupMutation:
		return c.Backup.mutate(ctx, m)
	case *EventMutation:
		return c.Event.mutate(ctx, m)
	case *ExportJobMutation:
		return c.ExportJob.mutate(ctx, m)
	case *NamespaceMutation:
		return c.Namespace.mutate(ctx, m)
	case *OrbMutation:
		return c.Orb.mutate(ctx, m)
	case *RegistryArtifactMutation:
		return c.RegistryArtifact.mutate(ctx, m)
	case *RestoreJobMutation:
		return c.RestoreJob.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BackupClient is a client for the Backup schema.
type BackupClient struct {
	config
}

// NewBackupClient returns a client for the Backup from the given config.
func NewBackupClient(c config) *BackupClient {
	return &BackupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backup.Hooks(f(g(h())))`.
func (c *BackupClient) Use(hooks ...Hook) {
	c.hooks.Backup = append(c.hooks.Backup, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backup.Intercept(f(g(h())))`.
func (c *BackupClient) Intercept(interceptors ...Interceptor) {
	c.inters.Backup = append(c.inters.Backup, interceptors...)
}

// Create returns a builder for creating a Backup entity.
func (c *BackupClient) Create() *BackupCreate {
	mutation := newBackupMutation(c.config, OpCreate)
	return &BackupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Backup entities.
func (c *BackupClient) CreateBulk(builders ...*BackupCreate) *BackupCreateBulk {
	return &BackupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackupClient) MapCreateBulk(slice any, setFunc func(*BackupCreate, int)) *BackupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackupCreateBulk{err: fmt.Errorf("calling to BackupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Backup.
func (c *BackupClient) Update() *BackupUpdate {
	mutation := newBackupMutation(c.config, OpUpdate)
	return &BackupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackupClient) UpdateOne(_m *Backup) *BackupUpdateOne {
	mutation := newBackupMutation(c.config, OpUpdateOne, withBackup(_m))
	return &BackupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackupClient) UpdateOneID(id uuid.UUID) *BackupUpdateOne {
	mutation := newBackupMutation(c.config, OpUpdateOne, withBackupID(id))
	return &BackupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Backup.
func (c *BackupClient) Delete() *BackupDelete {
	mutation := newBackupMutation(c.config, OpDelete)
	return &BackupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackupClient) DeleteOne(_m *Backup) *BackupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackupClient) DeleteOneID(id uuid.UUID) *BackupDeleteOne {
	builder := c.Delete().Where(backup.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackupDeleteOne{builder}
}

// Query returns a query builder for Backup.
func (c *BackupClient) Query() *BackupQuery {
	return &BackupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackup},
		inters: c.Interceptors(),
	}
}

// Get returns a Backup entity by its id.
func (c *BackupClient) Get(ctx context.Context, id uuid.UUID) (*Backup, error) {
	return c.Query().Where(backup.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackupClient) GetX(ctx context.Context, id uuid.UUID) *Backup {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BackupClient) Hooks() []Hook {
	return c.hooks.Backup
}

// Interceptors returns the client interceptors.
func (c *BackupClient) Interceptors() []Interceptor {
	return c.inters.Backup
}

func (c *BackupClient) mutate(ctx context.Context, m *BackupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Backup mutation op: %q", m.Op())
	}
}

// EventClient is a client for the Event schema.
type EventClient struct {
	config
}

// NewEventClient returns a client for the Event from the given config.
func NewEventClient(c config) *EventClient {
	return &EventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `event.Hooks(f(g(h())))`.
func (c *EventClient) Use(hooks ...Hook) {
	c.hooks.Event = append(c.hooks.Event, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `event.Intercept(f(g(h())))`.
func (c *EventClient) Intercept(interceptors ...Interceptor) {
	c.inters.Event = append(c.inters.Event, interceptors...)
}

// Create returns a builder for creating a Event entity.
func (c *EventClient) Create() *EventCreate {
	mutation := newEventMutation(c.config, OpCreate)
	return &EventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Event entities.
func (c *EventClient) CreateBulk(builders ...*EventCreate) *EventCreateBulk {
	return &EventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventClient) MapCreateBulk(slice any, setFunc func(*EventCreate, int)) *EventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventCreateBulk{err: fmt.Errorf("calling to EventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Event.
func (c *EventClient) Update() *EventUpdate {
	mutation := newEventMutation(c.config, OpUpdate)
	return &EventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventClient) UpdateOne(_m *Event) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEvent(_m))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventClient) UpdateOneID(id uuid.UUID) *EventUpdateOne {
	mutation := newEventMutation(c.config, OpUpdateOne, withEventID(id))
	return &EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Event.
func (c *EventClient) Delete() *EventDelete {
	mutation := newEventMutation(c.config, OpDelete)
	return &EventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventClient) DeleteOne(_m *Event) *EventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventClient) DeleteOneID(id uuid.UUID) *EventDeleteOne {
	builder := c.Delete().Where(event.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventDeleteOne{builder}
}

// Query returns a query builder for Event.
func (c *EventClient) Query() *EventQuery {
	return &EventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a Event entity by its id.
func (c *EventClient) Get(ctx context.Context, id uuid.UUID) (*Event, error) {
	return c.Query().Where(event.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventClient) GetX(ctx context.Context, id uuid.UUID) *Event {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EventClient) Hooks() []Hook {
	return c.hooks.Event
}

// Interceptors returns the client interceptors.
func (c *EventClient) Interceptors() []Interceptor {
	return c.inters.Event
}

func (c *EventClient) mutate(ctx context.Context, m *EventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Event mutation op: %q", m.Op())
	}
}

// ExportJobClient is a client for the ExportJob schema.
type ExportJobClient struct {
	config
}

// NewExportJobClient returns a client for the ExportJob from the given config.
func NewExportJobClient(c config) *ExportJobClient {
	return &ExportJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `exportjob.Hooks(f(g(h())))`.
func (c *ExportJobClient) Use(hooks ...Hook) {
	c.hooks.ExportJob = append(c.hooks.ExportJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `exportjob.Intercept(f(g(h())))`.
func (c *ExportJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.ExportJob = append(c.inters.ExportJob, interceptors...)
}

// Create returns a builder for creating a ExportJob entity.
func (c *ExportJobClient) Create() *ExportJobCreate {
	mutation := newExportJobMutation(c.config, OpCreate)
	return &ExportJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ExportJob entities.
func (c *ExportJobClient) CreateBulk(builders ...*ExportJobCreate) *ExportJobCreateBulk {
	return &ExportJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExportJobClient) MapCreateBulk(slice any, setFunc func(*ExportJobCreate, int)) *ExportJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExportJobCreateBulk{err: fmt.Errorf("calling to ExportJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExportJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExportJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ExportJob.
func (c *ExportJobClient) Update() *ExportJobUpdate {
	mutation := newExportJobMutation(c.config, OpUpdate)
	return &ExportJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExportJobClient) UpdateOne(_m *ExportJob) *ExportJobUpdateOne {
	mutation := newExportJobMutation(c.config, OpUpdateOne, withExportJob(_m))
	return &ExportJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExportJobClient) UpdateOneID(id uuid.UUID) *ExportJobUpdateOne {
	mutation := newExportJobMutation(c.config, OpUpdateOne, withExportJobID(id))
	return &ExportJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ExportJob.
func (c *ExportJobClient) Delete() *ExportJobDelete {
	mutation := newExportJobMutation(c.config, OpDelete)
	return &ExportJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExportJobClient) DeleteOne(_m *ExportJob) *ExportJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExportJobClient) DeleteOneID(id uuid.UUID) *ExportJobDeleteOne {
	builder := c.Delete().Where(exportjob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExportJobDeleteOne{builder}
}

// Query returns a query builder for ExportJob.
func (c *ExportJobClient) Query() *ExportJobQuery {
	return &ExportJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExportJob},
		inters: c.Interceptors(),
	}
}

// Get returns a ExportJob entity by its id.
func (c *ExportJobClient) Get(ctx context.Context, id uuid.UUID) (*ExportJob, error) {
	return c.Query().Where(exportjob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExportJobClient) GetX(ctx context.Context, id uuid.UUID) *ExportJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ExportJobClient) Hooks() []Hook {
	return c.hooks.ExportJob
}

// Interceptors returns the client interceptors.
func (c *ExportJobClient) Interceptors() []Interceptor {
	return c.inters.ExportJob
}

func (c *ExportJobClient) mutate(ctx context.Context, m *ExportJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExportJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExportJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExportJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExportJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ExportJob mutation op: %q", m.Op())
	}
}

// NamespaceClient is a client for the Namespace schema.
type NamespaceClient struct {
	config
}

// NewNamespaceClient returns a client for the Namespace from the given config.
func NewNamespaceClient(c config) *NamespaceClient {
	return &NamespaceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `namespace.Hooks(f(g(h())))`.
func (c *NamespaceClient) Use(hooks ...Hook) {
	c.hooks.Namespace = append(c.hooks.Namespace, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `namespace.Intercept(f(g(h())))`.
func (c *NamespaceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Namespace = append(c.inters.Namespace, interceptors...)
}

// Create returns a builder for creating a Namespace entity.
func (c *NamespaceClient) Create() *NamespaceCreate {
	mutation := newNamespaceMutation(c.config, OpCreate)
	return &NamespaceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Namespace entities.
func (c *NamespaceClient) CreateBulk(builders ...*NamespaceCreate) *NamespaceCreateBulk {
	return &NamespaceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NamespaceClient) MapCreateBulk(slice any, setFunc func(*NamespaceCreate, int)) *NamespaceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NamespaceCreateBulk{err: fmt.Errorf("calling to NamespaceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NamespaceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NamespaceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Namespace.
func (c *NamespaceClient) Update() *NamespaceUpdate {
	mutation := newNamespaceMutation(c.config, OpUpdate)
	return &NamespaceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NamespaceClient) UpdateOne(_m *Namespace) *NamespaceUpdateOne {
	mutation := newNamespaceMutation(c.config, OpUpdateOne, withNamespace(_m))
	return &NamespaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NamespaceClient) UpdateOneID(id uuid.UUID) *NamespaceUpdateOne {
	mutation := newNamespaceMutation(c.config, OpUpdateOne, withNamespaceID(id))
	return &NamespaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Namespace.
func (c *NamespaceClient) Delete() *NamespaceDelete {
	mutation := newNamespaceMutation(c.config, OpDelete)
	return &NamespaceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NamespaceClient) DeleteOne(_m *Namespace) *NamespaceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NamespaceClient) DeleteOneID(id uuid.UUID) *NamespaceDeleteOne {
	builder := c.Delete().Where(namespace.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NamespaceDeleteOne{builder}
}

// Query returns a query builder for Namespace.
func (c *NamespaceClient) Query() *NamespaceQuery {
	return &NamespaceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNamespace},
		inters: c.Interceptors(),
	}
}

// Get returns a Namespace entity by its id.
func (c *NamespaceClient) Get(ctx context.Context, id uuid.UUID) (*Namespace, error) {
	return c.Query().Where(namespace.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NamespaceClient) GetX(ctx context.Context, id uuid.UUID) *Namespace {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NamespaceClient) Hooks() []Hook {
	return c.hooks.Namespace
}

// Interceptors returns the client interceptors.
func (c *NamespaceClient) Interceptors() []Interceptor {
	return c.inters.Namespace
}

func (c *NamespaceClient) mutate(ctx context.Context, m *NamespaceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NamespaceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NamespaceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NamespaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NamespaceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Namespace mutation op: %q", m.Op())
	}
}

// OrbClient is a client for the Orb schema.
type OrbClient struct {
	config
}

// NewOrbClient returns a client for the Orb from the given config.
func NewOrbClient(c config) *OrbClient {
	return &OrbClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `orb.Hooks(f(g(h())))`.
func (c *OrbClient) Use(hooks ...Hook) {
	c.hooks.Orb = append(c.hooks.Orb, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `orb.Intercept(f(g(h())))`.
func (c *OrbClient) Intercept(interceptors ...Interceptor) {
	c.inters.Orb = append(c.inters.Orb, interceptors...)
}

// Create returns a builder for creating a Orb entity.
func (c *OrbClient) Create() *OrbCreate {
	mutation := newOrbMutation(c.config, OpCreate)
	return &OrbCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Orb entities.
func (c *OrbClient) CreateBulk(builders ...*OrbCreate) *OrbCreateBulk {
	return &OrbCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrbClient) MapCreateBulk(slice any, setFunc func(*OrbCreate, int)) *OrbCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrbCreateBulk{err: fmt.Errorf("calling to OrbClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrbCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrbCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Orb.
func (c *OrbClient) Update() *OrbUpdate {
	mutation := newOrbMutation(c.config, OpUpdate)
	return &OrbUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrbClient) UpdateOne(_m *Orb) *OrbUpdateOne {
	mutation := newOrbMutation(c.config, OpUpdateOne, withOrb(_m))
	return &OrbUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrbClient) UpdateOneID(id uuid.UUID) *OrbUpdateOne {
	mutation := newOrbMutation(c.config, OpUpdateOne, withOrbID(id))
	return &OrbUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Orb.
func (c *OrbClient) Delete() *OrbDelete {
	mutation := newOrbMutation(c.config, OpDelete)
	return &OrbDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrbClient) DeleteOne(_m *Orb) *OrbDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrbClient) DeleteOneID(id uuid.UUID) *OrbDeleteOne {
	builder := c.Delete().Where(orb.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrbDeleteOne{builder}
}

// Query returns a query builder for Orb.
func (c *OrbClient) Query() *OrbQuery {
	return &OrbQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrb},
		inters: c.Interceptors(),
	}
}

// Get returns a Orb entity by its id.
func (c *OrbClient) Get(ctx context.Context, id uuid.UUID) (*Orb, error) {
	return c.Query().Where(orb.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrbClient) GetX(ctx context.Context, id uuid.UUID) *Orb {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OrbClient) Hooks() []Hook {
	return c.hooks.Orb
}

// Interceptors returns the client interceptors.
func (c *OrbClient) Interceptors() []Interceptor {
	return c.inters.Orb
}

func (c *OrbClient) mutate(ctx context.Context, m *OrbMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrbCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrbUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrbUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrbDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Orb mutation op: %q", m.Op())
	}
}

// RegistryArtifactClient is a client for the RegistryArtifact schema.
type RegistryArtifactClient struct {
	config
}

// NewRegistryArtifactClient returns a client for the RegistryArtifact from the given config.
func NewRegistryArtifactClient(c config) *RegistryArtifactClient {
	return &RegistryArtifactClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `registryartifact.Hooks(f(g(h())))`.
func (c *RegistryArtifactClient) Use(hooks ...Hook) {
	c.hooks.RegistryArtifact = append(c.hooks.RegistryArtifact, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `registryartifact.Intercept(f(g(h())))`.
func (c *RegistryArtifactClient) Intercept(interceptors ...Interceptor) {
	c.inters.RegistryArtifact = append(c.inters.RegistryArtifact, interceptors...)
}

// Create returns a builder for creating a RegistryArtifact entity.
func (c *RegistryArtifactClient) Create() *RegistryArtifactCreate {
	mutation := newRegistryArtifactMutation(c.config, OpCreate)
	return &RegistryArtifactCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RegistryArtifact entities.
func (c *RegistryArtifactClient) CreateBulk(builders ...*RegistryArtifactCreate) *RegistryArtifactCreateBulk {
	return &RegistryArtifactCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RegistryArtifactClient) MapCreateBulk(slice any, setFunc func(*RegistryArtifactCreate, int)) *RegistryArtifactCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RegistryArtifactCreateBulk{err: fmt.Errorf("calling to RegistryArtifactClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RegistryArtifactCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RegistryArtifactCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RegistryArtifact.
func (c *RegistryArtifactClient) Update() *RegistryArtifactUpdate {
	mutation := newRegistryArtifactMutation(c.config, OpUpdate)
	return &RegistryArtifactUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RegistryArtifactClient) UpdateOne(_m *RegistryArtifact) *RegistryArtifactUpdateOne {
	mutation := newRegistryArtifactMutation(c.config, OpUpdateOne, withRegistryArtifact(_m))
	return &RegistryArtifactUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RegistryArtifactClient) UpdateOneID(id int) *RegistryArtifactUpdateOne {
	mutation := newRegistryArtifactMutation(c.config, OpUpdateOne, withRegistryArtifactID(id))
	return &RegistryArtifactUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RegistryArtifact.
func (c *RegistryArtifactClient) Delete() *RegistryArtifactDelete {
	mutation := newRegistryArtifactMutation(c.config, OpDelete)
	return &RegistryArtifactDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RegistryArtifactClient) DeleteOne(_m *RegistryArtifact) *RegistryArtifactDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RegistryArtifactClient) DeleteOneID(id int) *RegistryArtifactDeleteOne {
	builder := c.Delete().Where(registryartifact.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RegistryArtifactDeleteOne{builder}
}

// Query returns a query builder for RegistryArtifact.
func (c *RegistryArtifactClient) Query() *RegistryArtifactQuery {
	return &RegistryArtifactQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRegistryArtifact},
		inters: c.Interceptors(),
	}
}

// Get returns a RegistryArtifact entity by its id.
func (c *RegistryArtifactClient) Get(ctx context.Context, id int) (*RegistryArtifact, error) {
	return c.Query().Where(registryartifact.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RegistryArtifactClient) GetX(ctx context.Context, id int) *RegistryArtifact {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RegistryArtifactClient) Hooks() []Hook {
	return c.hooks.RegistryArtifact
}

// Interceptors returns the client interceptors.
func (c *RegistryArtifactClient) Interceptors() []Interceptor {
	return c.inters.RegistryArtifact
}

func (c *RegistryArtifactClient) mutate(ctx context.Context, m *RegistryArtifactMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RegistryArtifactCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RegistryArtifactUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RegistryArtifactUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RegistryArtifactDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RegistryArtifact mutation op: %q", m.Op())
	}
}

// RestoreJobClient is a client for the RestoreJob schema.
type RestoreJobClient struct {
	config
}

// NewRestoreJobClient returns a client for the RestoreJob from the given config.
func NewRestoreJobClient(c config) *RestoreJobClient {
	return &RestoreJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `restorejob.Hooks(f(g(h())))`.
func (c *RestoreJobClient) Use(hooks ...Hook) {
	c.hooks.RestoreJob = append(c.hooks.RestoreJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `restorejob.Intercept(f(g(h())))`.
func (c *RestoreJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.RestoreJob = append(c.inters.RestoreJob, interceptors...)
}

// Create returns a builder for creating a RestoreJob entity.
func (c *RestoreJobClient) Create() *RestoreJobCreate {
	mutation := newRestoreJobMutation(c.config, OpCreate)
	return &RestoreJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RestoreJob entities.
func (c *RestoreJobClient) CreateBulk(builders ...*RestoreJobCreate) *RestoreJobCreateBulk {
	return &RestoreJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RestoreJobClient) MapCreateBulk(slice any, setFunc func(*RestoreJobCreate, int)) *RestoreJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RestoreJobCreateBulk{err: fmt.Errorf("calling to RestoreJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RestoreJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RestoreJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RestoreJob.
func (c *RestoreJobClient) Update() *RestoreJobUpdate {
	mutation := newRestoreJobMutation(c.config, OpUpdate)
	return &RestoreJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RestoreJobClient) UpdateOne(_m *RestoreJob) *RestoreJobUpdateOne {
	mutation := newRestoreJobMutation(c.config, OpUpdateOne, withRestoreJob(_m))
	return &RestoreJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RestoreJobClient) UpdateOneID(id uuid.UUID) *RestoreJobUpdateOne {
	mutation := newRestoreJobMutation(c.config, OpUpdateOne, withRestoreJobID(id))
	return &RestoreJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RestoreJob.
func (c *RestoreJobClient) Delete() *RestoreJobDelete {
	mutation := newRestoreJobMutation(c.config, OpDelete)
	return &RestoreJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RestoreJobClient) DeleteOne(_m *RestoreJob) *RestoreJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RestoreJobClient) DeleteOneID(id uuid.UUID) *RestoreJobDeleteOne {
	builder := c.Delete().Where(restorejob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RestoreJobDeleteOne{builder}
}

// Query returns a query builder for RestoreJob.
func (c *RestoreJobClient) Query() *RestoreJobQuery {
	return &RestoreJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRestoreJob},
		inters: c.Interceptors(),
	}
}

// Get returns a RestoreJob entity by its id.
func (c *RestoreJobClient) Get(ctx context.Context, id uuid.UUID) (*RestoreJob, error) {
	return c.Query().Where(restorejob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RestoreJobClient) GetX(ctx context.Context, id uuid.UUID) *RestoreJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RestoreJobClient) Hooks() []Hook {
	return c.hooks.RestoreJob
}

// Interceptors returns the client interceptors.
func (c *RestoreJobClient) Interceptors() []Interceptor {
	return c.inters.RestoreJob
}

func (c *RestoreJobClient) mutate(ctx context.Context, m *RestoreJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RestoreJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RestoreJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RestoreJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RestoreJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RestoreJob mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Backup, Event, ExportJob, Namespace, Orb, RegistryArtifact, RestoreJob,
		User []ent.Hook
	}
	inters struct {
		Backup, Event, ExportJob, Namespace, Orb, RegistryArtifact, RestoreJob,
		User []ent.Interceptor
	}
)
