// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/divergenceresolution"
	"github.com/google/uuid"
)

// DivergenceResolutionCreate is the builder for creating a DivergenceResolution entity.
type DivergenceResolutionCreate struct {
	config
	mutation *DivergenceResolutionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DivergenceResolutionCreate) SetCreatedAt(v time.Time) *DivergenceResolutionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DivergenceResolutionCreate) SetNillableCreatedAt(v *time.Time) *DivergenceResolutionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DivergenceResolutionCreate) SetCreatedBy(v string) *DivergenceResolutionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DivergenceResolutionCreate) SetNillableCreatedBy(v *string) *DivergenceResolutionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DivergenceResolutionCreate) SetUpdatedAt(v time.Time) *DivergenceResolutionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DivergenceResolutionCreate) SetNillableUpdatedAt(v *time.Time) *DivergenceResolutionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *DivergenceResolutionCreate) SetUpdatedBy(v string) *DivergenceResolutionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *DivergenceResolutionCreate) SetNillableUpdatedBy(v *string) *DivergenceResolutionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetEntryOrbID sets the "entry_orb_id" field.
func (_c *DivergenceResolutionCreate) SetEntryOrbID(v string) *DivergenceResolutionCreate {
	_c.mutation.SetEntryOrbID(v)
	return _c
}

// SetField sets the "field" field.
func (_c *DivergenceResolutionCreate) SetField(v string) *DivergenceResolutionCreate {
	_c.mutation.SetFieldField(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *DivergenceResolutionCreate) SetAction(v divergenceresolution.Action) *DivergenceResolutionCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetActor sets the "actor" field.
func (_c *DivergenceResolutionCreate) SetActor(v string) *DivergenceResolutionCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetDecidedAt sets the "decided_at" field.
func (_c *DivergenceResolutionCreate) SetDecidedAt(v time.Time) *DivergenceResolutionCreate {
	_c.mutation.SetDecidedAt(v)
	return _c
}

// SetCbConsumed sets the "cb_consumed" field.
func (_c *DivergenceResolutionCreate) SetCbConsumed(v bool) *DivergenceResolutionCreate {
	_c.mutation.SetCbConsumed(v)
	return _c
}

// SetNillableCbConsumed sets the "cb_consumed" field if the given value is not nil.
func (_c *DivergenceResolutionCreate) SetNillableCbConsumed(v *bool) *DivergenceResolutionCreate {
	if v != nil {
		_c.SetCbConsumed(*v)
	}
	return _c
}

// SetCbConsumedAt sets the "cb_consumed_at" field.
func (_c *DivergenceResolutionCreate) SetCbConsumedAt(v time.Time) *DivergenceResolutionCreate {
	_c.mutation.SetCbConsumedAt(v)
	return _c
}

// SetNillableCbConsumedAt sets the "cb_consumed_at" field if the given value is not nil.
func (_c *DivergenceResolutionCreate) SetNillableCbConsumedAt(v *time.Time) *DivergenceResolutionCreate {
	if v != nil {
		_c.SetCbConsumedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DivergenceResolutionCreate) SetID(v uuid.UUID) *DivergenceResolutionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DivergenceResolutionCreate) SetNillableID(v *uuid.UUID) *DivergenceResolutionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DivergenceResolutionMutation object of the builder.
func (_c *DivergenceResolutionCreate) Mutation() *DivergenceResolutionMutation {
	return _c.mutation
}

// Save creates the DivergenceResolution in the database.
func (_c *DivergenceResolutionCreate) Save(ctx context.Context) (*DivergenceResolution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DivergenceResolutionCreate) SaveX(ctx context.Context) *DivergenceResolution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DivergenceResolutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DivergenceResolutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DivergenceResolutionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := divergenceresolution.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.CbConsumed(); !ok {
		v := divergenceresolution.DefaultCbConsumed
		_c.mutation.SetCbConsumed(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := divergenceresolution.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DivergenceResolutionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DivergenceResolution.created_at"`)}
	}
	if _, ok := _c.mutation.EntryOrbID(); !ok {
		return &ValidationError{Name: "entry_orb_id", err: errors.New(`ent: missing required field "DivergenceResolution.entry_orb_id"`)}
	}
	if v, ok := _c.mutation.EntryOrbID(); ok {
		if err := divergenceresolution.EntryOrbIDValidator(v); err != nil {
			return &ValidationError{Name: "entry_orb_id", err: fmt.Errorf(`ent: validator failed for field "DivergenceResolution.entry_orb_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetField(); !ok {
		return &ValidationError{Name: "field", err: errors.New(`ent: missing required field "DivergenceResolution.field"`)}
	}
	if v, ok := _c.mutation.GetField(); ok {
		if err := divergenceresolution.FieldValidator(v); err != nil {
			return &ValidationError{Name: "field", err: fmt.Errorf(`ent: validator failed for field "DivergenceResolution.field": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "DivergenceResolution.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := divergenceresolution.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "DivergenceResolution.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "DivergenceResolution.actor"`)}
	}
	if v, ok := _c.mutation.Actor(); ok {
		if err := divergenceresolution.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "DivergenceResolution.actor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DecidedAt(); !ok {
		return &ValidationError{Name: "decided_at", err: errors.New(`ent: missing required field "DivergenceResolution.decided_at"`)}
	}
	if _, ok := _c.mutation.CbConsumed(); !ok {
		return &ValidationError{Name: "cb_consumed", err: errors.New(`ent: missing required field "DivergenceResolution.cb_consumed"`)}
	}
	return nil
}

func (_c *DivergenceResolutionCreate) sqlSave(ctx context.Context) (*DivergenceResolution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DivergenceResolutionCreate) createSpec() (*DivergenceResolution, *sqlgraph.CreateSpec) {
	var (
		_node = &DivergenceResolution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(divergenceresolution.Table, sqlgraph.NewFieldSpec(divergenceresolution.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(divergenceresolution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(divergenceresolution.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(divergenceresolution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(divergenceresolution.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.EntryOrbID(); ok {
		_spec.SetField(divergenceresolution.FieldEntryOrbID, field.TypeString, value)
		_node.EntryOrbID = value
	}
	if value, ok := _c.mutation.GetField(); ok {
		_spec.SetField(divergenceresolution.FieldField, field.TypeString, value)
		_node.Field = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(divergenceresolution.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(divergenceresolution.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	if value, ok := _c.mutation.DecidedAt(); ok {
		_spec.SetField(divergenceresolution.FieldDecidedAt, field.TypeTime, value)
		_node.DecidedAt = value
	}
	if value, ok := _c.mutation.CbConsumed(); ok {
		_spec.SetField(divergenceresolution.FieldCbConsumed, field.TypeBool, value)
		_node.CbConsumed = value
	}
	if value, ok := _c.mutation.CbConsumedAt(); ok {
		_spec.SetField(divergenceresolution.FieldCbConsumedAt, field.TypeTime, value)
		_node.CbConsumedAt = &value
	}
	return _node, _spec
}

// DivergenceResolutionCreateBulk is the builder for creating many DivergenceResolution entities in bulk.
type DivergenceResolutionCreateBulk struct {
	config
	err      error
	builders []*DivergenceResolutionCreate
}

// Save creates the DivergenceResolution entities in the database.
func (_c *DivergenceResolutionCreateBulk) Save(ctx context.Context) ([]*DivergenceResolution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DivergenceResolution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DivergenceResolutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DivergenceResolutionCreateBulk) SaveX(ctx context.Context) []*DivergenceResolution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DivergenceResolutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DivergenceResolutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
