// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/armada/orbital/ent/divergenceentry"
	"github.com/google/uuid"
)

// DivergenceEntry is the model entity for the DivergenceEntry schema.
type DivergenceEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// DcOrbID holds the value of the "dc_orb_id" field.
	DcOrbID string `json:"dc_orb_id,omitempty"`
	// EntryOrbID holds the value of the "entry_orb_id" field.
	EntryOrbID string `json:"entry_orb_id,omitempty"`
	// Field holds the value of the "field" field.
	Field string `json:"field,omitempty"`
	// TypeName holds the value of the "type_name" field.
	TypeName string `json:"type_name,omitempty"`
	// IntendedValue holds the value of the "intended_value" field.
	IntendedValue json.RawMessage `json:"intended_value,omitempty"`
	// OverrideValue holds the value of the "override_value" field.
	OverrideValue json.RawMessage `json:"override_value,omitempty"`
	// Who holds the value of the "who" field.
	Who string `json:"who,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt time.Time `json:"first_seen_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// LastReportPublishedAt holds the value of the "last_report_published_at" field.
	LastReportPublishedAt time.Time `json:"last_report_published_at,omitempty"`
	selectValues          sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DivergenceEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case divergenceentry.FieldIntendedValue, divergenceentry.FieldOverrideValue:
			values[i] = new([]byte)
		case divergenceentry.FieldCreatedBy, divergenceentry.FieldUpdatedBy, divergenceentry.FieldDcOrbID, divergenceentry.FieldEntryOrbID, divergenceentry.FieldField, divergenceentry.FieldTypeName, divergenceentry.FieldWho:
			values[i] = new(sql.NullString)
		case divergenceentry.FieldCreatedAt, divergenceentry.FieldUpdatedAt, divergenceentry.FieldFirstSeenAt, divergenceentry.FieldLastSeenAt, divergenceentry.FieldLastReportPublishedAt:
			values[i] = new(sql.NullTime)
		case divergenceentry.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DivergenceEntry fields.
func (_m *DivergenceEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case divergenceentry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case divergenceentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case divergenceentry.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case divergenceentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case divergenceentry.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case divergenceentry.FieldDcOrbID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dc_orb_id", values[i])
			} else if value.Valid {
				_m.DcOrbID = value.String
			}
		case divergenceentry.FieldEntryOrbID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_orb_id", values[i])
			} else if value.Valid {
				_m.EntryOrbID = value.String
			}
		case divergenceentry.FieldField:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field", values[i])
			} else if value.Valid {
				_m.Field = value.String
			}
		case divergenceentry.FieldTypeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type_name", values[i])
			} else if value.Valid {
				_m.TypeName = value.String
			}
		case divergenceentry.FieldIntendedValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field intended_value", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IntendedValue); err != nil {
					return fmt.Errorf("unmarshal field intended_value: %w", err)
				}
			}
		case divergenceentry.FieldOverrideValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field override_value", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OverrideValue); err != nil {
					return fmt.Errorf("unmarshal field override_value: %w", err)
				}
			}
		case divergenceentry.FieldWho:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field who", values[i])
			} else if value.Valid {
				_m.Who = value.String
			}
		case divergenceentry.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				_m.FirstSeenAt = value.Time
			}
		case divergenceentry.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case divergenceentry.FieldLastReportPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_report_published_at", values[i])
			} else if value.Valid {
				_m.LastReportPublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DivergenceEntry.
// This includes values selected through modifiers, order, etc.
func (_m *DivergenceEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DivergenceEntry.
// Note that you need to call DivergenceEntry.Unwrap() before calling this method if this DivergenceEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DivergenceEntry) Update() *DivergenceEntryUpdateOne {
	return NewDivergenceEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DivergenceEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DivergenceEntry) Unwrap() *DivergenceEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DivergenceEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DivergenceEntry) String() string {
	var builder strings.Builder
	builder.WriteString("DivergenceEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("dc_orb_id=")
	builder.WriteString(_m.DcOrbID)
	builder.WriteString(", ")
	builder.WriteString("entry_orb_id=")
	builder.WriteString(_m.EntryOrbID)
	builder.WriteString(", ")
	builder.WriteString("field=")
	builder.WriteString(_m.Field)
	builder.WriteString(", ")
	builder.WriteString("type_name=")
	builder.WriteString(_m.TypeName)
	builder.WriteString(", ")
	builder.WriteString("intended_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntendedValue))
	builder.WriteString(", ")
	builder.WriteString("override_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverrideValue))
	builder.WriteString(", ")
	builder.WriteString("who=")
	builder.WriteString(_m.Who)
	builder.WriteString(", ")
	builder.WriteString("first_seen_at=")
	builder.WriteString(_m.FirstSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_report_published_at=")
	builder.WriteString(_m.LastReportPublishedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DivergenceEntries is a parsable slice of DivergenceEntry.
type DivergenceEntries []*DivergenceEntry
