// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/event"
	"github.com/armada/orbital/ent/eventresourcetype"
	"github.com/google/uuid"
)

// EventResourceTypeCreate is the builder for creating a EventResourceType entity.
type EventResourceTypeCreate struct {
	config
	mutation *EventResourceTypeMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *EventResourceTypeCreate) SetEventID(v uuid.UUID) *EventResourceTypeCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *EventResourceTypeCreate) SetResourceType(v string) *EventResourceTypeCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *EventResourceTypeCreate) SetEvent(v *Event) *EventResourceTypeCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the EventResourceTypeMutation object of the builder.
func (_c *EventResourceTypeCreate) Mutation() *EventResourceTypeMutation {
	return _c.mutation
}

// Save creates the EventResourceType in the database.
func (_c *EventResourceTypeCreate) Save(ctx context.Context) (*EventResourceType, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventResourceTypeCreate) SaveX(ctx context.Context) *EventResourceType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventResourceTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventResourceTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventResourceTypeCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "EventResourceType.event_id"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "EventResourceType.resource_type"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "EventResourceType.event"`)}
	}
	return nil
}

func (_c *EventResourceTypeCreate) sqlSave(ctx context.Context) (*EventResourceType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventResourceTypeCreate) createSpec() (*EventResourceType, *sqlgraph.CreateSpec) {
	var (
		_node = &EventResourceType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventresourcetype.Table, sqlgraph.NewFieldSpec(eventresourcetype.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(eventresourcetype.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventresourcetype.EventTable,
			Columns: []string{eventresourcetype.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventResourceTypeCreateBulk is the builder for creating many EventResourceType entities in bulk.
type EventResourceTypeCreateBulk struct {
	config
	err      error
	builders []*EventResourceTypeCreate
}

// Save creates the EventResourceType entities in the database.
func (_c *EventResourceTypeCreateBulk) Save(ctx context.Context) ([]*EventResourceType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventResourceType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventResourceTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventResourceTypeCreateBulk) SaveX(ctx context.Context) []*EventResourceType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventResourceTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventResourceTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
