// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/event"
	"github.com/armada/orbital/ent/eventresourcetype"
	"github.com/armada/orbital/ent/predicate"
	"github.com/google/uuid"
)

// EventResourceTypeUpdate is the builder for updating EventResourceType entities.
type EventResourceTypeUpdate struct {
	config
	hooks    []Hook
	mutation *EventResourceTypeMutation
}

// Where appends a list predicates to the EventResourceTypeUpdate builder.
func (_u *EventResourceTypeUpdate) Where(ps ...predicate.EventResourceType) *EventResourceTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *EventResourceTypeUpdate) SetEventID(v uuid.UUID) *EventResourceTypeUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *EventResourceTypeUpdate) SetNillableEventID(v *uuid.UUID) *EventResourceTypeUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *EventResourceTypeUpdate) SetResourceType(v string) *EventResourceTypeUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *EventResourceTypeUpdate) SetNillableResourceType(v *string) *EventResourceTypeUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *EventResourceTypeUpdate) SetEvent(v *Event) *EventResourceTypeUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the EventResourceTypeMutation object of the builder.
func (_u *EventResourceTypeUpdate) Mutation() *EventResourceTypeMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *EventResourceTypeUpdate) ClearEvent() *EventResourceTypeUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventResourceTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventResourceTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventResourceTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventResourceTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventResourceTypeUpdate) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventResourceType.event"`)
	}
	return nil
}

func (_u *EventResourceTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventresourcetype.Table, eventresourcetype.Columns, sqlgraph.NewFieldSpec(eventresourcetype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(eventresourcetype.FieldResourceType, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventresourcetype.EventTable,
			Columns: []string{eventresourcetype.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventresourcetype.EventTable,
			Columns: []string{eventresourcetype.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventresourcetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventResourceTypeUpdateOne is the builder for updating a single EventResourceType entity.
type EventResourceTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventResourceTypeMutation
}

// SetEventID sets the "event_id" field.
func (_u *EventResourceTypeUpdateOne) SetEventID(v uuid.UUID) *EventResourceTypeUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *EventResourceTypeUpdateOne) SetNillableEventID(v *uuid.UUID) *EventResourceTypeUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *EventResourceTypeUpdateOne) SetResourceType(v string) *EventResourceTypeUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *EventResourceTypeUpdateOne) SetNillableResourceType(v *string) *EventResourceTypeUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *EventResourceTypeUpdateOne) SetEvent(v *Event) *EventResourceTypeUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the EventResourceTypeMutation object of the builder.
func (_u *EventResourceTypeUpdateOne) Mutation() *EventResourceTypeMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *EventResourceTypeUpdateOne) ClearEvent() *EventResourceTypeUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the EventResourceTypeUpdate builder.
func (_u *EventResourceTypeUpdateOne) Where(ps ...predicate.EventResourceType) *EventResourceTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventResourceTypeUpdateOne) Select(field string, fields ...string) *EventResourceTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EventResourceType entity.
func (_u *EventResourceTypeUpdateOne) Save(ctx context.Context) (*EventResourceType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventResourceTypeUpdateOne) SaveX(ctx context.Context) *EventResourceType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventResourceTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventResourceTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventResourceTypeUpdateOne) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventResourceType.event"`)
	}
	return nil
}

func (_u *EventResourceTypeUpdateOne) sqlSave(ctx context.Context) (_node *EventResourceType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventresourcetype.Table, eventresourcetype.Columns, sqlgraph.NewFieldSpec(eventresourcetype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventResourceType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventresourcetype.FieldID)
		for _, f := range fields {
			if !eventresourcetype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventresourcetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(eventresourcetype.FieldResourceType, field.TypeString, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventresourcetype.EventTable,
			Columns: []string{eventresourcetype.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventresourcetype.EventTable,
			Columns: []string{eventresourcetype.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EventResourceType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventresourcetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
