// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/exportjob"
	"github.com/armada/orbital/ent/predicate"
)

// ExportJobUpdate is the builder for updating ExportJob entities.
type ExportJobUpdate struct {
	config
	hooks    []Hook
	mutation *ExportJobMutation
}

// Where appends a list predicates to the ExportJobUpdate builder.
func (_u *ExportJobUpdate) Where(ps ...predicate.ExportJob) *ExportJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExportJobUpdate) SetCreatedBy(v string) *ExportJobUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableCreatedBy(v *string) *ExportJobUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ExportJobUpdate) ClearCreatedBy() *ExportJobUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExportJobUpdate) SetUpdatedAt(v time.Time) *ExportJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableUpdatedAt(v *time.Time) *ExportJobUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExportJobUpdate) ClearUpdatedAt() *ExportJobUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ExportJobUpdate) SetUpdatedBy(v string) *ExportJobUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableUpdatedBy(v *string) *ExportJobUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ExportJobUpdate) ClearUpdatedBy() *ExportJobUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDatacenterID sets the "datacenter_id" field.
func (_u *ExportJobUpdate) SetDatacenterID(v string) *ExportJobUpdate {
	_u.mutation.SetDatacenterID(v)
	return _u
}

// SetNillableDatacenterID sets the "datacenter_id" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableDatacenterID(v *string) *ExportJobUpdate {
	if v != nil {
		_u.SetDatacenterID(*v)
	}
	return _u
}

// SetDatacenterName sets the "datacenter_name" field.
func (_u *ExportJobUpdate) SetDatacenterName(v string) *ExportJobUpdate {
	_u.mutation.SetDatacenterName(v)
	return _u
}

// SetNillableDatacenterName sets the "datacenter_name" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableDatacenterName(v *string) *ExportJobUpdate {
	if v != nil {
		_u.SetDatacenterName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExportJobUpdate) SetStatus(v exportjob.Status) *ExportJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableStatus(v *exportjob.Status) *ExportJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetArtifactPath sets the "artifact_path" field.
func (_u *ExportJobUpdate) SetArtifactPath(v string) *ExportJobUpdate {
	_u.mutation.SetArtifactPath(v)
	return _u
}

// SetNillableArtifactPath sets the "artifact_path" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableArtifactPath(v *string) *ExportJobUpdate {
	if v != nil {
		_u.SetArtifactPath(*v)
	}
	return _u
}

// ClearArtifactPath clears the value of the "artifact_path" field.
func (_u *ExportJobUpdate) ClearArtifactPath() *ExportJobUpdate {
	_u.mutation.ClearArtifactPath()
	return _u
}

// SetError sets the "error" field.
func (_u *ExportJobUpdate) SetError(v string) *ExportJobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableError(v *string) *ExportJobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ExportJobUpdate) ClearError() *ExportJobUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ExportJobUpdate) SetStartedAt(v time.Time) *ExportJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableStartedAt(v *time.Time) *ExportJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ExportJobUpdate) ClearStartedAt() *ExportJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ExportJobUpdate) SetCompletedAt(v time.Time) *ExportJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ExportJobUpdate) SetNillableCompletedAt(v *time.Time) *ExportJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ExportJobUpdate) ClearCompletedAt() *ExportJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ExportJobMutation object of the builder.
func (_u *ExportJobUpdate) Mutation() *ExportJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExportJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExportJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExportJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExportJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExportJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := exportjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ExportJob.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ExportJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exportjob.Table, exportjob.Columns, sqlgraph.NewFieldSpec(exportjob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(exportjob.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(exportjob.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exportjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(exportjob.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(exportjob.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(exportjob.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.DatacenterID(); ok {
		_spec.SetField(exportjob.FieldDatacenterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DatacenterName(); ok {
		_spec.SetField(exportjob.FieldDatacenterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(exportjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ArtifactPath(); ok {
		_spec.SetField(exportjob.FieldArtifactPath, field.TypeString, value)
	}
	if _u.mutation.ArtifactPathCleared() {
		_spec.ClearField(exportjob.FieldArtifactPath, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(exportjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(exportjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(exportjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(exportjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(exportjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(exportjob.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exportjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExportJobUpdateOne is the builder for updating a single ExportJob entity.
type ExportJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExportJobMutation
}

// SetCreatedBy sets the "created_by" field.
func (_u *ExportJobUpdateOne) SetCreatedBy(v string) *ExportJobUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableCreatedBy(v *string) *ExportJobUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ExportJobUpdateOne) ClearCreatedBy() *ExportJobUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExportJobUpdateOne) SetUpdatedAt(v time.Time) *ExportJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableUpdatedAt(v *time.Time) *ExportJobUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ExportJobUpdateOne) ClearUpdatedAt() *ExportJobUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ExportJobUpdateOne) SetUpdatedBy(v string) *ExportJobUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableUpdatedBy(v *string) *ExportJobUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ExportJobUpdateOne) ClearUpdatedBy() *ExportJobUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDatacenterID sets the "datacenter_id" field.
func (_u *ExportJobUpdateOne) SetDatacenterID(v string) *ExportJobUpdateOne {
	_u.mutation.SetDatacenterID(v)
	return _u
}

// SetNillableDatacenterID sets the "datacenter_id" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableDatacenterID(v *string) *ExportJobUpdateOne {
	if v != nil {
		_u.SetDatacenterID(*v)
	}
	return _u
}

// SetDatacenterName sets the "datacenter_name" field.
func (_u *ExportJobUpdateOne) SetDatacenterName(v string) *ExportJobUpdateOne {
	_u.mutation.SetDatacenterName(v)
	return _u
}

// SetNillableDatacenterName sets the "datacenter_name" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableDatacenterName(v *string) *ExportJobUpdateOne {
	if v != nil {
		_u.SetDatacenterName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExportJobUpdateOne) SetStatus(v exportjob.Status) *ExportJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableStatus(v *exportjob.Status) *ExportJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetArtifactPath sets the "artifact_path" field.
func (_u *ExportJobUpdateOne) SetArtifactPath(v string) *ExportJobUpdateOne {
	_u.mutation.SetArtifactPath(v)
	return _u
}

// SetNillableArtifactPath sets the "artifact_path" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableArtifactPath(v *string) *ExportJobUpdateOne {
	if v != nil {
		_u.SetArtifactPath(*v)
	}
	return _u
}

// ClearArtifactPath clears the value of the "artifact_path" field.
func (_u *ExportJobUpdateOne) ClearArtifactPath() *ExportJobUpdateOne {
	_u.mutation.ClearArtifactPath()
	return _u
}

// SetError sets the "error" field.
func (_u *ExportJobUpdateOne) SetError(v string) *ExportJobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableError(v *string) *ExportJobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ExportJobUpdateOne) ClearError() *ExportJobUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ExportJobUpdateOne) SetStartedAt(v time.Time) *ExportJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableStartedAt(v *time.Time) *ExportJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ExportJobUpdateOne) ClearStartedAt() *ExportJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ExportJobUpdateOne) SetCompletedAt(v time.Time) *ExportJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ExportJobUpdateOne) SetNillableCompletedAt(v *time.Time) *ExportJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ExportJobUpdateOne) ClearCompletedAt() *ExportJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ExportJobMutation object of the builder.
func (_u *ExportJobUpdateOne) Mutation() *ExportJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExportJobUpdate builder.
func (_u *ExportJobUpdateOne) Where(ps ...predicate.ExportJob) *ExportJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExportJobUpdateOne) Select(field string, fields ...string) *ExportJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExportJob entity.
func (_u *ExportJobUpdateOne) Save(ctx context.Context) (*ExportJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExportJobUpdateOne) SaveX(ctx context.Context) *ExportJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExportJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExportJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExportJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := exportjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ExportJob.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ExportJobUpdateOne) sqlSave(ctx context.Context) (_node *ExportJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exportjob.Table, exportjob.Columns, sqlgraph.NewFieldSpec(exportjob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExportJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exportjob.FieldID)
		for _, f := range fields {
			if !exportjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exportjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(exportjob.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(exportjob.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exportjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(exportjob.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(exportjob.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(exportjob.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.DatacenterID(); ok {
		_spec.SetField(exportjob.FieldDatacenterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DatacenterName(); ok {
		_spec.SetField(exportjob.FieldDatacenterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(exportjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ArtifactPath(); ok {
		_spec.SetField(exportjob.FieldArtifactPath, field.TypeString, value)
	}
	if _u.mutation.ArtifactPathCleared() {
		_spec.ClearField(exportjob.FieldArtifactPath, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(exportjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(exportjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(exportjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(exportjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(exportjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(exportjob.FieldCompletedAt, field.TypeTime)
	}
	_node = &ExportJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exportjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
