// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/armada/orbital/ent/approvalrequest"
	"github.com/armada/orbital/ent/mergeattempt"
	"github.com/google/uuid"
)

// MergeAttempt is the model entity for the MergeAttempt schema.
type MergeAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// ApprovalRequestID holds the value of the "approval_request_id" field.
	ApprovalRequestID int64 `json:"approval_request_id,omitempty"`
	// AttemptedBy holds the value of the "attempted_by" field.
	AttemptedBy string `json:"attempted_by,omitempty"`
	// AttemptedAt holds the value of the "attempted_at" field.
	AttemptedAt time.Time `json:"attempted_at,omitempty"`
	// Results holds the value of the "results" field.
	Results json.RawMessage `json:"results,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MergeAttemptQuery when eager-loading is set.
	Edges        MergeAttemptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MergeAttemptEdges holds the relations/edges for other nodes in the graph.
type MergeAttemptEdges struct {
	// Request holds the value of the request edge.
	Request *ApprovalRequest `json:"request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MergeAttemptEdges) RequestOrErr() (*ApprovalRequest, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: approvalrequest.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MergeAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mergeattempt.FieldResults:
			values[i] = new([]byte)
		case mergeattempt.FieldApprovalRequestID:
			values[i] = new(sql.NullInt64)
		case mergeattempt.FieldCreatedBy, mergeattempt.FieldUpdatedBy, mergeattempt.FieldAttemptedBy, mergeattempt.FieldError:
			values[i] = new(sql.NullString)
		case mergeattempt.FieldCreatedAt, mergeattempt.FieldUpdatedAt, mergeattempt.FieldAttemptedAt:
			values[i] = new(sql.NullTime)
		case mergeattempt.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MergeAttempt fields.
func (_m *MergeAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mergeattempt.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case mergeattempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mergeattempt.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case mergeattempt.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case mergeattempt.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case mergeattempt.FieldApprovalRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approval_request_id", values[i])
			} else if value.Valid {
				_m.ApprovalRequestID = value.Int64
			}
		case mergeattempt.FieldAttemptedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attempted_by", values[i])
			} else if value.Valid {
				_m.AttemptedBy = value.String
			}
		case mergeattempt.FieldAttemptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field attempted_at", values[i])
			} else if value.Valid {
				_m.AttemptedAt = value.Time
			}
		case mergeattempt.FieldResults:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field results", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Results); err != nil {
					return fmt.Errorf("unmarshal field results: %w", err)
				}
			}
		case mergeattempt.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MergeAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *MergeAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequest queries the "request" edge of the MergeAttempt entity.
func (_m *MergeAttempt) QueryRequest() *ApprovalRequestQuery {
	return NewMergeAttemptClient(_m.config).QueryRequest(_m)
}

// Update returns a builder for updating this MergeAttempt.
// Note that you need to call MergeAttempt.Unwrap() before calling this method if this MergeAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MergeAttempt) Update() *MergeAttemptUpdateOne {
	return NewMergeAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MergeAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MergeAttempt) Unwrap() *MergeAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MergeAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MergeAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("MergeAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("approval_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApprovalRequestID))
	builder.WriteString(", ")
	builder.WriteString("attempted_by=")
	builder.WriteString(_m.AttemptedBy)
	builder.WriteString(", ")
	builder.WriteString("attempted_at=")
	builder.WriteString(_m.AttemptedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("results=")
	builder.WriteString(fmt.Sprintf("%v", _m.Results))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteByte(')')
	return builder.String()
}

// MergeAttempts is a parsable slice of MergeAttempt.
type MergeAttempts []*MergeAttempt
