// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/approvalrequest"
	"github.com/armada/orbital/ent/mergeattempt"
	"github.com/google/uuid"
)

// MergeAttemptCreate is the builder for creating a MergeAttempt entity.
type MergeAttemptCreate struct {
	config
	mutation *MergeAttemptMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MergeAttemptCreate) SetCreatedAt(v time.Time) *MergeAttemptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MergeAttemptCreate) SetNillableCreatedAt(v *time.Time) *MergeAttemptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *MergeAttemptCreate) SetCreatedBy(v string) *MergeAttemptCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *MergeAttemptCreate) SetNillableCreatedBy(v *string) *MergeAttemptCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MergeAttemptCreate) SetUpdatedAt(v time.Time) *MergeAttemptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MergeAttemptCreate) SetNillableUpdatedAt(v *time.Time) *MergeAttemptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *MergeAttemptCreate) SetUpdatedBy(v string) *MergeAttemptCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *MergeAttemptCreate) SetNillableUpdatedBy(v *string) *MergeAttemptCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetApprovalRequestID sets the "approval_request_id" field.
func (_c *MergeAttemptCreate) SetApprovalRequestID(v uuid.UUID) *MergeAttemptCreate {
	_c.mutation.SetApprovalRequestID(v)
	return _c
}

// SetAttemptedBy sets the "attempted_by" field.
func (_c *MergeAttemptCreate) SetAttemptedBy(v string) *MergeAttemptCreate {
	_c.mutation.SetAttemptedBy(v)
	return _c
}

// SetAttemptedAt sets the "attempted_at" field.
func (_c *MergeAttemptCreate) SetAttemptedAt(v time.Time) *MergeAttemptCreate {
	_c.mutation.SetAttemptedAt(v)
	return _c
}

// SetNillableAttemptedAt sets the "attempted_at" field if the given value is not nil.
func (_c *MergeAttemptCreate) SetNillableAttemptedAt(v *time.Time) *MergeAttemptCreate {
	if v != nil {
		_c.SetAttemptedAt(*v)
	}
	return _c
}

// SetResults sets the "results" field.
func (_c *MergeAttemptCreate) SetResults(v json.RawMessage) *MergeAttemptCreate {
	_c.mutation.SetResults(v)
	return _c
}

// SetError sets the "error" field.
func (_c *MergeAttemptCreate) SetError(v string) *MergeAttemptCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *MergeAttemptCreate) SetNillableError(v *string) *MergeAttemptCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MergeAttemptCreate) SetID(v uuid.UUID) *MergeAttemptCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MergeAttemptCreate) SetNillableID(v *uuid.UUID) *MergeAttemptCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRequestID sets the "request" edge to the ApprovalRequest entity by ID.
func (_c *MergeAttemptCreate) SetRequestID(id uuid.UUID) *MergeAttemptCreate {
	_c.mutation.SetRequestID(id)
	return _c
}

// SetRequest sets the "request" edge to the ApprovalRequest entity.
func (_c *MergeAttemptCreate) SetRequest(v *ApprovalRequest) *MergeAttemptCreate {
	return _c.SetRequestID(v.ID)
}

// Mutation returns the MergeAttemptMutation object of the builder.
func (_c *MergeAttemptCreate) Mutation() *MergeAttemptMutation {
	return _c.mutation
}

// Save creates the MergeAttempt in the database.
func (_c *MergeAttemptCreate) Save(ctx context.Context) (*MergeAttempt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MergeAttemptCreate) SaveX(ctx context.Context) *MergeAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MergeAttemptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MergeAttemptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MergeAttemptCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mergeattempt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.AttemptedAt(); !ok {
		v := mergeattempt.DefaultAttemptedAt()
		_c.mutation.SetAttemptedAt(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := mergeattempt.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mergeattempt.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MergeAttemptCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MergeAttempt.created_at"`)}
	}
	if _, ok := _c.mutation.ApprovalRequestID(); !ok {
		return &ValidationError{Name: "approval_request_id", err: errors.New(`ent: missing required field "MergeAttempt.approval_request_id"`)}
	}
	if _, ok := _c.mutation.AttemptedBy(); !ok {
		return &ValidationError{Name: "attempted_by", err: errors.New(`ent: missing required field "MergeAttempt.attempted_by"`)}
	}
	if v, ok := _c.mutation.AttemptedBy(); ok {
		if err := mergeattempt.AttemptedByValidator(v); err != nil {
			return &ValidationError{Name: "attempted_by", err: fmt.Errorf(`ent: validator failed for field "MergeAttempt.attempted_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptedAt(); !ok {
		return &ValidationError{Name: "attempted_at", err: errors.New(`ent: missing required field "MergeAttempt.attempted_at"`)}
	}
	if len(_c.mutation.RequestIDs()) == 0 {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required edge "MergeAttempt.request"`)}
	}
	return nil
}

func (_c *MergeAttemptCreate) sqlSave(ctx context.Context) (*MergeAttempt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MergeAttemptCreate) createSpec() (*MergeAttempt, *sqlgraph.CreateSpec) {
	var (
		_node = &MergeAttempt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mergeattempt.Table, sqlgraph.NewFieldSpec(mergeattempt.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mergeattempt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(mergeattempt.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mergeattempt.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(mergeattempt.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.AttemptedBy(); ok {
		_spec.SetField(mergeattempt.FieldAttemptedBy, field.TypeString, value)
		_node.AttemptedBy = value
	}
	if value, ok := _c.mutation.AttemptedAt(); ok {
		_spec.SetField(mergeattempt.FieldAttemptedAt, field.TypeTime, value)
		_node.AttemptedAt = value
	}
	if value, ok := _c.mutation.Results(); ok {
		_spec.SetField(mergeattempt.FieldResults, field.TypeJSON, value)
		_node.Results = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(mergeattempt.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if nodes := _c.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mergeattempt.RequestTable,
			Columns: []string{mergeattempt.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(approvalrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApprovalRequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MergeAttemptCreateBulk is the builder for creating many MergeAttempt entities in bulk.
type MergeAttemptCreateBulk struct {
	config
	err      error
	builders []*MergeAttemptCreate
}

// Save creates the MergeAttempt entities in the database.
func (_c *MergeAttemptCreateBulk) Save(ctx context.Context) ([]*MergeAttempt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MergeAttempt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MergeAttemptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MergeAttemptCreateBulk) SaveX(ctx context.Context) []*MergeAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MergeAttemptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MergeAttemptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
