// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/armada/orbital/ent/predicate"
	"github.com/armada/orbital/ent/registryartifact"
	"github.com/google/uuid"
)

// RegistryArtifactUpdate is the builder for updating RegistryArtifact entities.
type RegistryArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *RegistryArtifactMutation
}

// Where appends a list predicates to the RegistryArtifactUpdate builder.
func (_u *RegistryArtifactUpdate) Where(ps ...predicate.RegistryArtifact) *RegistryArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExportJobID sets the "export_job_id" field.
func (_u *RegistryArtifactUpdate) SetExportJobID(v uuid.UUID) *RegistryArtifactUpdate {
	_u.mutation.SetExportJobID(v)
	return _u
}

// SetNillableExportJobID sets the "export_job_id" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableExportJobID(v *uuid.UUID) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetExportJobID(*v)
	}
	return _u
}

// SetDatacenterID sets the "datacenter_id" field.
func (_u *RegistryArtifactUpdate) SetDatacenterID(v string) *RegistryArtifactUpdate {
	_u.mutation.SetDatacenterID(v)
	return _u
}

// SetNillableDatacenterID sets the "datacenter_id" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableDatacenterID(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetDatacenterID(*v)
	}
	return _u
}

// SetDatacenterName sets the "datacenter_name" field.
func (_u *RegistryArtifactUpdate) SetDatacenterName(v string) *RegistryArtifactUpdate {
	_u.mutation.SetDatacenterName(v)
	return _u
}

// SetNillableDatacenterName sets the "datacenter_name" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableDatacenterName(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetDatacenterName(*v)
	}
	return _u
}

// SetRegistry sets the "registry" field.
func (_u *RegistryArtifactUpdate) SetRegistry(v string) *RegistryArtifactUpdate {
	_u.mutation.SetRegistry(v)
	return _u
}

// SetNillableRegistry sets the "registry" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableRegistry(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetRegistry(*v)
	}
	return _u
}

// SetRepository sets the "repository" field.
func (_u *RegistryArtifactUpdate) SetRepository(v string) *RegistryArtifactUpdate {
	_u.mutation.SetRepository(v)
	return _u
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableRepository(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetRepository(*v)
	}
	return _u
}

// SetTag sets the "tag" field.
func (_u *RegistryArtifactUpdate) SetTag(v string) *RegistryArtifactUpdate {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableTag(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// SetDigest sets the "digest" field.
func (_u *RegistryArtifactUpdate) SetDigest(v string) *RegistryArtifactUpdate {
	_u.mutation.SetDigest(v)
	return _u
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableDigest(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetDigest(*v)
	}
	return _u
}

// ClearDigest clears the value of the "digest" field.
func (_u *RegistryArtifactUpdate) ClearDigest() *RegistryArtifactUpdate {
	_u.mutation.ClearDigest()
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *RegistryArtifactUpdate) SetSizeBytes(v int64) *RegistryArtifactUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableSizeBytes(v *int64) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *RegistryArtifactUpdate) AddSizeBytes(v int64) *RegistryArtifactUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (_u *RegistryArtifactUpdate) ClearSizeBytes() *RegistryArtifactUpdate {
	_u.mutation.ClearSizeBytes()
	return _u
}

// SetSigned sets the "signed" field.
func (_u *RegistryArtifactUpdate) SetSigned(v bool) *RegistryArtifactUpdate {
	_u.mutation.SetSigned(v)
	return _u
}

// SetNillableSigned sets the "signed" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableSigned(v *bool) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetSigned(*v)
	}
	return _u
}

// SetSigningKeyFingerprint sets the "signing_key_fingerprint" field.
func (_u *RegistryArtifactUpdate) SetSigningKeyFingerprint(v string) *RegistryArtifactUpdate {
	_u.mutation.SetSigningKeyFingerprint(v)
	return _u
}

// SetNillableSigningKeyFingerprint sets the "signing_key_fingerprint" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableSigningKeyFingerprint(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetSigningKeyFingerprint(*v)
	}
	return _u
}

// ClearSigningKeyFingerprint clears the value of the "signing_key_fingerprint" field.
func (_u *RegistryArtifactUpdate) ClearSigningKeyFingerprint() *RegistryArtifactUpdate {
	_u.mutation.ClearSigningKeyFingerprint()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RegistryArtifactUpdate) SetStatus(v registryartifact.Status) *RegistryArtifactUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableStatus(v *registryartifact.Status) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInitiatedBy sets the "initiated_by" field.
func (_u *RegistryArtifactUpdate) SetInitiatedBy(v int) *RegistryArtifactUpdate {
	_u.mutation.ResetInitiatedBy()
	_u.mutation.SetInitiatedBy(v)
	return _u
}

// SetNillableInitiatedBy sets the "initiated_by" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableInitiatedBy(v *int) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetInitiatedBy(*v)
	}
	return _u
}

// AddInitiatedBy adds value to the "initiated_by" field.
func (_u *RegistryArtifactUpdate) AddInitiatedBy(v int) *RegistryArtifactUpdate {
	_u.mutation.AddInitiatedBy(v)
	return _u
}

// ClearInitiatedBy clears the value of the "initiated_by" field.
func (_u *RegistryArtifactUpdate) ClearInitiatedBy() *RegistryArtifactUpdate {
	_u.mutation.ClearInitiatedBy()
	return _u
}

// SetInitiatedAt sets the "initiated_at" field.
func (_u *RegistryArtifactUpdate) SetInitiatedAt(v time.Time) *RegistryArtifactUpdate {
	_u.mutation.SetInitiatedAt(v)
	return _u
}

// SetNillableInitiatedAt sets the "initiated_at" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableInitiatedAt(v *time.Time) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetInitiatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RegistryArtifactUpdate) SetCompletedAt(v time.Time) *RegistryArtifactUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableCompletedAt(v *time.Time) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *RegistryArtifactUpdate) ClearCompletedAt() *RegistryArtifactUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetError sets the "error" field.
func (_u *RegistryArtifactUpdate) SetError(v string) *RegistryArtifactUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableError(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *RegistryArtifactUpdate) ClearError() *RegistryArtifactUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetEnriched sets the "enriched" field.
func (_u *RegistryArtifactUpdate) SetEnriched(v bool) *RegistryArtifactUpdate {
	_u.mutation.SetEnriched(v)
	return _u
}

// SetNillableEnriched sets the "enriched" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableEnriched(v *bool) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetEnriched(*v)
	}
	return _u
}

// SetEnricherError sets the "enricher_error" field.
func (_u *RegistryArtifactUpdate) SetEnricherError(v string) *RegistryArtifactUpdate {
	_u.mutation.SetEnricherError(v)
	return _u
}

// SetNillableEnricherError sets the "enricher_error" field if the given value is not nil.
func (_u *RegistryArtifactUpdate) SetNillableEnricherError(v *string) *RegistryArtifactUpdate {
	if v != nil {
		_u.SetEnricherError(*v)
	}
	return _u
}

// ClearEnricherError clears the value of the "enricher_error" field.
func (_u *RegistryArtifactUpdate) ClearEnricherError() *RegistryArtifactUpdate {
	_u.mutation.ClearEnricherError()
	return _u
}

// Mutation returns the RegistryArtifactMutation object of the builder.
func (_u *RegistryArtifactUpdate) Mutation() *RegistryArtifactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RegistryArtifactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegistryArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RegistryArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegistryArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegistryArtifactUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := registryartifact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RegistryArtifact.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RegistryArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(registryartifact.Table, registryartifact.Columns, sqlgraph.NewFieldSpec(registryartifact.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExportJobID(); ok {
		_spec.SetField(registryartifact.FieldExportJobID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.DatacenterID(); ok {
		_spec.SetField(registryartifact.FieldDatacenterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DatacenterName(); ok {
		_spec.SetField(registryartifact.FieldDatacenterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Registry(); ok {
		_spec.SetField(registryartifact.FieldRegistry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repository(); ok {
		_spec.SetField(registryartifact.FieldRepository, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(registryartifact.FieldTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Digest(); ok {
		_spec.SetField(registryartifact.FieldDigest, field.TypeString, value)
	}
	if _u.mutation.DigestCleared() {
		_spec.ClearField(registryartifact.FieldDigest, field.TypeString)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(registryartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(registryartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.SizeBytesCleared() {
		_spec.ClearField(registryartifact.FieldSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.Signed(); ok {
		_spec.SetField(registryartifact.FieldSigned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SigningKeyFingerprint(); ok {
		_spec.SetField(registryartifact.FieldSigningKeyFingerprint, field.TypeString, value)
	}
	if _u.mutation.SigningKeyFingerprintCleared() {
		_spec.ClearField(registryartifact.FieldSigningKeyFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(registryartifact.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.InitiatedBy(); ok {
		_spec.SetField(registryartifact.FieldInitiatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInitiatedBy(); ok {
		_spec.AddField(registryartifact.FieldInitiatedBy, field.TypeInt, value)
	}
	if _u.mutation.InitiatedByCleared() {
		_spec.ClearField(registryartifact.FieldInitiatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.InitiatedAt(); ok {
		_spec.SetField(registryartifact.FieldInitiatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(registryartifact.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(registryartifact.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(registryartifact.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(registryartifact.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.Enriched(); ok {
		_spec.SetField(registryartifact.FieldEnriched, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnricherError(); ok {
		_spec.SetField(registryartifact.FieldEnricherError, field.TypeString, value)
	}
	if _u.mutation.EnricherErrorCleared() {
		_spec.ClearField(registryartifact.FieldEnricherError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registryartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RegistryArtifactUpdateOne is the builder for updating a single RegistryArtifact entity.
type RegistryArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RegistryArtifactMutation
}

// SetExportJobID sets the "export_job_id" field.
func (_u *RegistryArtifactUpdateOne) SetExportJobID(v uuid.UUID) *RegistryArtifactUpdateOne {
	_u.mutation.SetExportJobID(v)
	return _u
}

// SetNillableExportJobID sets the "export_job_id" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableExportJobID(v *uuid.UUID) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetExportJobID(*v)
	}
	return _u
}

// SetDatacenterID sets the "datacenter_id" field.
func (_u *RegistryArtifactUpdateOne) SetDatacenterID(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetDatacenterID(v)
	return _u
}

// SetNillableDatacenterID sets the "datacenter_id" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableDatacenterID(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetDatacenterID(*v)
	}
	return _u
}

// SetDatacenterName sets the "datacenter_name" field.
func (_u *RegistryArtifactUpdateOne) SetDatacenterName(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetDatacenterName(v)
	return _u
}

// SetNillableDatacenterName sets the "datacenter_name" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableDatacenterName(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetDatacenterName(*v)
	}
	return _u
}

// SetRegistry sets the "registry" field.
func (_u *RegistryArtifactUpdateOne) SetRegistry(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetRegistry(v)
	return _u
}

// SetNillableRegistry sets the "registry" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableRegistry(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetRegistry(*v)
	}
	return _u
}

// SetRepository sets the "repository" field.
func (_u *RegistryArtifactUpdateOne) SetRepository(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetRepository(v)
	return _u
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableRepository(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetRepository(*v)
	}
	return _u
}

// SetTag sets the "tag" field.
func (_u *RegistryArtifactUpdateOne) SetTag(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableTag(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// SetDigest sets the "digest" field.
func (_u *RegistryArtifactUpdateOne) SetDigest(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetDigest(v)
	return _u
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableDigest(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetDigest(*v)
	}
	return _u
}

// ClearDigest clears the value of the "digest" field.
func (_u *RegistryArtifactUpdateOne) ClearDigest() *RegistryArtifactUpdateOne {
	_u.mutation.ClearDigest()
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *RegistryArtifactUpdateOne) SetSizeBytes(v int64) *RegistryArtifactUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableSizeBytes(v *int64) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *RegistryArtifactUpdateOne) AddSizeBytes(v int64) *RegistryArtifactUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (_u *RegistryArtifactUpdateOne) ClearSizeBytes() *RegistryArtifactUpdateOne {
	_u.mutation.ClearSizeBytes()
	return _u
}

// SetSigned sets the "signed" field.
func (_u *RegistryArtifactUpdateOne) SetSigned(v bool) *RegistryArtifactUpdateOne {
	_u.mutation.SetSigned(v)
	return _u
}

// SetNillableSigned sets the "signed" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableSigned(v *bool) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetSigned(*v)
	}
	return _u
}

// SetSigningKeyFingerprint sets the "signing_key_fingerprint" field.
func (_u *RegistryArtifactUpdateOne) SetSigningKeyFingerprint(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetSigningKeyFingerprint(v)
	return _u
}

// SetNillableSigningKeyFingerprint sets the "signing_key_fingerprint" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableSigningKeyFingerprint(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetSigningKeyFingerprint(*v)
	}
	return _u
}

// ClearSigningKeyFingerprint clears the value of the "signing_key_fingerprint" field.
func (_u *RegistryArtifactUpdateOne) ClearSigningKeyFingerprint() *RegistryArtifactUpdateOne {
	_u.mutation.ClearSigningKeyFingerprint()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RegistryArtifactUpdateOne) SetStatus(v registryartifact.Status) *RegistryArtifactUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableStatus(v *registryartifact.Status) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInitiatedBy sets the "initiated_by" field.
func (_u *RegistryArtifactUpdateOne) SetInitiatedBy(v int) *RegistryArtifactUpdateOne {
	_u.mutation.ResetInitiatedBy()
	_u.mutation.SetInitiatedBy(v)
	return _u
}

// SetNillableInitiatedBy sets the "initiated_by" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableInitiatedBy(v *int) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetInitiatedBy(*v)
	}
	return _u
}

// AddInitiatedBy adds value to the "initiated_by" field.
func (_u *RegistryArtifactUpdateOne) AddInitiatedBy(v int) *RegistryArtifactUpdateOne {
	_u.mutation.AddInitiatedBy(v)
	return _u
}

// ClearInitiatedBy clears the value of the "initiated_by" field.
func (_u *RegistryArtifactUpdateOne) ClearInitiatedBy() *RegistryArtifactUpdateOne {
	_u.mutation.ClearInitiatedBy()
	return _u
}

// SetInitiatedAt sets the "initiated_at" field.
func (_u *RegistryArtifactUpdateOne) SetInitiatedAt(v time.Time) *RegistryArtifactUpdateOne {
	_u.mutation.SetInitiatedAt(v)
	return _u
}

// SetNillableInitiatedAt sets the "initiated_at" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableInitiatedAt(v *time.Time) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetInitiatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RegistryArtifactUpdateOne) SetCompletedAt(v time.Time) *RegistryArtifactUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableCompletedAt(v *time.Time) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *RegistryArtifactUpdateOne) ClearCompletedAt() *RegistryArtifactUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetError sets the "error" field.
func (_u *RegistryArtifactUpdateOne) SetError(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableError(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *RegistryArtifactUpdateOne) ClearError() *RegistryArtifactUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetEnriched sets the "enriched" field.
func (_u *RegistryArtifactUpdateOne) SetEnriched(v bool) *RegistryArtifactUpdateOne {
	_u.mutation.SetEnriched(v)
	return _u
}

// SetNillableEnriched sets the "enriched" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableEnriched(v *bool) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetEnriched(*v)
	}
	return _u
}

// SetEnricherError sets the "enricher_error" field.
func (_u *RegistryArtifactUpdateOne) SetEnricherError(v string) *RegistryArtifactUpdateOne {
	_u.mutation.SetEnricherError(v)
	return _u
}

// SetNillableEnricherError sets the "enricher_error" field if the given value is not nil.
func (_u *RegistryArtifactUpdateOne) SetNillableEnricherError(v *string) *RegistryArtifactUpdateOne {
	if v != nil {
		_u.SetEnricherError(*v)
	}
	return _u
}

// ClearEnricherError clears the value of the "enricher_error" field.
func (_u *RegistryArtifactUpdateOne) ClearEnricherError() *RegistryArtifactUpdateOne {
	_u.mutation.ClearEnricherError()
	return _u
}

// Mutation returns the RegistryArtifactMutation object of the builder.
func (_u *RegistryArtifactUpdateOne) Mutation() *RegistryArtifactMutation {
	return _u.mutation
}

// Where appends a list predicates to the RegistryArtifactUpdate builder.
func (_u *RegistryArtifactUpdateOne) Where(ps ...predicate.RegistryArtifact) *RegistryArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RegistryArtifactUpdateOne) Select(field string, fields ...string) *RegistryArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RegistryArtifact entity.
func (_u *RegistryArtifactUpdateOne) Save(ctx context.Context) (*RegistryArtifact, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegistryArtifactUpdateOne) SaveX(ctx context.Context) *RegistryArtifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RegistryArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegistryArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegistryArtifactUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := registryartifact.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RegistryArtifact.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RegistryArtifactUpdateOne) sqlSave(ctx context.Context) (_node *RegistryArtifact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(registryartifact.Table, registryartifact.Columns, sqlgraph.NewFieldSpec(registryartifact.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RegistryArtifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registryartifact.FieldID)
		for _, f := range fields {
			if !registryartifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != registryartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExportJobID(); ok {
		_spec.SetField(registryartifact.FieldExportJobID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.DatacenterID(); ok {
		_spec.SetField(registryartifact.FieldDatacenterID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DatacenterName(); ok {
		_spec.SetField(registryartifact.FieldDatacenterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Registry(); ok {
		_spec.SetField(registryartifact.FieldRegistry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Repository(); ok {
		_spec.SetField(registryartifact.FieldRepository, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(registryartifact.FieldTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Digest(); ok {
		_spec.SetField(registryartifact.FieldDigest, field.TypeString, value)
	}
	if _u.mutation.DigestCleared() {
		_spec.ClearField(registryartifact.FieldDigest, field.TypeString)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(registryartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(registryartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.SizeBytesCleared() {
		_spec.ClearField(registryartifact.FieldSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.Signed(); ok {
		_spec.SetField(registryartifact.FieldSigned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SigningKeyFingerprint(); ok {
		_spec.SetField(registryartifact.FieldSigningKeyFingerprint, field.TypeString, value)
	}
	if _u.mutation.SigningKeyFingerprintCleared() {
		_spec.ClearField(registryartifact.FieldSigningKeyFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(registryartifact.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.InitiatedBy(); ok {
		_spec.SetField(registryartifact.FieldInitiatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInitiatedBy(); ok {
		_spec.AddField(registryartifact.FieldInitiatedBy, field.TypeInt, value)
	}
	if _u.mutation.InitiatedByCleared() {
		_spec.ClearField(registryartifact.FieldInitiatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.InitiatedAt(); ok {
		_spec.SetField(registryartifact.FieldInitiatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(registryartifact.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(registryartifact.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(registryartifact.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(registryartifact.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.Enriched(); ok {
		_spec.SetField(registryartifact.FieldEnriched, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnricherError(); ok {
		_spec.SetField(registryartifact.FieldEnricherError, field.TypeString, value)
	}
	if _u.mutation.EnricherErrorCleared() {
		_spec.ClearField(registryartifact.FieldEnricherError, field.TypeString)
	}
	_node = &RegistryArtifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registryartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
