apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
resources:
  - ../../base
  - secrets.yaml  # gitignored — see README.md for how to create this file
images:
  - name: armadaeksatest.azurecr.io/orbital
    newTag: v0.0.23
  - name: armadaeksatest.azurecr.io/configbundle-bundler
    newTag: v0.0.4

patches:
  - path: deployment-patch.yaml
