// Code generated by ent, DO NOT EDIT.

package auditevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the auditevent type in the database.
	Label = "audit_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOperations holds the string denoting the operations field in the database.
	FieldOperations = "operations"
	// FieldActor holds the string denoting the actor field in the database.
	FieldActor = "actor"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldEventCategory holds the string denoting the event_category field in the database.
	FieldEventCategory = "event_category"
	// EdgeResources holds the string denoting the resources edge name in mutations.
	EdgeResources = "resources"
	// EdgeResourceTypes holds the string denoting the resource_types edge name in mutations.
	EdgeResourceTypes = "resource_types"
	// Table holds the table name of the auditevent in the database.
	Table = "audit_events"
	// ResourcesTable is the table that holds the resources relation/edge.
	ResourcesTable = "audit_event_resources"
	// ResourcesInverseTable is the table name for the AuditEventResource entity.
	// It exists in this package in order to avoid circular dependency with the "auditeventresource" package.
	ResourcesInverseTable = "audit_event_resources"
	// ResourcesColumn is the table column denoting the resources relation/edge.
	ResourcesColumn = "audit_event_id"
	// ResourceTypesTable is the table that holds the resource_types relation/edge.
	ResourceTypesTable = "audit_event_resource_types"
	// ResourceTypesInverseTable is the table name for the AuditEventResourceType entity.
	// It exists in this package in order to avoid circular dependency with the "auditeventresourcetype" package.
	ResourceTypesInverseTable = "audit_event_resource_types"
	// ResourceTypesColumn is the table column denoting the resource_types relation/edge.
	ResourceTypesColumn = "audit_event_id"
)

// Columns holds all SQL columns for auditevent fields.
var Columns = []string{
	FieldID,
	FieldOperations,
	FieldActor,
	FieldTimestamp,
	FieldDetails,
	FieldEventCategory,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
	// DefaultEventCategory holds the default value on creation for the "event_category" field.
	DefaultEventCategory string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AuditEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActor orders the results by the actor field.
func ByActor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActor, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByEventCategory orders the results by the event_category field.
func ByEventCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventCategory, opts...).ToFunc()
}

// ByResourcesCount orders the results by resources count.
func ByResourcesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResourcesStep(), opts...)
	}
}

// ByResources orders the results by resources terms.
func ByResources(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResourcesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByResourceTypesCount orders the results by resource_types count.
func ByResourceTypesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResourceTypesStep(), opts...)
	}
}

// ByResourceTypes orders the results by resource_types terms.
func ByResourceTypes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResourceTypesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newResourcesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResourcesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResourcesTable, ResourcesColumn),
	)
}
func newResourceTypesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResourceTypesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResourceTypesTable, ResourceTypesColumn),
	)
}
