apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orb

resources:
  - ../../base

images:
  - name: armadaeksatest.azurecr.io/orb
    newTag: v0.0.2

configMapGenerator:
  - name: zot-config
    files:
      - config.json=zot-config.json
    options:
      disableNameSuffixHash: true

patches:
  - path: orb-patch.yaml
