apiVersion: apps/v1
kind: Deployment
metadata:
  name: orb
spec:
  template:
    spec:
      containers:
        - name: orb
          env:
            - name: ORB_OCI_REPO
              value: orbital/colo-galleon
            - name: ORB_CONSUMERS
              value: '[{"name":"configbundle-controller","url":"http://configbundle-controller.configbundle-system:8095/dispatch"}]'
