// Code generated by ent, DO NOT EDIT.

package auditeventresourcetype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the auditeventresourcetype type in the database.
	Label = "audit_event_resource_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuditEventID holds the string denoting the audit_event_id field in the database.
	FieldAuditEventID = "audit_event_id"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// EdgeAuditEvent holds the string denoting the audit_event edge name in mutations.
	EdgeAuditEvent = "audit_event"
	// Table holds the table name of the auditeventresourcetype in the database.
	Table = "audit_event_resource_types"
	// AuditEventTable is the table that holds the audit_event relation/edge.
	AuditEventTable = "audit_event_resource_types"
	// AuditEventInverseTable is the table name for the AuditEvent entity.
	// It exists in this package in order to avoid circular dependency with the "auditevent" package.
	AuditEventInverseTable = "audit_events"
	// AuditEventColumn is the table column denoting the audit_event relation/edge.
	AuditEventColumn = "audit_event_id"
)

// Columns holds all SQL columns for auditeventresourcetype fields.
var Columns = []string{
	FieldID,
	FieldAuditEventID,
	FieldResourceType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AuditEventResourceType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAuditEventID orders the results by the audit_event_id field.
func ByAuditEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditEventID, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByAuditEventField orders the results by audit_event field.
func ByAuditEventField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuditEventStep(), sql.OrderByField(field, opts...))
	}
}
func newAuditEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuditEventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuditEventTable, AuditEventColumn),
	)
}
