// Code generated by ent, DO NOT EDIT.

package auditeventresourcetype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/armada/orbital/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldLTE(FieldID, id))
}

// AuditEventID applies equality check predicate on the "audit_event_id" field. It's identical to AuditEventIDEQ.
func AuditEventID(v uuid.UUID) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldEQ(FieldAuditEventID, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldEQ(FieldResourceType, v))
}

// AuditEventIDEQ applies the EQ predicate on the "audit_event_id" field.
func AuditEventIDEQ(v uuid.UUID) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldEQ(FieldAuditEventID, v))
}

// AuditEventIDNEQ applies the NEQ predicate on the "audit_event_id" field.
func AuditEventIDNEQ(v uuid.UUID) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldNEQ(FieldAuditEventID, v))
}

// AuditEventIDIn applies the In predicate on the "audit_event_id" field.
func AuditEventIDIn(vs ...uuid.UUID) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldIn(FieldAuditEventID, vs...))
}

// AuditEventIDNotIn applies the NotIn predicate on the "audit_event_id" field.
func AuditEventIDNotIn(vs ...uuid.UUID) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldNotIn(FieldAuditEventID, vs...))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.FieldContainsFold(FieldResourceType, v))
}

// HasAuditEvent applies the HasEdge predicate on the "audit_event" edge.
func HasAuditEvent() predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuditEventTable, AuditEventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditEventWith applies the HasEdge predicate on the "audit_event" edge with a given conditions (other predicates).
func HasAuditEventWith(preds ...predicate.AuditEvent) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(func(s *sql.Selector) {
		step := newAuditEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditEventResourceType) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditEventResourceType) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditEventResourceType) predicate.AuditEventResourceType {
	return predicate.AuditEventResourceType(sql.NotPredicates(p))
}
